module RailsGuides
  class ApplicationMailer < ActionMailer::Base
  end

  class NotifierMailer < ApplicationMailer
    @account: untyped

    def welcome: (untyped) -> ActionMailer::MessageDelivery

    def self.welcome: (untyped) -> ActionMailer::MessageDelivery
  end

  class UserMailer < ApplicationMailer
    @user: untyped
    @url: String
    
    def welcome_email: () -> ActionMailer::MessageDelivery
  end
end
