D = Steep::Diagnostic

target :test do
  check "."
  signature "."

  repo_path "../../../"
  library "actionmailer:7.0"
  library "actionpack:7.0"
  library "activesupport:7.0"
  library "actionview:7.0"
  library "rack"

  library "cgi"
  library "date"
  library "logger"
  library "monitor"
  library "mutex_m"
  library "singleton"
  library "time"
  library "tsort"

  configure_code_diagnostics(D::Ruby.all_error)
end
