class Test
  class ApplicationController < ActionController::Base
  end

  class UsersController < ApplicationController
    include ActionView::Helpers

    def create: () -> void

    def update: () -> void
  end

  class View
    include ActionView::Helpers

    class User
    end

    @user : User

    def view_template_form: () -> void
  end
end
