module LaunchDarkly
  module Impl
    EventSenderResult: untyped

    class EventSender
      CURRENT_SCHEMA_VERSION: 4

      DEFAULT_RETRY_INTERVAL: 1

      def initialize: (untyped sdk_key, untyped config, ?untyped? http_client, ?untyped retry_interval) -> void

      def stop: () -> untyped

      def send_event_data: (untyped event_data, untyped description, untyped is_diagnostic) -> untyped
    end
  end
end
