module LaunchDarkly
  module Impl
    class RepeatingTask
      def initialize: (untyped interval, untyped start_delay, untyped task, untyped logger) -> void

      def start: () -> untyped

      def stop: () -> (untyped | nil | nil)
    end
  end
end
