module BusinessTime
  class ParsedTime
    include Comparable

    attr_reader hour: Integer
    attr_reader min: Integer
    attr_reader sec: Integer

    def initialize: (Integer hour, ?Integer min, ?Integer sec) -> void

    def self.parse: (Time | String time_or_string) -> BusinessTime::ParsedTime

    def to_s: () -> String

    def -: (Time other) -> Integer

    def <=>: (untyped other) -> Integer?
  end
end
