module Stripe
  module Terminal
    class Configuration < APIResource
      class BbposWisepad3 < ::Stripe::StripeObject
        def splashscreen: () -> (String | ::Stripe::File)?
      end

      class BbposWiseposE < ::Stripe::StripeObject
        def splashscreen: () -> (String | ::Stripe::File)?
      end

      class Cellular < ::Stripe::StripeObject
        def enabled: () -> bool
      end

      class Offline < ::Stripe::StripeObject
        def enabled: () -> bool?
      end

      class RebootWindow < ::Stripe::StripeObject
        def end_hour: () -> Integer

        def start_hour: () -> Integer
      end

      class StripeS700 < ::Stripe::StripeObject
        def splashscreen: () -> (String | ::Stripe::File)?
      end

      class StripeS710 < ::Stripe::StripeObject
        def splashscreen: () -> (String | ::Stripe::File)?
      end

      class Tipping < ::Stripe::StripeObject
        class Aed < ::Stripe::StripeObject
          def fixed_amounts: () -> ::Array[Integer]?

          def percentages: () -> ::Array[Integer]?

          def smart_tip_threshold: () -> Integer?
        end

        class Aud < ::Stripe::StripeObject
          def fixed_amounts: () -> ::Array[Integer]?

          def percentages: () -> ::Array[Integer]?

          def smart_tip_threshold: () -> Integer?
        end

        class Cad < ::Stripe::StripeObject
          def fixed_amounts: () -> ::Array[Integer]?

          def percentages: () -> ::Array[Integer]?

          def smart_tip_threshold: () -> Integer?
        end

        class Chf < ::Stripe::StripeObject
          def fixed_amounts: () -> ::Array[Integer]?

          def percentages: () -> ::Array[Integer]?

          def smart_tip_threshold: () -> Integer?
        end

        class Czk < ::Stripe::StripeObject
          def fixed_amounts: () -> ::Array[Integer]?

          def percentages: () -> ::Array[Integer]?

          def smart_tip_threshold: () -> Integer?
        end

        class Dkk < ::Stripe::StripeObject
          def fixed_amounts: () -> ::Array[Integer]?

          def percentages: () -> ::Array[Integer]?

          def smart_tip_threshold: () -> Integer?
        end

        class Eur < ::Stripe::StripeObject
          def fixed_amounts: () -> ::Array[Integer]?

          def percentages: () -> ::Array[Integer]?

          def smart_tip_threshold: () -> Integer?
        end

        class Gbp < ::Stripe::StripeObject
          def fixed_amounts: () -> ::Array[Integer]?

          def percentages: () -> ::Array[Integer]?

          def smart_tip_threshold: () -> Integer?
        end

        class Gip < ::Stripe::StripeObject
          def fixed_amounts: () -> ::Array[Integer]?

          def percentages: () -> ::Array[Integer]?

          def smart_tip_threshold: () -> Integer?
        end

        class Hkd < ::Stripe::StripeObject
          def fixed_amounts: () -> ::Array[Integer]?

          def percentages: () -> ::Array[Integer]?

          def smart_tip_threshold: () -> Integer?
        end

        class Huf < ::Stripe::StripeObject
          def fixed_amounts: () -> ::Array[Integer]?

          def percentages: () -> ::Array[Integer]?

          def smart_tip_threshold: () -> Integer?
        end

        class Jpy < ::Stripe::StripeObject
          def fixed_amounts: () -> ::Array[Integer]?

          def percentages: () -> ::Array[Integer]?

          def smart_tip_threshold: () -> Integer?
        end

        class Mxn < ::Stripe::StripeObject
          def fixed_amounts: () -> ::Array[Integer]?

          def percentages: () -> ::Array[Integer]?

          def smart_tip_threshold: () -> Integer?
        end

        class Myr < ::Stripe::StripeObject
          def fixed_amounts: () -> ::Array[Integer]?

          def percentages: () -> ::Array[Integer]?

          def smart_tip_threshold: () -> Integer?
        end

        class Nok < ::Stripe::StripeObject
          def fixed_amounts: () -> ::Array[Integer]?

          def percentages: () -> ::Array[Integer]?

          def smart_tip_threshold: () -> Integer?
        end

        class Nzd < ::Stripe::StripeObject
          def fixed_amounts: () -> ::Array[Integer]?

          def percentages: () -> ::Array[Integer]?

          def smart_tip_threshold: () -> Integer?
        end

        class Pln < ::Stripe::StripeObject
          def fixed_amounts: () -> ::Array[Integer]?

          def percentages: () -> ::Array[Integer]?

          def smart_tip_threshold: () -> Integer?
        end

        class Ron < ::Stripe::StripeObject
          def fixed_amounts: () -> ::Array[Integer]?

          def percentages: () -> ::Array[Integer]?

          def smart_tip_threshold: () -> Integer?
        end

        class Sek < ::Stripe::StripeObject
          def fixed_amounts: () -> ::Array[Integer]?

          def percentages: () -> ::Array[Integer]?

          def smart_tip_threshold: () -> Integer?
        end

        class Sgd < ::Stripe::StripeObject
          def fixed_amounts: () -> ::Array[Integer]?

          def percentages: () -> ::Array[Integer]?

          def smart_tip_threshold: () -> Integer?
        end

        class Usd < ::Stripe::StripeObject
          def fixed_amounts: () -> ::Array[Integer]?

          def percentages: () -> ::Array[Integer]?

          def smart_tip_threshold: () -> Integer?
        end

        def aed: () -> Aed?

        def aud: () -> Aud?

        def cad: () -> Cad?

        def chf: () -> Chf?

        def czk: () -> Czk?

        def dkk: () -> Dkk?

        def eur: () -> Eur?

        def gbp: () -> Gbp?

        def gip: () -> Gip?

        def hkd: () -> Hkd?

        def huf: () -> Huf?

        def jpy: () -> Jpy?

        def mxn: () -> Mxn?

        def myr: () -> Myr?

        def nok: () -> Nok?

        def nzd: () -> Nzd?

        def pln: () -> Pln?

        def ron: () -> Ron?

        def sek: () -> Sek?

        def sgd: () -> Sgd?

        def usd: () -> Usd?
      end

      class VerifoneM425 < ::Stripe::StripeObject
        def splashscreen: () -> (String | ::Stripe::File)?
      end

      class VerifoneP400 < ::Stripe::StripeObject
        def splashscreen: () -> (String | ::Stripe::File)?
      end

      class VerifoneP630 < ::Stripe::StripeObject
        def splashscreen: () -> (String | ::Stripe::File)?
      end

      class VerifoneUx700 < ::Stripe::StripeObject
        def splashscreen: () -> (String | ::Stripe::File)?
      end

      class VerifoneV660p < ::Stripe::StripeObject
        def splashscreen: () -> (String | ::Stripe::File)?
      end

      class Wifi < ::Stripe::StripeObject
        class EnterpriseEapPeap < ::Stripe::StripeObject
          def ca_certificate_file: () -> String?

          def password: () -> String

          def ssid: () -> String

          def username: () -> String
        end

        class EnterpriseEapTls < ::Stripe::StripeObject
          def ca_certificate_file: () -> String?

          def client_certificate_file: () -> String

          def private_key_file: () -> String

          def private_key_file_password: () -> String?

          def ssid: () -> String
        end

        class PersonalPsk < ::Stripe::StripeObject
          def password: () -> String

          def ssid: () -> String
        end

        def enterprise_eap_peap: () -> EnterpriseEapPeap?

        def enterprise_eap_tls: () -> EnterpriseEapTls?

        def personal_psk: () -> PersonalPsk?

        def type: () -> String
      end

      def bbpos_wisepad3: () -> BbposWisepad3?

      def bbpos_wisepos_e: () -> BbposWiseposE?

      def cellular: () -> Cellular?

      def deleted: () -> bool?

      def id: () -> String

      def is_account_default: () -> bool?

      def livemode: () -> bool

      def name: () -> String?

      def object: () -> String

      def offline: () -> Offline?

      def reboot_window: () -> RebootWindow?

      def stripe_s700: () -> StripeS700?

      def stripe_s710: () -> StripeS710?

      def tipping: () -> Tipping?

      def verifone_m425: () -> VerifoneM425?

      def verifone_p400: () -> VerifoneP400?

      def verifone_p630: () -> VerifoneP630?

      def verifone_ux700: () -> VerifoneUx700?

      def verifone_v660p: () -> VerifoneV660p?

      def wifi: () -> Wifi?

      def self.create: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Terminal::Configuration

      def self.delete: (String configuration, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Terminal::Configuration

      def delete: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Terminal::Configuration

      def self.list: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::Terminal::Configuration]

      def self.update: (String configuration, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Terminal::Configuration
    end
  end
end
