module Stripe
  module Terminal
    class ConnectionToken < APIResource
      def location: () -> String?

      def object: () -> String

      def secret: () -> String

      def self.create: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Terminal::ConnectionToken
    end
  end
end
