class YARD::Handlers::Ruby::Legacy::ClassConditionHandler < ::YARD::Handlers::Ruby::Legacy::Base
  #
  # @!method process
  # Main processing callback
  # @return [void]
  def process: () -> void
  # Parses the condition part of the if/unless statement
  #
  # @return [true, false, nil] true if the condition can be definitely
  #   parsed to true, false if not, and nil if the condition cannot be
  #   parsed with certainty (it's dynamic)
  # @since 0.5.5
  def parse_condition: () -> (true | false)?
  # @since 0.5.5
  def parse_then_block: () -> untyped
  # @since 0.5.5
  def parse_else_block: () -> untyped
end
