module Graphlient
  class Client
    def initialize: (String url, ?Hash[Symbol, untyped] options) ?{ (instance) -> void } -> void

    # FIXME: return GraphQL::Client::Response instead of untyped
    def query: (String query, ?Hash[Symbol | String, untyped]? variables) -> untyped
      | (?Hash[Symbol | String, untyped]? variables) { () -> untyped } -> untyped
  end
end
