module SPS
  module Converter
    module InstanceMethods
      def convert_decimal: (
          ?(::BigDecimal | ::String | ::Numeric)? value
        ) -> ::BigDecimal?

      def convert_text: (
          ?(::String | ::Symbol | ::Numeric)? value
        ) -> ::String?
    end
  end
end
