module Roo
  module Helpers
    module WeakInstanceCache
      private

      def instance_cache: (untyped key) { () -> untyped } -> untyped

      def instance_cache_finalizer: (untyped key) -> ^(Integer object_id) -> void
    end
  end
end
