module Stripe
  module TestHelpers
    module Treasury
      class InboundTransferService < StripeService
        def fail: (String id, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Treasury::InboundTransfer

        def return_inbound_transfer: (String id, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Treasury::InboundTransfer

        def succeed: (String id, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Treasury::InboundTransfer
      end
    end
  end
end
