module Stripe
  module TestHelpers
    module Treasury
      class OutboundPaymentService < StripeService
        def fail: (String id, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Treasury::OutboundPayment

        def post: (String id, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Treasury::OutboundPayment

        def return_outbound_payment: (String id, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Treasury::OutboundPayment

        def update: (String id, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Treasury::OutboundPayment
      end
    end
  end
end
