module Stripe
  module TestHelpers
    module Treasury
      class ReceivedDebitService < StripeService
        def create: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Treasury::ReceivedDebit
      end
    end
  end
end
