module Stripe
  module TestHelpers
    module Treasury
      class ReceivedCreditService < StripeService
        def create: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Treasury::ReceivedCredit
      end
    end
  end
end
