module LaunchDarkly
  module Impl
    module EvaluatorHelpers
      def self.off_result: (untyped flag, ?untyped? logger) -> untyped

      def self.target_match_result: (untyped target, untyped flag, ?untyped? logger) -> untyped

      def self.prerequisite_failed_result: (untyped prereq, untyped flag, ?untyped? logger) -> untyped

      def self.fallthrough_precomputed_results: (untyped flag) -> untyped

      def self.rule_precomputed_results: (untyped rule) -> untyped

      def self.evaluation_detail_for_off_variation: (untyped flag, untyped reason, ?untyped? logger) -> untyped

      def self.evaluation_detail_for_variation: (untyped flag, untyped index, untyped reason, ?untyped? logger) -> untyped
    end
  end
end
