module LaunchDarkly
  module Impl
    # A simple thread safe generic unbounded resource pool abstraction
    class UnboundedPool
      def initialize: (untyped instance_creator, untyped instance_destructor) -> void

      def acquire: () -> untyped

      def release: (untyped instance) -> untyped

      def dispose_all: () -> untyped
    end
  end
end
