module LaunchDarkly
  module Impl
    module Util
      def self.is_bool: (untyped aObject) -> untyped

      def self.current_time_millis: () -> untyped

      def self.default_http_headers: (untyped sdk_key, untyped config) -> untyped

      #
      # Generate an HTTP Header value containing the application meta information (@see #application).
      #
      # @return [String]
      #
      def self.application_header_value: (untyped application) -> untyped

      #
      # @param value [String]
      # @param name [Symbol]
      # @param logger [Logger]
      # @return [String]
      #
      def self.validate_application_value: (untyped value, untyped name, untyped logger) -> ("" | untyped)

      #
      # @param app [Hash]
      # @param logger [Logger]
      # @return [Hash]
      #
      def self.validate_application_info: (untyped app, untyped logger) -> { id: untyped, version: untyped }
    end
  end
end
