module Stripe
  # https://docs.stripe.com/api/customers/object#customer_object-address
  interface _Address
    # City, district, suburb, town, or village.
    def city: () -> String?

    # City, district, suburb, town, or village.
    def city=: (String?) -> String?

    # Two-letter country code ([ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)).
    def country: () -> String?

    # Two-letter country code ([ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)).
    def country=: (String?) -> String?

    # Address line 1 (e.g., street, PO Box, or company name).
    def line1: () -> String?

    # Address line 1 (e.g., street, PO Box, or company name).
    def line1=: (String?) -> String?

    # Address line 2 (e.g., apartment, suite, unit, or building).
    def line2: () -> String?

    # Address line 2 (e.g., apartment, suite, unit, or building).
    def line2=: (String?) -> String?

    # ZIP or postal code.
    def postal_code: () -> String?

    # ZIP or postal code.
    def postal_code=: (String?) -> String?

    # State, county, province, or region.
    def state: () -> String?

    # State, county, province, or region.
    def state=: (String?) -> String?
  end
end
