D = Steep::Diagnostic

target :test do
  check "."
  signature "."

  repo_path "../../../"
  library "recaptcha"

  library "actionpack"
  library "actionview"
  library "activemodel"
  library "activerecord"
  library "activesupport"
  library "cgi"
  library "date"
  library "erb"
  library "logger"
  library "monitor"
  library "mutex_m"
  library "rack"
  library "rails-dom-testing"
  library "railties"
  library "singleton"
  library "thor"
  library "tsort"
  library "time"

  configure_code_diagnostics(D::Ruby.all_error)
end
