D = Steep::Diagnostic

target :test do
  check "."
  signature "."

  repo_path "../../../"
  library "launchdarkly-server-sdk:6.4"
  library "forwardable"

  configure_code_diagnostics(D::Ruby.all_error)
end
