class CustomSessionsController < Devise::SessionsController
end

class User < ActiveRecord::Base
  include Devise::Models::DatabaseAuthenticatable
  include Devise::Models::Omniauthable
  include Devise::Models::Confirmable
  include Devise::Models::Recoverable
  include Devise::Models::Registerable
  include Devise::Models::Rememberable
  include Devise::Models::Trackable
  include Devise::Models::Timeoutable
  include Devise::Models::Validatable
  include Devise::Models::Lockable
end
