class CustomConfirmationsController < Devise::ConfirmationsController
end

class CustomOmniauthCallbacksController < Devise::OmniauthCallbacksController
end

class CustomPasswordsController < Devise::PasswordsController
end

class CustomRegistrationsController < Devise::RegistrationsController
end

class CustomSessionsController < Devise::SessionsController
end

class CustomUnlocksController < Devise::UnlocksController
end

class User < ActiveRecord::Base
  include Devise::Models::DatabaseAuthenticatable
  include Devise::Models::Omniauthable
  include Devise::Models::Confirmable
  include Devise::Models::Recoverable
  include Devise::Models::Registerable
  include Devise::Models::Rememberable
  include Devise::Models::Trackable
  include Devise::Models::Timeoutable
  include Devise::Models::Validatable
  include Devise::Models::Lockable
end
