module Stripe
  module Sigma
    class ScheduledQueryRun < APIResource
      class Error < ::Stripe::StripeObject
        def message: () -> String
      end

      def created: () -> Integer

      def data_load_time: () -> Integer

      def error: () -> Error?

      def file: () -> ::Stripe::File?

      def id: () -> String

      def livemode: () -> bool

      def object: () -> String

      def result_available_until: () -> Integer

      def sql: () -> String

      def status: () -> String

      def title: () -> String

      def self.list: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::Sigma::ScheduledQueryRun]
    end
  end
end
