class YARD::Serializers::ProcessSerializer < ::YARD::Serializers::Base
  # Creates a new ProcessSerializer for the shell command +cmd+
  #
  # @param [String] cmd the command that will accept data on stdin
  def initialize: (String cmd) -> void
end
