module Stripe
  module V2
    module Core
      module Accounts
        class PersonTokenService < StripeService
          def create: (String account_id, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::V2::Core::AccountPersonToken

          def retrieve: (String account_id, String id, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::V2::Core::AccountPersonToken
        end
      end
    end
  end
end
