module Stripe
  module V2
    module Core
      module Accounts
        class PersonService < StripeService
          def create: (String account_id, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::V2::Core::AccountPerson

          def delete: (String account_id, String id, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::V2::DeletedObject

          def list: (String account_id, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::V2::ListObject[::Stripe::V2::Core::AccountPerson]

          def retrieve: (String account_id, String id, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::V2::Core::AccountPerson

          def update: (String account_id, String id, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::V2::Core::AccountPerson
        end
      end
    end
  end
end
