module Stripe
  module FinancialConnections
    class AccountService < StripeService
      attr_reader owners: ::Stripe::FinancialConnections::AccountOwnerService

      def disconnect: (String account, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::FinancialConnections::Account

      def list: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::FinancialConnections::Account]

      def refresh: (String account, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::FinancialConnections::Account

      def retrieve: (String account, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::FinancialConnections::Account

      def subscribe: (String account, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::FinancialConnections::Account

      def unsubscribe: (String account, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::FinancialConnections::Account
    end
  end
end
