module Stripe
  module FinancialConnections
    class SessionService < StripeService
      def create: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::FinancialConnections::Session

      def retrieve: (String session, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::FinancialConnections::Session
    end
  end
end
