class YARD::Handlers::Ruby::HandlesExtension
  # @return [String] the extension matcher value
  attr_reader name: String
  # Creates a new extension with a specific matcher value +name+
  # @param [Object] name the matcher value to check against {#matches?}
  def initialize: (untyped name) -> void
  # Tests if the node matches the handler
  # @param [Parser::Ruby::AstNode] node a Ruby node
  # @return [Boolean] whether the +node+ matches the handler
  def matches?: (YARD::Parser::Ruby::AstNode node) -> bool
end
