module Timeout
  VERSION: "0.2.0"

  # Raised by Timeout.timeout when the block times out.
  class Error < RuntimeError
    attr_reader thread: untyped

    def self.catch: (*untyped args) { (untyped) -> untyped } -> untyped

    def exception: () -> untyped
  end

  # :stopdoc:
  THIS_FILE: untyped

  CALLER_OFFSET: untyped

  def self?.timeout: (untyped sec, ?untyped? klass, ?untyped? message) { (untyped) -> untyped } -> untyped
end
