module Google
  module Protobuf
    class AbstractMessage
      include Google::Protobuf::MessageExts

      extend Google::Protobuf::MessageExts::ClassMethods

      def self.decode: (String proto, Hash[untyped, untyped] options) -> instance

      def self.decode_json: (String json, Hash[untyped, untyped] options) -> instance

      def self.descriptor: () -> Descriptor

      def self.encode: (AbstractMessage msg, Hash[untyped, untyped] options) -> String

      def self.encode_json: (AbstractMessage msg, Hash[untyped, untyped] options) -> String

      public

      def ==: (untyped) -> bool

      def []: (String field) -> untyped

      def []=: (String field, untyped value) -> void

      def to_h: () -> Hash[untyped, untyped]

      def to_s: () -> String

      private

      def initialize: (*untyped) -> void
    end
  end
end
