module Google
  module Protobuf
    class DescriptorPool
      def self.generated_pool: () -> instance

      public

      def add_serialized_file: (String descriptor_data) -> void

      def build: () { () -> void } -> void

      def lookup: (String name) -> Descriptor?
    end
  end
end
