module Google
  module Protobuf
    class EnumDescriptor
      include Enumerable[Symbol]

      public

      def each: () { (Symbol) -> void } -> void

      def enummodule: () -> Module

      def file_descriptor: () -> FileDescriptor

      def lookup_name: (Symbol name) -> Integer?

      def lookup_value: (Integer value) -> Symbol?

      def name: () -> String

      private

      def initialize: (untyped, untyped, untyped) -> void
    end
  end
end
