module Google
  module Protobuf
    class FieldDescriptor
      public

      def clear: (AbstractMessage) -> void

      def default: () -> Integer

      def get: (AbstractMessage message) -> Integer

      def has?: (AbstractMessage message) -> bool

      def json_name: () -> String

      def label: () -> Symbol

      def name: () -> String

      def number: () -> Integer

      def set: (AbstractMessage message, Integer value) -> void

      def submsg_name: () -> String?

      def subtype: () -> Symbol?

      def type: () -> Symbol

      private

      def initialize: (untyped, untyped, untyped) -> void
    end
  end
end
