module Google
  module Protobuf
    class FileDescriptor
      public

      def name: () -> String

      def syntax: () -> Symbol

      private

      def initialize: (untyped, untyped, untyped) -> void
    end
  end
end
