module Google
  module Protobuf
    module MessageExts
      def self.included: (Class klass) -> void

      public

      def to_json: (?Hash[untyped, untyped] options) -> String

      def to_proto: (?Hash[untyped, untyped] options) -> String

      module ClassMethods
      end
    end
  end
end
