module Google
  module Protobuf
    class OneofDescriptor
      include Enumerable[untyped]

      public

      def each: () { (FieldDescriptor) -> void } -> void

      def name: () -> String

      private

      def initialize: (untyped, untyped, untyped) -> void
    end
  end
end
