module Google
  module Protobuf
    def self.decode: (singleton(AbstractMessage) klass, String proto, ?Hash[untyped, untyped] options) -> AbstractMessage

    def self.decode_json: (singleton(AbstractMessage) klass, String json, ?Hash[untyped, untyped] options) -> AbstractMessage

    def self.deep_copy: (RepeatedField | Map[untyped, untyped] | AbstractMessage obj) -> bot

    def self.discard_unknown: (untyped) -> untyped

    def self.encode: (AbstractMessage msg, ?untyped options) -> String

    def self.encode_json: (AbstractMessage msg, ?untyped options) -> String
  end
end
