module Faker
  class Base
    def self.unique: () -> UniqueGenerator
  end

  class UniqueGenerator
    def self.clear: () -> {}
    def clear: () -> {}
    def exclude: (Symbol, Array[String]|Array[Hash[Symbol, untyped]], Array[String]) -> void
  end

  class Config
    def self.random=: (Random | nil) -> Random
    def self.locale=: (Symbol | String) -> (Symbol | String)
  end

  class Address < Base
    def self.street_name: () -> String
    def self.secondary_address: () -> String
    def self.building_number: () -> String
    def self.community: () -> String
    def self.mail_box: () -> String
  end

  class Name < Base
    def self.name: () -> String
  end

  class Internet < Base
    # https://github.com/faker-ruby/faker/blob/v2.23.0/lib/faker/default/internet.rb#L32
    def self.email: (?name: String?, ?separators: Array[String]?, ?domain: String?) -> String
  end

  class Company < Base
    def self.bs: () -> String
    def self.name: () -> String
  end

  class Lorem < Base
  end
end
