module Faker
  class Lorem < Faker::Base
    # https://github.com/faker-ruby/faker/blob/v2.23.0/lib/faker/default/lorem.rb#L5
    def self.sentence: (?word_count: Integer, ?supplemental: bool, ?random_words_to_add: Integer) -> String
    def self.paragraph: (?sentence_count: Integer, ?supplemental: bool, ?random_sentences_to_add: Integer) -> String
  end
end
