class Post < ActiveRecord::Base
  extend Audited::Auditor::ClassMethods
  extend Audited::Auditor::AuditedClassMethods
  include Audited::Auditor::AuditedInstanceMethods
end

class Comment < ActiveRecord::Base
  extend Audited::Auditor::ClassMethods
  extend Audited::Auditor::AuditedClassMethods
  include Audited::Auditor::AuditedInstanceMethods
end

class User < ActiveRecord::Base
  extend Audited::Auditor::ClassMethods
  extend Audited::Auditor::AuditedClassMethods
  include Audited::Auditor::AuditedInstanceMethods
end
