module Roo
  class Font
    attr_accessor bold: untyped

    attr_accessor italic: untyped

    attr_accessor underline: untyped

    def bold?: () -> untyped

    def italic?: () -> untyped

    def underline?: () -> untyped
  end
end
