module Roo
  class Spreadsheet
    interface _Path
      def path: () -> string
    end

    def self.open: (string | _Path path, ?::Hash[Symbol, untyped] options) -> (::Roo::OpenOffice | ::Roo::Excelx | ::Roo::CSV)

    def self.extension_for: (string path, ::Hash[Symbol, untyped] options) -> Symbol
  end
end
