module Roo
  module Tempdir[CellValue]
    @tempdirs: Hash[Integer, Array[String]]

    def finalize_tempdirs: (Integer object_id) -> void

    def make_tempdir: (::Roo::Base[CellValue] object, String | nil prefix, String | nil root) -> String
  end
end
