module Roo
  module Tempdir[CellValue]
    @tempdirs: Hash[int, Array[String]]

    def finalize_tempdirs: (int object_id) -> void

    def make_tempdir: (::Roo::Base[CellValue] object, String | nil prefix, String | nil root) -> String
  end
end
