module Stripe
  module Reporting
    class ReportTypeService < StripeService
      def list: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::Reporting::ReportType]

      def retrieve: (String report_type, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Reporting::ReportType
    end
  end
end
