D = Steep::Diagnostic

target :test do
  check "."
  signature '.'

  repo_path "../../../"

  library "date"
  library "time"
  library "monitor"
  library "singleton"
  library "logger"
  library "mutex_m"
  library "minitest"
  library "json"
  library "benchmark"
  library "digest"
  library "set"

  library "nokogiri"
  library "activesupport"

  library "business_time"

  configure_code_diagnostics(D::Ruby.all_error)
end
