module Stripe
  module Tax
    class Registration < APIResource
      class CountryOptions < ::Stripe::StripeObject
        class Ae < ::Stripe::StripeObject
          class Standard < ::Stripe::StripeObject
            def place_of_supply_scheme: () -> String
          end

          def standard: () -> Standard?

          def type: () -> String
        end

        class Al < ::Stripe::StripeObject
          def type: () -> String
        end

        class Am < ::Stripe::StripeObject
          def type: () -> String
        end

        class Ao < ::Stripe::StripeObject
          def type: () -> String
        end

        class At < ::Stripe::StripeObject
          class Standard < ::Stripe::StripeObject
            def place_of_supply_scheme: () -> String
          end

          def standard: () -> Standard?

          def type: () -> String
        end

        class Au < ::Stripe::StripeObject
          class Standard < ::Stripe::StripeObject
            def place_of_supply_scheme: () -> String
          end

          def standard: () -> Standard?

          def type: () -> String
        end

        class Aw < ::Stripe::StripeObject
          def type: () -> String
        end

        class Az < ::Stripe::StripeObject
          def type: () -> String
        end

        class Ba < ::Stripe::StripeObject
          def type: () -> String
        end

        class Bb < ::Stripe::StripeObject
          def type: () -> String
        end

        class Bd < ::Stripe::StripeObject
          def type: () -> String
        end

        class Be < ::Stripe::StripeObject
          class Standard < ::Stripe::StripeObject
            def place_of_supply_scheme: () -> String
          end

          def standard: () -> Standard?

          def type: () -> String
        end

        class Bf < ::Stripe::StripeObject
          def type: () -> String
        end

        class Bg < ::Stripe::StripeObject
          class Standard < ::Stripe::StripeObject
            def place_of_supply_scheme: () -> String
          end

          def standard: () -> Standard?

          def type: () -> String
        end

        class Bh < ::Stripe::StripeObject
          def type: () -> String
        end

        class Bj < ::Stripe::StripeObject
          def type: () -> String
        end

        class Bs < ::Stripe::StripeObject
          def type: () -> String
        end

        class By < ::Stripe::StripeObject
          def type: () -> String
        end

        class Ca < ::Stripe::StripeObject
          class ProvinceStandard < ::Stripe::StripeObject
            def province: () -> String
          end

          def province_standard: () -> ProvinceStandard?

          def type: () -> String
        end

        class Cd < ::Stripe::StripeObject
          def type: () -> String
        end

        class Ch < ::Stripe::StripeObject
          class Standard < ::Stripe::StripeObject
            def place_of_supply_scheme: () -> String
          end

          def standard: () -> Standard?

          def type: () -> String
        end

        class Cl < ::Stripe::StripeObject
          def type: () -> String
        end

        class Cm < ::Stripe::StripeObject
          def type: () -> String
        end

        class Co < ::Stripe::StripeObject
          def type: () -> String
        end

        class Cr < ::Stripe::StripeObject
          def type: () -> String
        end

        class Cv < ::Stripe::StripeObject
          def type: () -> String
        end

        class Cy < ::Stripe::StripeObject
          class Standard < ::Stripe::StripeObject
            def place_of_supply_scheme: () -> String
          end

          def standard: () -> Standard?

          def type: () -> String
        end

        class Cz < ::Stripe::StripeObject
          class Standard < ::Stripe::StripeObject
            def place_of_supply_scheme: () -> String
          end

          def standard: () -> Standard?

          def type: () -> String
        end

        class De < ::Stripe::StripeObject
          class Standard < ::Stripe::StripeObject
            def place_of_supply_scheme: () -> String
          end

          def standard: () -> Standard?

          def type: () -> String
        end

        class Dk < ::Stripe::StripeObject
          class Standard < ::Stripe::StripeObject
            def place_of_supply_scheme: () -> String
          end

          def standard: () -> Standard?

          def type: () -> String
        end

        class Ec < ::Stripe::StripeObject
          def type: () -> String
        end

        class Ee < ::Stripe::StripeObject
          class Standard < ::Stripe::StripeObject
            def place_of_supply_scheme: () -> String
          end

          def standard: () -> Standard?

          def type: () -> String
        end

        class Eg < ::Stripe::StripeObject
          def type: () -> String
        end

        class Es < ::Stripe::StripeObject
          class Standard < ::Stripe::StripeObject
            def place_of_supply_scheme: () -> String
          end

          def standard: () -> Standard?

          def type: () -> String
        end

        class Et < ::Stripe::StripeObject
          def type: () -> String
        end

        class Fi < ::Stripe::StripeObject
          class Standard < ::Stripe::StripeObject
            def place_of_supply_scheme: () -> String
          end

          def standard: () -> Standard?

          def type: () -> String
        end

        class Fr < ::Stripe::StripeObject
          class Standard < ::Stripe::StripeObject
            def place_of_supply_scheme: () -> String
          end

          def standard: () -> Standard?

          def type: () -> String
        end

        class Gb < ::Stripe::StripeObject
          class Standard < ::Stripe::StripeObject
            def place_of_supply_scheme: () -> String
          end

          def standard: () -> Standard?

          def type: () -> String
        end

        class Ge < ::Stripe::StripeObject
          def type: () -> String
        end

        class Gn < ::Stripe::StripeObject
          def type: () -> String
        end

        class Gr < ::Stripe::StripeObject
          class Standard < ::Stripe::StripeObject
            def place_of_supply_scheme: () -> String
          end

          def standard: () -> Standard?

          def type: () -> String
        end

        class Hr < ::Stripe::StripeObject
          class Standard < ::Stripe::StripeObject
            def place_of_supply_scheme: () -> String
          end

          def standard: () -> Standard?

          def type: () -> String
        end

        class Hu < ::Stripe::StripeObject
          class Standard < ::Stripe::StripeObject
            def place_of_supply_scheme: () -> String
          end

          def standard: () -> Standard?

          def type: () -> String
        end

        class Id < ::Stripe::StripeObject
          def type: () -> String
        end

        class Ie < ::Stripe::StripeObject
          class Standard < ::Stripe::StripeObject
            def place_of_supply_scheme: () -> String
          end

          def standard: () -> Standard?

          def type: () -> String
        end

        class In < ::Stripe::StripeObject
          def type: () -> String
        end

        class Is < ::Stripe::StripeObject
          def type: () -> String
        end

        class It < ::Stripe::StripeObject
          class Standard < ::Stripe::StripeObject
            def place_of_supply_scheme: () -> String
          end

          def standard: () -> Standard?

          def type: () -> String
        end

        class Jp < ::Stripe::StripeObject
          class Standard < ::Stripe::StripeObject
            def place_of_supply_scheme: () -> String
          end

          def standard: () -> Standard?

          def type: () -> String
        end

        class Ke < ::Stripe::StripeObject
          def type: () -> String
        end

        class Kg < ::Stripe::StripeObject
          def type: () -> String
        end

        class Kh < ::Stripe::StripeObject
          def type: () -> String
        end

        class Kr < ::Stripe::StripeObject
          def type: () -> String
        end

        class Kz < ::Stripe::StripeObject
          def type: () -> String
        end

        class La < ::Stripe::StripeObject
          def type: () -> String
        end

        class Lk < ::Stripe::StripeObject
          def type: () -> String
        end

        class Lt < ::Stripe::StripeObject
          class Standard < ::Stripe::StripeObject
            def place_of_supply_scheme: () -> String
          end

          def standard: () -> Standard?

          def type: () -> String
        end

        class Lu < ::Stripe::StripeObject
          class Standard < ::Stripe::StripeObject
            def place_of_supply_scheme: () -> String
          end

          def standard: () -> Standard?

          def type: () -> String
        end

        class Lv < ::Stripe::StripeObject
          class Standard < ::Stripe::StripeObject
            def place_of_supply_scheme: () -> String
          end

          def standard: () -> Standard?

          def type: () -> String
        end

        class Ma < ::Stripe::StripeObject
          def type: () -> String
        end

        class Md < ::Stripe::StripeObject
          def type: () -> String
        end

        class Me < ::Stripe::StripeObject
          def type: () -> String
        end

        class Mk < ::Stripe::StripeObject
          def type: () -> String
        end

        class Mr < ::Stripe::StripeObject
          def type: () -> String
        end

        class Mt < ::Stripe::StripeObject
          class Standard < ::Stripe::StripeObject
            def place_of_supply_scheme: () -> String
          end

          def standard: () -> Standard?

          def type: () -> String
        end

        class Mx < ::Stripe::StripeObject
          def type: () -> String
        end

        class My < ::Stripe::StripeObject
          def type: () -> String
        end

        class Ng < ::Stripe::StripeObject
          def type: () -> String
        end

        class Nl < ::Stripe::StripeObject
          class Standard < ::Stripe::StripeObject
            def place_of_supply_scheme: () -> String
          end

          def standard: () -> Standard?

          def type: () -> String
        end

        class No < ::Stripe::StripeObject
          class Standard < ::Stripe::StripeObject
            def place_of_supply_scheme: () -> String
          end

          def standard: () -> Standard?

          def type: () -> String
        end

        class Np < ::Stripe::StripeObject
          def type: () -> String
        end

        class Nz < ::Stripe::StripeObject
          class Standard < ::Stripe::StripeObject
            def place_of_supply_scheme: () -> String
          end

          def standard: () -> Standard?

          def type: () -> String
        end

        class Om < ::Stripe::StripeObject
          def type: () -> String
        end

        class Pe < ::Stripe::StripeObject
          def type: () -> String
        end

        class Ph < ::Stripe::StripeObject
          def type: () -> String
        end

        class Pl < ::Stripe::StripeObject
          class Standard < ::Stripe::StripeObject
            def place_of_supply_scheme: () -> String
          end

          def standard: () -> Standard?

          def type: () -> String
        end

        class Pt < ::Stripe::StripeObject
          class Standard < ::Stripe::StripeObject
            def place_of_supply_scheme: () -> String
          end

          def standard: () -> Standard?

          def type: () -> String
        end

        class Ro < ::Stripe::StripeObject
          class Standard < ::Stripe::StripeObject
            def place_of_supply_scheme: () -> String
          end

          def standard: () -> Standard?

          def type: () -> String
        end

        class Rs < ::Stripe::StripeObject
          def type: () -> String
        end

        class Ru < ::Stripe::StripeObject
          def type: () -> String
        end

        class Sa < ::Stripe::StripeObject
          def type: () -> String
        end

        class Se < ::Stripe::StripeObject
          class Standard < ::Stripe::StripeObject
            def place_of_supply_scheme: () -> String
          end

          def standard: () -> Standard?

          def type: () -> String
        end

        class Sg < ::Stripe::StripeObject
          class Standard < ::Stripe::StripeObject
            def place_of_supply_scheme: () -> String
          end

          def standard: () -> Standard?

          def type: () -> String
        end

        class Si < ::Stripe::StripeObject
          class Standard < ::Stripe::StripeObject
            def place_of_supply_scheme: () -> String
          end

          def standard: () -> Standard?

          def type: () -> String
        end

        class Sk < ::Stripe::StripeObject
          class Standard < ::Stripe::StripeObject
            def place_of_supply_scheme: () -> String
          end

          def standard: () -> Standard?

          def type: () -> String
        end

        class Sn < ::Stripe::StripeObject
          def type: () -> String
        end

        class Sr < ::Stripe::StripeObject
          def type: () -> String
        end

        class Th < ::Stripe::StripeObject
          def type: () -> String
        end

        class Tj < ::Stripe::StripeObject
          def type: () -> String
        end

        class Tr < ::Stripe::StripeObject
          def type: () -> String
        end

        class Tw < ::Stripe::StripeObject
          def type: () -> String
        end

        class Tz < ::Stripe::StripeObject
          def type: () -> String
        end

        class Ua < ::Stripe::StripeObject
          def type: () -> String
        end

        class Ug < ::Stripe::StripeObject
          def type: () -> String
        end

        class Us < ::Stripe::StripeObject
          class AdmissionsTax < ::Stripe::StripeObject
            def jurisdiction: () -> String
          end

          class AttendanceTax < ::Stripe::StripeObject
            def jurisdiction: () -> String
          end

          class EntertainmentTax < ::Stripe::StripeObject
            def jurisdiction: () -> String
          end

          class GrossReceiptsTax < ::Stripe::StripeObject
            def jurisdiction: () -> String
          end

          class HospitalityTax < ::Stripe::StripeObject
            def jurisdiction: () -> String
          end

          class LocalAmusementTax < ::Stripe::StripeObject
            def jurisdiction: () -> String
          end

          class LocalLeaseTax < ::Stripe::StripeObject
            def jurisdiction: () -> String
          end

          class LuxuryTax < ::Stripe::StripeObject
            def jurisdiction: () -> String
          end

          class MassTransitParkingTax < ::Stripe::StripeObject
            def jurisdiction: () -> String
          end

          class ParkingTax < ::Stripe::StripeObject
            def jurisdiction: () -> String
          end

          class ResortTax < ::Stripe::StripeObject
            def jurisdiction: () -> String
          end

          class StateSalesTax < ::Stripe::StripeObject
            class Election < ::Stripe::StripeObject
              def jurisdiction: () -> String?

              def type: () -> String
            end

            def elections: () -> ::Array[Election]?
          end

          class TourismTax < ::Stripe::StripeObject
            def jurisdiction: () -> String
          end

          def admissions_tax: () -> AdmissionsTax?

          def attendance_tax: () -> AttendanceTax?

          def entertainment_tax: () -> EntertainmentTax?

          def gross_receipts_tax: () -> GrossReceiptsTax?

          def hospitality_tax: () -> HospitalityTax?

          def local_amusement_tax: () -> LocalAmusementTax?

          def local_lease_tax: () -> LocalLeaseTax?

          def luxury_tax: () -> LuxuryTax?

          def mass_transit_parking_tax: () -> MassTransitParkingTax?

          def parking_tax: () -> ParkingTax?

          def resort_tax: () -> ResortTax?

          def state: () -> String

          def state_sales_tax: () -> StateSalesTax?

          def tourism_tax: () -> TourismTax?

          def type: () -> String
        end

        class Uy < ::Stripe::StripeObject
          def type: () -> String
        end

        class Uz < ::Stripe::StripeObject
          def type: () -> String
        end

        class Vn < ::Stripe::StripeObject
          def type: () -> String
        end

        class Za < ::Stripe::StripeObject
          def type: () -> String
        end

        class Zm < ::Stripe::StripeObject
          def type: () -> String
        end

        class Zw < ::Stripe::StripeObject
          def type: () -> String
        end

        def ae: () -> Ae?

        def al: () -> Al?

        def am: () -> Am?

        def ao: () -> Ao?

        def at: () -> At?

        def au: () -> Au?

        def aw: () -> Aw?

        def az: () -> Az?

        def ba: () -> Ba?

        def bb: () -> Bb?

        def bd: () -> Bd?

        def be: () -> Be?

        def bf: () -> Bf?

        def bg: () -> Bg?

        def bh: () -> Bh?

        def bj: () -> Bj?

        def bs: () -> Bs?

        def by: () -> By?

        def ca: () -> Ca?

        def cd: () -> Cd?

        def ch: () -> Ch?

        def cl: () -> Cl?

        def cm: () -> Cm?

        def co: () -> Co?

        def cr: () -> Cr?

        def cv: () -> Cv?

        def cy: () -> Cy?

        def cz: () -> Cz?

        def de: () -> De?

        def dk: () -> Dk?

        def ec: () -> Ec?

        def ee: () -> Ee?

        def eg: () -> Eg?

        def es: () -> Es?

        def et: () -> Et?

        def fi: () -> Fi?

        def fr: () -> Fr?

        def gb: () -> Gb?

        def ge: () -> Ge?

        def gn: () -> Gn?

        def gr: () -> Gr?

        def hr: () -> Hr?

        def hu: () -> Hu?

        def id: () -> Id?

        def ie: () -> Ie?

        def in: () -> In?

        def is: () -> Is?

        def it: () -> It?

        def jp: () -> Jp?

        def ke: () -> Ke?

        def kg: () -> Kg?

        def kh: () -> Kh?

        def kr: () -> Kr?

        def kz: () -> Kz?

        def la: () -> La?

        def lk: () -> Lk?

        def lt: () -> Lt?

        def lu: () -> Lu?

        def lv: () -> Lv?

        def ma: () -> Ma?

        def md: () -> Md?

        def me: () -> Me?

        def mk: () -> Mk?

        def mr: () -> Mr?

        def mt: () -> Mt?

        def mx: () -> Mx?

        def my: () -> My?

        def ng: () -> Ng?

        def nl: () -> Nl?

        def no: () -> No?

        def np: () -> Np?

        def nz: () -> Nz?

        def om: () -> Om?

        def pe: () -> Pe?

        def ph: () -> Ph?

        def pl: () -> Pl?

        def pt: () -> Pt?

        def ro: () -> Ro?

        def rs: () -> Rs?

        def ru: () -> Ru?

        def sa: () -> Sa?

        def se: () -> Se?

        def sg: () -> Sg?

        def si: () -> Si?

        def sk: () -> Sk?

        def sn: () -> Sn?

        def sr: () -> Sr?

        def th: () -> Th?

        def tj: () -> Tj?

        def tr: () -> Tr?

        def tw: () -> Tw?

        def tz: () -> Tz?

        def ua: () -> Ua?

        def ug: () -> Ug?

        def us: () -> Us?

        def uy: () -> Uy?

        def uz: () -> Uz?

        def vn: () -> Vn?

        def za: () -> Za?

        def zm: () -> Zm?

        def zw: () -> Zw?
      end

      def active_from: () -> Integer

      def country: () -> String

      def country_options: () -> CountryOptions

      def created: () -> Integer

      def expires_at: () -> Integer?

      def id: () -> String

      def livemode: () -> bool

      def object: () -> String

      def status: () -> String

      def self.create: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Tax::Registration

      def self.list: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::Tax::Registration]

      def self.update: (String id, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Tax::Registration
    end
  end
end
