module Stripe
  module Tax
    class TransactionLineItem < APIResource
      class Reversal < ::Stripe::StripeObject
        def original_line_item: () -> String
      end

      def amount: () -> Integer

      def amount_tax: () -> Integer

      def id: () -> String

      def livemode: () -> bool

      def metadata: () -> ::Stripe::StripeObject?

      def object: () -> String

      def product: () -> String?

      def quantity: () -> Integer

      def reference: () -> String

      def reversal: () -> Reversal?

      def tax_behavior: () -> String

      def tax_code: () -> String

      def type: () -> String
    end
  end
end
