D = Steep::Diagnostic

target :test do
  check "."
  signature '.'

  repo_path "../../../"
  library "sentry-ruby"
  library "rack", 'uri', 'cgi'

  configure_code_diagnostics(D::Ruby.all_error)
end
