module ActionDispatch
  class RequestId
    X_REQUEST_ID: ::String

    def initialize: (Rack::_Application app) -> void

    def call: (Rack::env env) -> Rack::response

    private

    def make_request_id: (String? request_id) -> String

    def internal_request_id: () -> String
  end
end
