D = Steep::Diagnostic

target :test do
  check "."

  repo_path "../../../"
  library "sidekiq:6.3"
  library "redis:4.2"
  library "logger"
  library "monitor"
  library "connection_pool"
  library "timeout"
  signature "."

  configure_code_diagnostics(D::Ruby.all_error)
end
