root = File.expand_path("../..")
src = File.expand_path("_src")

gems = {
  'aws-sdk-s3' => {
    api_path: "#{src}/apis/s3/2006-03-01/api-2.json",
    rbs_path: "#{root}/gems/aws-sdk-s3/1/2006-03-01_api-2.rbs",
  },
  'aws-sdk-sqs' => {
    api_path: "#{src}/apis/sqs/2012-11-05/api-2.json",
    rbs_path: "#{root}/gems/aws-sdk-sqs/1/2012-11-05_api-2.rbs",
  }
}

gems.each do |gem, config|
  config => { api_path:, rbs_path: }

  file rbs_path => ['aws_client_types_generator.rb'] do
    mkdir_p File.dirname(rbs_path)
    ruby "aws_client_types_generator.rb #{api_path} > #{rbs_path}"
  end  

  task gem => rbs_path
end

task :aws => gems.keys
