#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'
set -v

RBS_DIR=$(cd $(dirname $0)/..; pwd)
REPO_DIR=$(cd $(dirname $0)/../../..; pwd)
GEM=delayed_job:4.1

bundle exec rbs --repo $REPO_DIR \
  -r activesupport -r pathname -r logger -r mutex_m -r time -r monitor -r date -r singleton \
  -r $GEM validate --silent

cd ${RBS_DIR}/_test
bundle exec steep check

$(git rev-parse --show-toplevel)/bin/check-untyped-call.rb
