module Stripe
  module FinancialConnections
    class AccountOwner < StripeObject
      def email: () -> String?

      def id: () -> String

      def name: () -> String

      def object: () -> String

      def ownership: () -> String

      def phone: () -> String?

      def raw_address: () -> String?

      def refreshed_at: () -> Integer?
    end
  end
end
