module Stripe
  module FinancialConnections
    class AccountOwnership < StripeObject
      def created: () -> Integer

      def id: () -> String

      def object: () -> String

      def owners: () -> ::Stripe::ListObject[::Stripe::FinancialConnections::AccountOwner]
    end
  end
end
