module Stripe
  module Terminal
    class OnboardingLinkService < StripeService
      def create: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Terminal::OnboardingLink
    end
  end
end
