module Stripe
  module Terminal
    class ReaderService < StripeService
      def cancel_action: (String reader, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Terminal::Reader

      def collect_inputs: (String reader, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Terminal::Reader

      def collect_payment_method: (String reader, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Terminal::Reader

      def confirm_payment_intent: (String reader, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Terminal::Reader

      def create: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Terminal::Reader

      def delete: (String reader, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Terminal::Reader

      def list: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::Terminal::Reader]

      def process_payment_intent: (String reader, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Terminal::Reader

      def process_setup_intent: (String reader, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Terminal::Reader

      def refund_payment: (String reader, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Terminal::Reader

      def retrieve: (String reader, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Terminal::Reader

      def set_reader_display: (String reader, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Terminal::Reader

      def update: (String reader, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Terminal::Reader
    end
  end
end
