module Roo
  TEMP_PREFIX: "roo_"

  CLASS_FOR_EXTENSION: { ods: singleton(OpenOffice), xlsx: singleton(Excelx), xlsm: singleton(Excelx), csv: singleton(CSV) }

  def self.const_missing: (untyped const_name) -> untyped
end
