#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

cd ${RBS_DIR}/_test

env BUNDLE_GEMFILE="${ROOT_GEMFILE}" bundle exec rbs collection install
env BUNDLE_GEMFILE="${ROOT_GEMFILE}" bundle exec rbs validate --silent
env BUNDLE_GEMFILE="${ROOT_GEMFILE}" bundle exec steep check --with-expectations
