#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

bundle exec rbs --repo $REPO_ROOT -r forwardable -r retryable:3.0 validate --silent

cd ${RBS_DIR}/_test
bundle exec steep check --with-expectations

$(git rev-parse --show-toplevel)/bin/check-untyped-call.rb
