module Stripe
  module V2
    class CoreService < StripeService
      attr_reader accounts: ::Stripe::V2::Core::AccountService

      attr_reader account_links: ::Stripe::V2::Core::AccountLinkService

      attr_reader account_tokens: ::Stripe::V2::Core::AccountTokenService

      attr_reader events: ::Stripe::V2::Core::EventService

      attr_reader event_destinations: ::Stripe::V2::Core::EventDestinationService
    end
  end
end
