module Zip
  class DecryptedIo
    CHUNK_SIZE: Integer

    def initialize: (IO io, Decrypter decrypter, Integer compressed_size) -> void

    def read: (?Integer? length, ?String outbuf) -> String?
  end
end
