module Roo
  class Excelx
    class Cell
      @type: untyped

      @formula: untyped

      @base_date: untyped

      @excelx_type: untyped

      @excelx_value: untyped

      @style: untyped

      @value: untyped

      @coordinate: untyped

      attr_reader formula: untyped

      attr_reader value: untyped

      attr_reader excelx_type: untyped

      attr_reader excelx_value: untyped

      attr_reader style: untyped

      attr_reader hyperlink: untyped

      attr_reader coordinate: untyped

      attr_writer value: untyped

      # DEPRECATED: Please use Cell.create_cell instead.
      def initialize: (untyped value, untyped type, untyped formula, untyped excelx_type, untyped excelx_value, untyped style, untyped hyperlink, untyped base_date, untyped coordinate) -> void

      def type: () -> untyped

      def self.create_cell: (untyped type, *untyped values) -> untyped

      def self.cell_class: (untyped type) -> untyped

      # Deprecated: use Roo::Excelx::Coordinate instead.
      class Coordinate
        @row: untyped

        @column: untyped

        attr_accessor row: untyped

        attr_accessor column: untyped

        def initialize: (untyped row, untyped column) -> void
      end

      private

      def type_cast_value: (untyped value) -> untyped

      def create_date: (untyped date) -> untyped

      def create_datetime: (untyped date) -> untyped

      def round_datetime: (untyped datetime_string) -> untyped
    end
  end
end
