module Roo
  class Excelx
    class Comments < Excelx::Extractor
      @comments: Hash[Coordinate, String]

      def comments: () -> Hash[Coordinate, String]

      private

      def extract_comments: () -> Hash[Coordinate, String]
    end
  end
end
