module Roo
  class Excelx
    class Comments < Excelx::Extractor
      @comments: Hash[Coordinate, string]

      def comments: () -> Hash[Coordinate, string]

      private

      def extract_comments: () -> Hash[Coordinate, string]
    end
  end
end
