module Roo
  class Excelx
    class Coordinate < ::Array[int | String]
      def initialize: (int | String row, int | String column) -> void

      def row: () -> (int | String)

      def column: () -> (int | String)
    end
  end
end
