module Roo
  class Excelx
    class Coordinate < ::Array[int | string]
      def initialize: (int | string row, int | string column) -> void

      def row: () -> (int | string)

      def column: () -> (int | string)
    end
  end
end
