module Roo
  class Excelx
    class Extractor
      @path: String

      @options: untyped

      include Roo::Helpers::WeakInstanceCache

      COMMON_STRINGS: { t: "t", r: "r", s: "s", ref: "ref", html_tag_open: "<html>", html_tag_closed: "</html>" }

      def initialize: (String path, ?Hash[Symbol, untyped] options) -> void

      private

      def doc: () -> Nokogiri::XML::Document

      def doc_exists?: () -> bool
    end
  end
end
