module Roo
  class Excelx
    class Images < Excelx::Extractor
      @images: Hash[string, string]

      # Returns: Hash { id1: extracted_file_name1 },
      # Example: { "rId1"=>"roo_media_image1.png",
      #            "rId2"=>"roo_media_image2.png",
      #            "rId3"=>"roo_media_image3.png" }
      def list: () -> Hash[string, string]

      private

      def extract_images_names: () -> Hash[string, string]
    end
  end
end
