module Roo
  class Excelx
    class Relationships < Excelx::Extractor
      @relationships: untyped

      def []: (untyped index) -> untyped

      def to_a: () -> untyped

      def include_type?: (untyped type) -> untyped

      private

      def extract_relationships: () -> (::Hash[untyped, untyped] | untyped)
    end
  end
end
