module Roo
  class Excelx
    class Relationships < Excelx::Extractor
      @relationships: Hash[string, Nokogiri::XML::Node]

      def []: (string index) -> Nokogiri::XML::Node

      def to_a: () -> Hash[string, Nokogiri::XML::Node]

      def include_type?: (string type) -> bool

      private

      def extract_relationships: () -> Hash[string, Nokogiri::XML::Node]
    end
  end
end
