module Roo
  class Excelx
    # Public:  Shared class for allowing sheets to share data. This should
    #          reduce memory usage and reduce the number of objects being passed
    #          to various inititializers.
    class Shared
      @dir: string

      @comments_files: Array[string]

      @sheet_files: Array[string]

      @rels_files: Array[string]

      @options: { disable_html_wrapper: bool }

      @image_rels: Array[string]

      @image_files: Array[string]

      @styles: Styles

      @shared_strings: SharedStrings

      @workbook: Workbook

      attr_accessor comments_files: Array[string]

      attr_accessor sheet_files: Array[string]

      attr_accessor rels_files: Array[string]

      attr_accessor image_rels: Array[string]

      attr_accessor image_files: Array[string]

      def initialize: (string dir, { disable_html_wrapper: bool } options) -> void

      def styles: () -> Styles

      def shared_strings: () -> SharedStrings

      def workbook: () -> Workbook

      def base_date: () -> Date

      def base_timestamp: () -> int
    end
  end
end
