module Roo
  class Excelx
    class Styles < Excelx::Extractor
      @definitions: Array[Font | nil]

      @num_fmt_ids: Array[string]

      @num_fmts: Hash[string, string]

      @fonts: Array[Font]

      # convert internal excelx attribute to a format
      def style_format: (int style) -> (string | nil)

      def definitions: () -> Array[Font | nil]

      private

      def num_fmt_ids: () -> Array[string]

      def num_fmts: () -> Hash[string, string]

      def fonts: () -> Array[Font]

      def extract_definitions: () -> Array[Font | nil]

      def extract_fonts: () -> Array[Font]

      def extract_num_fmt_ids: () -> Array[string]

      def extract_num_fmts: () -> Hash[string, string]
    end
  end
end
