module Roo
  class Excelx
    class Styles < Excelx::Extractor
      @definitions: untyped

      @num_fmt_ids: untyped

      @num_fmts: untyped

      @fonts: untyped

      # convert internal excelx attribute to a format
      def style_format: (untyped style) -> untyped

      def definitions: () -> untyped

      private

      def num_fmt_ids: () -> untyped

      def num_fmts: () -> untyped

      def fonts: () -> untyped

      def extract_definitions: () -> untyped

      def extract_fonts: () -> untyped

      def extract_num_fmt_ids: () -> untyped

      def extract_num_fmts: () -> untyped
    end
  end
end
