module Roo
  class Excelx
    class Styles < Excelx::Extractor
      @definitions: Array[Font | nil]

      @num_fmt_ids: Array[String]

      @num_fmts: Hash[String, String]

      @fonts: Array[Font]

      # convert internal excelx attribute to a format
      def style_format: (Integer style) -> (String | nil)

      def definitions: () -> Array[Font | nil]

      private

      def num_fmt_ids: () -> Array[String]

      def num_fmts: () -> Hash[String, String]

      def fonts: () -> Array[Font]

      def extract_definitions: () -> Array[Font | nil]

      def extract_fonts: () -> Array[Font]

      def extract_num_fmt_ids: () -> Array[String]

      def extract_num_fmts: () -> Hash[String, String]
    end
  end
end
