module Roo
  class Excelx
    class Workbook < Excelx::Extractor
      @base_timestamp: int

      @base_date: Date

      class Label
        @name: String

        @sheet: String

        @row: int

        @col: int

        attr_reader sheet: String

        attr_reader row: int

        attr_reader col: int

        attr_reader name: String

        def initialize: (String name, String sheet, String row, String col) -> void

        def key: () -> [int, int]
      end

      def initialize: (String path) -> void

      def sheets: () -> ::Nokogiri::XML::NodeSet

      # aka labels
      def defined_names: () -> Hash[String, Label]

      def base_timestamp: () -> int

      def base_date: () -> Date
    end
  end
end
