module Roo
  class Excelx
    class Workbook < Excelx::Extractor
      @base_timestamp: int

      @base_date: Date

      class Label
        @name: string

        @sheet: string

        @row: int

        @col: int

        attr_reader sheet: string

        attr_reader row: int

        attr_reader col: int

        attr_reader name: string

        def initialize: (string name, string sheet, string row, string col) -> void

        def key: () -> [int, int]
      end

      def initialize: (string path) -> void

      def sheets: () -> ::Nokogiri::XML::NodeSet

      # aka labels
      def defined_names: () -> Hash[string, Label]

      def base_timestamp: () -> int

      def base_date: () -> Date
    end
  end
end
