module LaunchDarkly
  #
  # Internal implementation classes. Everything in this module should be considered unsupported
  # and subject to change.
  #
  # @since 5.5.0
  # @private
  #
  module Impl
  end
end
