module LaunchDarkly
  # @private
  module Util
    #
    # Append the payload filter key query parameter to the provided URI.
    #
    # @param uri [String]
    # @param config [Config]
    # @return [String]
    #
    def self.add_payload_filter_key: (untyped uri, untyped config) -> untyped

    def self.new_http_client: (untyped uri_s, untyped config) -> untyped

    def self.log_exception: (untyped logger, untyped message, untyped exc) -> untyped

    def self.http_error_recoverable?: (untyped status) -> (untyped | true)

    def self.http_error_message: (untyped status, untyped context, untyped recoverable_message) -> ::String
  end
end
