# Classes
module ZenginCode
  class Bank
    def self.[]: (String code) -> Bank?
    def self.all: -> Hash[String, Bank]

    attr_reader code: String
    attr_reader name: String
    attr_reader kana: String
    attr_reader hira: String
    attr_reader roma: String
    attr_reader branches: Hash[String, Branch]
  end

  class Branch
    attr_reader bank: Bank
    attr_reader code: String
    attr_reader name: String
    attr_reader kana: String
    attr_reader hira: String
    attr_reader roma: String
  end

  def self.version: () -> String
end
