D = Steep::Diagnostic

target :test do
  check "."
  signature "."

  repo_path "../../../"
  library "shoryuken:6.0"
  library "aws-sdk-sqs:1"
  library "aws-sdk-core:3"

  library "logger"
  library "forwardable"

  configure_code_diagnostics(D::Ruby.all_error)
end
