#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'
set -v

RBS_DIR=$(cd $(dirname $0)/..; pwd)
REPO_DIR=$(cd $(dirname $0)/../../..; pwd)
GEM=redis:4.2.0

bundle exec rbs --repo $REPO_DIR -r $GEM validate --silent

cd ${RBS_DIR}/_test
bundle exec steep check

$(git rev-parse --show-toplevel)/bin/check-untyped-call.rb
