module Google
  module Protobuf
    class Any < Google::Protobuf::AbstractMessage
      def self.pack: (AbstractMessage msg, ?String type_url_prefix) -> instance

      public

      def is: (Class klass) -> bool

      def pack: (AbstractMessage msg, ?String type_url_prefix) -> void

      def type_name: () -> String?

      def unpack: (Class klass) -> AbstractMessage?
    end
  end
end
