module Google
  module Protobuf
    class ListValue < Google::Protobuf::AbstractMessage
      include Enumerable[untyped]

      def self.from_a: (Array[untyped] arr) -> instance

      public

      def <<: (untyped value) -> self

      def []: (Integer index) -> untyped?

      def []=: (Integer index, untyped value) -> void

      def each: () { (untyped) -> void } -> untyped

      def length: () -> Integer

      def to_a: () -> Array[untyped]
    end
  end
end
