module Google
  module Protobuf
    module NullValue
      def self.descriptor: () -> EnumDescriptor

      def self.lookup: (Integer) -> nil

      def self.resolve: (Symbol) -> void

      NULL_VALUE: Integer
    end
  end
end
