module Google
  module Protobuf
    class Timestamp < Google::Protobuf::AbstractMessage
      def self.from_time: (Time time) -> instance

      public

      def from_time: (Time time) -> self

      def to_f: () -> Float

      def to_i: () -> Integer

      def to_time: () -> Time
    end
  end
end
