module Google
  module Protobuf
    class Value < Google::Protobuf::AbstractMessage
      def self.from_ruby: (untyped value) -> instance

      public

      def from_ruby: (untyped value) -> self

      def to_ruby: (?untyped recursive) -> untyped
    end
  end
end
