module Stripe
  module Treasury
    class CreditReversal < APIResource
      class StatusTransitions < ::Stripe::StripeObject
        def posted_at: () -> Integer?
      end

      def amount: () -> Integer

      def created: () -> Integer

      def currency: () -> String

      def financial_account: () -> String

      def hosted_regulatory_receipt_url: () -> String?

      def id: () -> String

      def livemode: () -> bool

      def metadata: () -> ::Stripe::StripeObject

      def network: () -> String

      def object: () -> String

      def received_credit: () -> String

      def status: () -> String

      def status_transitions: () -> StatusTransitions

      def transaction: () -> (String | ::Stripe::Treasury::Transaction)?

      def self.create: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Treasury::CreditReversal

      def self.list: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::Treasury::CreditReversal]
    end
  end
end
