module Stripe
  module Treasury
    class FinancialAccountFeatures < APIResource
      class CardIssuing < ::Stripe::StripeObject
        class StatusDetail < ::Stripe::StripeObject
          def code: () -> String

          def resolution: () -> String?

          def restriction: () -> String?
        end

        def requested: () -> bool

        def status: () -> String

        def status_details: () -> ::Array[StatusDetail]
      end

      class DepositInsurance < ::Stripe::StripeObject
        class StatusDetail < ::Stripe::StripeObject
          def code: () -> String

          def resolution: () -> String?

          def restriction: () -> String?
        end

        def requested: () -> bool

        def status: () -> String

        def status_details: () -> ::Array[StatusDetail]
      end

      class FinancialAddresses < ::Stripe::StripeObject
        class Aba < ::Stripe::StripeObject
          class StatusDetail < ::Stripe::StripeObject
            def code: () -> String

            def resolution: () -> String?

            def restriction: () -> String?
          end

          def requested: () -> bool

          def status: () -> String

          def status_details: () -> ::Array[StatusDetail]
        end

        def aba: () -> Aba?
      end

      class InboundTransfers < ::Stripe::StripeObject
        class Ach < ::Stripe::StripeObject
          class StatusDetail < ::Stripe::StripeObject
            def code: () -> String

            def resolution: () -> String?

            def restriction: () -> String?
          end

          def requested: () -> bool

          def status: () -> String

          def status_details: () -> ::Array[StatusDetail]
        end

        def ach: () -> Ach?
      end

      class IntraStripeFlows < ::Stripe::StripeObject
        class StatusDetail < ::Stripe::StripeObject
          def code: () -> String

          def resolution: () -> String?

          def restriction: () -> String?
        end

        def requested: () -> bool

        def status: () -> String

        def status_details: () -> ::Array[StatusDetail]
      end

      class OutboundPayments < ::Stripe::StripeObject
        class Ach < ::Stripe::StripeObject
          class StatusDetail < ::Stripe::StripeObject
            def code: () -> String

            def resolution: () -> String?

            def restriction: () -> String?
          end

          def requested: () -> bool

          def status: () -> String

          def status_details: () -> ::Array[StatusDetail]
        end

        class UsDomesticWire < ::Stripe::StripeObject
          class StatusDetail < ::Stripe::StripeObject
            def code: () -> String

            def resolution: () -> String?

            def restriction: () -> String?
          end

          def requested: () -> bool

          def status: () -> String

          def status_details: () -> ::Array[StatusDetail]
        end

        def ach: () -> Ach?

        def us_domestic_wire: () -> UsDomesticWire?
      end

      class OutboundTransfers < ::Stripe::StripeObject
        class Ach < ::Stripe::StripeObject
          class StatusDetail < ::Stripe::StripeObject
            def code: () -> String

            def resolution: () -> String?

            def restriction: () -> String?
          end

          def requested: () -> bool

          def status: () -> String

          def status_details: () -> ::Array[StatusDetail]
        end

        class UsDomesticWire < ::Stripe::StripeObject
          class StatusDetail < ::Stripe::StripeObject
            def code: () -> String

            def resolution: () -> String?

            def restriction: () -> String?
          end

          def requested: () -> bool

          def status: () -> String

          def status_details: () -> ::Array[StatusDetail]
        end

        def ach: () -> Ach?

        def us_domestic_wire: () -> UsDomesticWire?
      end

      def card_issuing: () -> CardIssuing?

      def deposit_insurance: () -> DepositInsurance?

      def financial_addresses: () -> FinancialAddresses?

      def inbound_transfers: () -> InboundTransfers?

      def intra_stripe_flows: () -> IntraStripeFlows?

      def object: () -> String

      def outbound_payments: () -> OutboundPayments?

      def outbound_transfers: () -> OutboundTransfers?
    end
  end
end
