module Stripe
  module Treasury
    class Transaction < APIResource
      class BalanceImpact < ::Stripe::StripeObject
        def cash: () -> Integer

        def inbound_pending: () -> Integer

        def outbound_pending: () -> Integer
      end

      class FlowDetails < ::Stripe::StripeObject
        def credit_reversal: () -> ::Stripe::Treasury::CreditReversal?

        def debit_reversal: () -> ::Stripe::Treasury::DebitReversal?

        def inbound_transfer: () -> ::Stripe::Treasury::InboundTransfer?

        def issuing_authorization: () -> ::Stripe::Issuing::Authorization?

        def outbound_payment: () -> ::Stripe::Treasury::OutboundPayment?

        def outbound_transfer: () -> ::Stripe::Treasury::OutboundTransfer?

        def received_credit: () -> ::Stripe::Treasury::ReceivedCredit?

        def received_debit: () -> ::Stripe::Treasury::ReceivedDebit?

        def type: () -> String
      end

      class StatusTransitions < ::Stripe::StripeObject
        def posted_at: () -> Integer?

        def void_at: () -> Integer?
      end

      def amount: () -> Integer

      def balance_impact: () -> BalanceImpact

      def created: () -> Integer

      def currency: () -> String

      def description: () -> String

      def entries: () -> ::Stripe::ListObject[::Stripe::Treasury::TransactionEntry]?

      def financial_account: () -> String

      def flow: () -> String?

      def flow_details: () -> FlowDetails?

      def flow_type: () -> String

      def id: () -> String

      def livemode: () -> bool

      def object: () -> String

      def status: () -> String

      def status_transitions: () -> StatusTransitions

      def self.list: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::Treasury::Transaction]
    end
  end
end
