module Stripe
  class AccountCapabilityService < StripeService
    def list: (String account, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::Capability]

    def retrieve: (String account, String capability, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Capability

    def update: (String account, String capability, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Capability
  end
end
