module Stripe
  class AccountPersonService < StripeService
    def create: (String account, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Person

    def delete: (String account, String person, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Person

    def list: (String account, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::Person]

    def retrieve: (String account, String person, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Person

    def update: (String account, String person, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Person
  end
end
