module Stripe
  class ApplePayDomainService < StripeService
    def create: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ApplePayDomain

    def delete: (String domain, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ApplePayDomain

    def list: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::ApplePayDomain]

    def retrieve: (String domain, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ApplePayDomain
  end
end
