module Stripe
  class ApplicationFeeRefundService < StripeService
    def create: (String id, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ApplicationFeeRefund

    def list: (String id, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::ApplicationFeeRefund]

    def retrieve: (String fee, String id, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ApplicationFeeRefund

    def update: (String fee, String id, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ApplicationFeeRefund
  end
end
