module Stripe
  class ApplicationFeeService < StripeService
    attr_reader refunds: ::Stripe::ApplicationFeeRefundService

    def list: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::ApplicationFee]

    def retrieve: (String id, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ApplicationFee
  end
end
