module Stripe
  class BalanceTransactionService < StripeService
    def list: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::BalanceTransaction]

    def retrieve: (String id, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::BalanceTransaction
  end
end
