module Stripe
  class BalanceSettingsService < StripeService
    def retrieve: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::BalanceSettings

    def update: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::BalanceSettings
  end
end
