module Stripe
  class BillingPortalService < StripeService
    attr_reader configurations: ::Stripe::BillingPortal::ConfigurationService

    attr_reader sessions: ::Stripe::BillingPortal::SessionService
  end
end
