module Stripe
  class BillingService < StripeService
    attr_reader alerts: ::Stripe::Billing::AlertService

    attr_reader credit_balance_summary: ::Stripe::Billing::CreditBalanceSummaryService

    attr_reader credit_balance_transactions: ::Stripe::Billing::CreditBalanceTransactionService

    attr_reader credit_grants: ::Stripe::Billing::CreditGrantService

    attr_reader feedback_options: ::Stripe::Billing::FeedbackOptionService

    attr_reader meters: ::Stripe::Billing::MeterService

    attr_reader meter_events: ::Stripe::Billing::MeterEventService

    attr_reader meter_event_adjustments: ::Stripe::Billing::MeterEventAdjustmentService
  end
end
