module Stripe
  class ChargeService < StripeService
    def capture: (String charge, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Charge

    def create: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Charge

    def list: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::Charge]

    def retrieve: (String charge, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Charge

    def search: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::SearchResultObject[::Stripe::Charge]

    def update: (String charge, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Charge
  end
end
