module Stripe
  class ClimateService < StripeService
    attr_reader orders: ::Stripe::Climate::OrderService

    attr_reader products: ::Stripe::Climate::ProductService

    attr_reader suppliers: ::Stripe::Climate::SupplierService
  end
end
