module Stripe
  class CountrySpecService < StripeService
    def list: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::CountrySpec]

    def retrieve: (String country, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::CountrySpec
  end
end
