module Stripe
  class CouponService < StripeService
    def create: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Coupon

    def delete: (String coupon, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Coupon

    def list: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::Coupon]

    def retrieve: (String coupon, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Coupon

    def update: (String coupon, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Coupon
  end
end
