module Stripe
  class CreditNoteLineItemService < StripeService
    def list: (String credit_note, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::CreditNoteLineItem]
  end
end
