module Stripe
  class CreditNoteService < StripeService
    attr_reader line_items: ::Stripe::CreditNoteLineItemService

    attr_reader preview_lines: ::Stripe::CreditNotePreviewLinesService

    def create: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::CreditNote

    def list: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::CreditNote]

    def preview: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::CreditNote

    def retrieve: (String id, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::CreditNote

    def update: (String id, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::CreditNote

    def void_credit_note: (String id, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::CreditNote
  end
end
