module Stripe
  class CustomerBalanceTransactionService < StripeService
    def create: (String customer, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::CustomerBalanceTransaction

    def list: (String customer, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::CustomerBalanceTransaction]

    def retrieve: (String customer, String transaction, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::CustomerBalanceTransaction

    def update: (String customer, String transaction, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::CustomerBalanceTransaction
  end
end
