module Stripe
  class CustomerTaxIdService < StripeService
    def create: (String customer, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::TaxId

    def delete: (String customer, String id, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::TaxId

    def list: (String customer, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::TaxId]

    def retrieve: (String customer, String id, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::TaxId
  end
end
