module Stripe
  class CustomerPaymentMethodService < StripeService
    def list: (String customer, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::PaymentMethod]

    def retrieve: (String customer, String payment_method, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::PaymentMethod
  end
end
