module Stripe
  class CustomerCashBalanceTransactionService < StripeService
    def list: (String customer, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::CustomerCashBalanceTransaction]

    def retrieve: (String customer, String transaction, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::CustomerCashBalanceTransaction
  end
end
