module Stripe
  class CustomerPaymentSourceService < StripeService
    def create: (String customer, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> (::Stripe::Account | ::Stripe::BankAccount | ::Stripe::Card | ::Stripe::Source)

    def delete: (String customer, String id, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> (::Stripe::Account | ::Stripe::BankAccount | ::Stripe::Card | ::Stripe::Source)

    def list: (String customer, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::BankAccount | ::Stripe::Card | ::Stripe::Source]

    def retrieve: (String customer, String id, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> (::Stripe::Account | ::Stripe::BankAccount | ::Stripe::Card | ::Stripe::Source)

    def update: (String customer, String id, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> (::Stripe::Account | ::Stripe::BankAccount | ::Stripe::Card | ::Stripe::Source)

    def verify: (String customer, String id, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::BankAccount
  end
end
