module Stripe
  class DisputeService < StripeService
    def close: (String dispute, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Dispute

    def list: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::Dispute]

    def retrieve: (String dispute, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Dispute

    def update: (String dispute, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Dispute
  end
end
