module Stripe
  class EntitlementsService < StripeService
    attr_reader active_entitlements: ::Stripe::Entitlements::ActiveEntitlementService

    attr_reader features: ::Stripe::Entitlements::FeatureService
  end
end
