module Stripe
  class EphemeralKeyService < StripeService
    def create: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::EphemeralKey

    def delete: (String key, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::EphemeralKey
  end
end
