module Stripe
  class ExchangeRateService < StripeService
    def list: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::ExchangeRate]

    def retrieve: (String rate_id, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ExchangeRate
  end
end
