module Stripe
  class FileService < StripeService
    def create: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::File

    def list: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::File]

    def retrieve: (String file, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::File
  end
end
