module Stripe
  class FileLinkService < StripeService
    def create: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::FileLink

    def list: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::FileLink]

    def retrieve: (String link, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::FileLink

    def update: (String link, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::FileLink
  end
end
