module Stripe
  class FinancialConnectionsService < StripeService
    attr_reader accounts: ::Stripe::FinancialConnections::AccountService

    attr_reader sessions: ::Stripe::FinancialConnections::SessionService

    attr_reader transactions: ::Stripe::FinancialConnections::TransactionService
  end
end
