module Stripe
  class IdentityService < StripeService
    attr_reader verification_reports: ::Stripe::Identity::VerificationReportService

    attr_reader verification_sessions: ::Stripe::Identity::VerificationSessionService
  end
end
