module Stripe
  class InvoiceRenderingTemplateService < StripeService
    def archive: (String template, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::InvoiceRenderingTemplate

    def list: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::InvoiceRenderingTemplate]

    def retrieve: (String template, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::InvoiceRenderingTemplate

    def unarchive: (String template, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::InvoiceRenderingTemplate
  end
end
