module Stripe
  class InvoiceItemService < StripeService
    def create: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::InvoiceItem

    def delete: (String invoiceitem, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::InvoiceItem

    def list: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::InvoiceItem]

    def retrieve: (String invoiceitem, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::InvoiceItem

    def update: (String invoiceitem, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::InvoiceItem
  end
end
