module Stripe
  class InvoiceService < StripeService
    attr_reader line_items: ::Stripe::InvoiceLineItemService

    def add_lines: (String invoice, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Invoice

    def attach_payment: (String invoice, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Invoice

    def create: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Invoice

    def create_preview: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Invoice

    def delete: (String invoice, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Invoice

    def finalize_invoice: (String invoice, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Invoice

    def list: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::Invoice]

    def mark_uncollectible: (String invoice, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Invoice

    def pay: (String invoice, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Invoice

    def remove_lines: (String invoice, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Invoice

    def retrieve: (String invoice, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Invoice

    def search: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::SearchResultObject[::Stripe::Invoice]

    def send_invoice: (String invoice, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Invoice

    def update: (String invoice, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Invoice

    def update_lines: (String invoice, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Invoice

    def void_invoice: (String invoice, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Invoice
  end
end
