module Stripe
  class InvoiceLineItemService < StripeService
    def list: (String invoice, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::InvoiceLineItem]

    def update: (String invoice, String line_item_id, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::InvoiceLineItem
  end
end
