module Stripe
  class IssuingService < StripeService
    attr_reader authorizations: ::Stripe::Issuing::AuthorizationService

    attr_reader cards: ::Stripe::Issuing::CardService

    attr_reader cardholders: ::Stripe::Issuing::CardholderService

    attr_reader disputes: ::Stripe::Issuing::DisputeService

    attr_reader personalization_designs: ::Stripe::Issuing::PersonalizationDesignService

    attr_reader physical_bundles: ::Stripe::Issuing::PhysicalBundleService

    attr_reader tokens: ::Stripe::Issuing::TokenService

    attr_reader transactions: ::Stripe::Issuing::TransactionService
  end
end
