module Stripe
  class PaymentLinkLineItemService < StripeService
    def list: (String payment_link, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::LineItem]
  end
end
