module Stripe
  class PaymentLinkService < StripeService
    attr_reader line_items: ::Stripe::PaymentLinkLineItemService

    def create: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::PaymentLink

    def list: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::PaymentLink]

    def retrieve: (String payment_link, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::PaymentLink

    def update: (String payment_link, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::PaymentLink
  end
end
