module Stripe
  class PaymentIntentAmountDetailsLineItemService < StripeService
    def list: (String intent, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::PaymentIntentAmountDetailsLineItem]
  end
end
