module Stripe
  class PaymentRecordService < StripeService
    def list: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::PaymentRecord]

    def report_payment: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::PaymentRecord

    def report_payment_attempt: (String id, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::PaymentRecord

    def report_payment_attempt_canceled: (String id, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::PaymentRecord

    def report_payment_attempt_failed: (String id, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::PaymentRecord

    def report_payment_attempt_guaranteed: (String id, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::PaymentRecord

    def report_payment_attempt_informational: (String id, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::PaymentRecord

    def report_refund: (String id, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::PaymentRecord

    def retrieve: (String id, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::PaymentRecord
  end
end
