module Stripe
  class PayoutService < StripeService
    def cancel: (String payout, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Payout

    def create: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Payout

    def list: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::Payout]

    def retrieve: (String payout, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Payout

    def reverse: (String payout, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Payout

    def update: (String payout, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Payout
  end
end
