module Stripe
  class PriceService < StripeService
    def create: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Price

    def list: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::Price]

    def retrieve: (String price, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Price

    def search: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::SearchResultObject[::Stripe::Price]

    def update: (String price, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Price
  end
end
