module Stripe
  class ProductFeatureService < StripeService
    def create: (String product, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ProductFeature

    def delete: (String product, String id, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ProductFeature

    def list: (String product, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::ProductFeature]

    def retrieve: (String product, String id, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ProductFeature
  end
end
