module Stripe
  class QuoteComputedUpfrontLineItemsService < StripeService
    def list: (String quote, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::LineItem]
  end
end
