module Stripe
  class RadarService < StripeService
    attr_reader early_fraud_warnings: ::Stripe::Radar::EarlyFraudWarningService

    attr_reader payment_evaluations: ::Stripe::Radar::PaymentEvaluationService

    attr_reader value_lists: ::Stripe::Radar::ValueListService

    attr_reader value_list_items: ::Stripe::Radar::ValueListItemService
  end
end
