module Stripe
  class RefundService < StripeService
    def cancel: (String refund, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Refund

    def create: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Refund

    def list: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::Refund]

    def retrieve: (String refund, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Refund

    def update: (String refund, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Refund
  end
end
