module Stripe
  class ReportingService < StripeService
    attr_reader report_runs: ::Stripe::Reporting::ReportRunService

    attr_reader report_types: ::Stripe::Reporting::ReportTypeService
  end
end
