module Stripe
  class ReviewService < StripeService
    def approve: (String review, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Review

    def list: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::Review]

    def retrieve: (String review, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Review
  end
end
