module Stripe
  class ShippingRateService < StripeService
    def create: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ShippingRate

    def list: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::ShippingRate]

    def retrieve: (String shipping_rate_token, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ShippingRate

    def update: (String shipping_rate_token, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ShippingRate
  end
end
