module Stripe
  class SourceService < StripeService
    attr_reader transactions: ::Stripe::SourceTransactionService

    def create: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Source

    def detach: (String customer, String id, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> (::Stripe::Account | ::Stripe::BankAccount | ::Stripe::Card | ::Stripe::Source)

    def retrieve: (String source, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Source

    def update: (String source, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Source

    def verify: (String source, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Source
  end
end
