module Stripe
  class SourceTransactionService < StripeService
    def list: (String source, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::SourceTransaction]
  end
end
