module Stripe
  class SubscriptionScheduleService < StripeService
    def cancel: (String schedule, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::SubscriptionSchedule

    def create: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::SubscriptionSchedule

    def list: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::SubscriptionSchedule]

    def release: (String schedule, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::SubscriptionSchedule

    def retrieve: (String schedule, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::SubscriptionSchedule

    def update: (String schedule, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::SubscriptionSchedule
  end
end
