module Stripe
  class SubscriptionService < StripeService
    def cancel: (String subscription_exposed_id, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Subscription

    def create: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Subscription

    def delete_discount: (String subscription_exposed_id, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Discount

    def list: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::Subscription]

    def migrate: (String subscription, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Subscription

    def pause: (String subscription, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Subscription

    def resume: (String subscription, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Subscription

    def retrieve: (String subscription_exposed_id, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Subscription

    def search: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::SearchResultObject[::Stripe::Subscription]

    def update: (String subscription_exposed_id, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Subscription
  end
end
