module Stripe
  class SubscriptionItemService < StripeService
    def create: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::SubscriptionItem

    def delete: (String item, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::SubscriptionItem

    def list: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::SubscriptionItem]

    def retrieve: (String item, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::SubscriptionItem

    def update: (String item, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::SubscriptionItem
  end
end
