module Stripe
  class TaxIdService < StripeService
    def create: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::TaxId

    def delete: (String id, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::TaxId

    def list: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::TaxId]

    def retrieve: (String id, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::TaxId
  end
end
