module Stripe
  class TaxRateService < StripeService
    def create: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::TaxRate

    def list: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::TaxRate]

    def retrieve: (String tax_rate, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::TaxRate

    def update: (String tax_rate, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::TaxRate
  end
end
