module Stripe
  class TaxService < StripeService
    attr_reader associations: ::Stripe::Tax::AssociationService

    attr_reader calculations: ::Stripe::Tax::CalculationService

    attr_reader locations: ::Stripe::Tax::LocationService

    attr_reader registrations: ::Stripe::Tax::RegistrationService

    attr_reader settings: ::Stripe::Tax::SettingsService

    attr_reader transactions: ::Stripe::Tax::TransactionService
  end
end
