module Stripe
  class TerminalService < StripeService
    attr_reader configurations: ::Stripe::Terminal::ConfigurationService

    attr_reader connection_tokens: ::Stripe::Terminal::ConnectionTokenService

    attr_reader locations: ::Stripe::Terminal::LocationService

    attr_reader onboarding_links: ::Stripe::Terminal::OnboardingLinkService

    attr_reader readers: ::Stripe::Terminal::ReaderService
  end
end
