module Stripe
  class TokenService < StripeService
    def create: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Token

    def retrieve: (String token, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Token
  end
end
