module Stripe
  class TopupService < StripeService
    def cancel: (String topup, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Topup

    def create: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Topup

    def list: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::Topup]

    def retrieve: (String topup, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Topup

    def update: (String topup, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Topup
  end
end
