module Stripe
  class TransferReversalService < StripeService
    def create: (String id, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::TransferReversal

    def list: (String id, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::TransferReversal]

    def retrieve: (String transfer, String id, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::TransferReversal

    def update: (String transfer, String id, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::TransferReversal
  end
end
