module Stripe
  class TreasuryService < StripeService
    attr_reader credit_reversals: ::Stripe::Treasury::CreditReversalService

    attr_reader debit_reversals: ::Stripe::Treasury::DebitReversalService

    attr_reader financial_accounts: ::Stripe::Treasury::FinancialAccountService

    attr_reader inbound_transfers: ::Stripe::Treasury::InboundTransferService

    attr_reader outbound_payments: ::Stripe::Treasury::OutboundPaymentService

    attr_reader outbound_transfers: ::Stripe::Treasury::OutboundTransferService

    attr_reader received_credits: ::Stripe::Treasury::ReceivedCreditService

    attr_reader received_debits: ::Stripe::Treasury::ReceivedDebitService

    attr_reader transactions: ::Stripe::Treasury::TransactionService

    attr_reader transaction_entries: ::Stripe::Treasury::TransactionEntryService
  end
end
