module Stripe
  class V2Services < StripeService
    attr_reader billing: ::Stripe::V2::BillingService

    attr_reader commerce: ::Stripe::V2::CommerceService

    attr_reader core: ::Stripe::V2::CoreService
  end
end
