module Zip
  module FileSystem
    class DirectoryIterator
      include Enumerable[String]

      def initialize: (Array[String] filenames) -> void

      def close: -> void

      def each: { (String) -> void } -> void

      def read: -> String?

      def rewind: -> self

      def seek: (Integer position) -> self

      def tell: -> Integer
    end
  end
end
