module Zip
  module FileSystem
    class FileStat
      def initialize: (FileSystem::File zip_fs_file, String entry_name) -> void

      def kind_of?: (Module type) -> bool

      def blocks: () -> nil
      def gid: () -> Integer
      def uid: () -> Integer
      def ino: () -> Integer
      def dev: () -> Integer
      def rdev: () -> Integer
      def rdev_major: () -> Integer
      def rdev_minor: () -> Integer

      def ftype: () -> String

      def nlink: () -> Integer

      def blksize: () -> nil

      def mode: () -> Integer

      def file?: () -> bool
      def directory?: () -> bool
      def pipe?: () -> false
      def chardev?: () -> false
      def symlink?: () -> false
      def socket?: () -> false
      def blockdev?: () -> false

      def readable?: () -> bool
      def readable_real?: () -> bool
      def writable?: () -> bool
      def writable_real?: () -> bool
      def executable?: () -> bool
      def executable_real?: () -> bool

      def sticky?: () -> bool
      def owned?: () -> bool
      def grpowned?: () -> bool
      def setuid?: () -> bool
      def setgid?: () -> bool
      def zero?: () -> bool

      def size: () -> Integer
      def size?: () -> Integer?

      def mtime: () -> Time
      def atime: () -> Time?
      def ctime: () -> Time?
    end
  end
end
