module Zip
  module FileSystem
    class ZipFileNameMapper
      include Enumerable[String]

      attr_accessor pwd: String

      def initialize: (Zip::File zip_file) -> void

      def find_entry: (String filename) -> Entry?

      def get_entry: (String filename) -> Entry

      def get_input_stream: [TContent] (String filename) { (IO) -> TContent } -> TContent
                          | (String filename) -> IO

      def get_output_stream: [TContent] (String filename, ?Integer? permissions) { (IO) -> TContent } -> TContent
                           | (String filename, ?Integer? permissions) -> IO

      def glob: (String pattern, *untyped flags) ?{ (String) -> void } -> Array[String]

      def read: (String filename) -> String

      def remove: (String filename) -> void

      def rename: (String filename, String new_name) ?{ () -> boolish } -> void

      def mkdir: (String filename, ?Integer permissions) -> void

      def each: () { (String) -> void } -> void

      def expand_path: (String path) -> String
    end
  end
end
