module ActiveRecord
  class Base
    include Encryption::EncryptableRecord
    extend Encryption::EncryptableRecord::ClassMethods
  end

  class AssociationRelation
    def insert: (untyped attributes, ?unique_by: untyped?, ?returning: untyped?, ?record_timestamps: bool?) -> untyped
    def insert_all: (untyped attributes, ?unique_by: untyped?, ?returning: untyped?, ?record_timestamps: bool?) -> untyped
    def insert!: (untyped attributes, ?returning: untyped?, ?record_timestamps: bool?) -> untyped
    def insert_all!: (untyped attributes, ?returning: untyped?, ?record_timestamps: bool?) -> untyped
    def upsert: (untyped attributes, ?unique_by: untyped?, ?returning: untyped?, ?record_timestamps: bool?) -> untyped
    def upsert_all: (untyped attributes, ?unique_by: untyped?, ?returning: untyped?, ?record_timestamps: bool?) -> untyped
  end

  module Associations
    class CollectionProxy
      def insert: (untyped attributes, ?unique_by: untyped?, ?returning: untyped?, ?record_timestamps: bool?) -> untyped
      def insert_all: (untyped attributes, ?unique_by: untyped?, ?returning: untyped?, ?record_timestamps: bool?) -> untyped
      def insert!: (untyped attributes, ?returning: untyped?, ?record_timestamps: bool?) -> untyped
      def insert_all!: (untyped attributes, ?returning: untyped?, ?record_timestamps: bool?) -> untyped
      def upsert: (untyped attributes, ?unique_by: untyped?, ?returning: untyped?, ?record_timestamps: bool?) -> untyped
      def upsert_all: (untyped attributes, ?unique_by: untyped?, ?returning: untyped?, ?record_timestamps: bool?) -> untyped
    end
  end

  module Inheritance
    module ClassMethods
      def primary_abstract_class: () -> void
    end
  end

  module Enum
    def enum: (**untyped options) -> void
            | ((String | Symbol) name, **untyped options) -> void
            | ((String | Symbol) name, (Hash[(Symbol | String), untyped] | Array[Symbol | String]) values, **untyped options) -> void
  end

  module RuntimeRegistry
    def sql_runtime: () -> untyped

    def sql_runtime=: (untyped runtime) -> untyped

    extend RuntimeRegistry
  end

  module QueryMethods
    class WhereChain[Relation]
      def missing: (*Symbol associations) -> Relation
    end
  end

  module Encryption
    module EncryptableRecord
      module ClassMethods
        @deterministic_encrypted_attributes: untyped

        def encrypts: (*untyped names, ?key_provider: untyped?, ?key: untyped?, ?deterministic: bool, ?support_unencrypted_data: untyped?, ?downcase: bool, ?ignore_case: bool, ?previous: untyped, **untyped context_properties) -> untyped

        def deterministic_encrypted_attributes: () -> untyped

        def source_attribute_from_preserved_attribute: (untyped attribute_name) -> untyped
      end

      def encrypted_attribute?: (untyped attribute_name) -> untyped

      def ciphertext_for: (untyped attribute_name) -> untyped

      def encrypt: () -> untyped

      def decrypt: () -> untyped
    end
  end

  class ConnectionNotEstablished < ActiveRecordError
  end

  class StatementInvalid < ActiveRecordError
    def initialize: (?untyped? message, ?binds: untyped? binds, ?sql: untyped? sql) -> untyped

    attr_reader sql: untyped

    attr_reader binds: untyped
  end

  class MismatchedForeignKey < StatementInvalid
    def initialize: (?primary_key_column: untyped? primary_key_column, ?primary_key: untyped? primary_key, ?target_table: untyped? target_table, ?foreign_key: untyped? foreign_key, ?table: untyped? table, ?binds: untyped? binds, ?sql: untyped? sql, ?message: untyped? message) -> untyped
  end

  module Persistence
    extend ActiveSupport::Concern

    module ClassMethods
      def insert: (untyped attributes, ?unique_by: untyped?, ?returning: untyped?, ?record_timestamps: bool?) -> untyped

      def insert_all: (untyped attributes, ?unique_by: untyped?, ?returning: untyped?, ?record_timestamps: bool?) -> untyped

      def insert!: (untyped attributes, ?returning: untyped?, ?record_timestamps: bool?) -> untyped

      def insert_all!: (untyped attributes, ?returning: untyped?, ?record_timestamps: bool?) -> untyped

      def upsert: (untyped attributes, ?unique_by: untyped?, ?returning: untyped?, ?record_timestamps: bool?) -> untyped

      def upsert_all: (untyped attributes, ?unique_by: untyped?, ?returning: untyped?, ?record_timestamps: bool?) -> untyped
    end
  end

  class InsertAll
    @record_timestamps: bool

    def initialize: (untyped model, untyped inserts, on_duplicate: untyped, ?unique_by: untyped?, ?returning: untyped?, ?record_timestamps: bool?) -> untyped

    def record_timestamps?: () -> bool

    def keys_including_timestamps: () -> Set[String]

    def timestamps_for_create: () -> Hash[String, String]
  end
end

module Arel
  class Table
    def initialize: (untyped name, ?type_caster: untyped type_caster, ?as: untyped? as, ?klass: untyped?) -> void
  end

  class InsertManager < Arel::TreeManager
    def initialize: (?Arel::Table? table) -> untyped
  end

  class UpdateManager < Arel::TreeManager
    def initialize: (?Arel::Table? table) -> untyped
  end

  class DeleteManager < Arel::TreeManager
    def initialize: (?Arel::Table? table) -> untyped
  end
end
