#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'
set -v

RBS_DIR=$(cd $(dirname $0)/..; pwd)
REPO_DIR=$(cd $(dirname $0)/../../..; pwd)

bundle exec rbs --repo $REPO_DIR -r ast:2.4 validate --silent

cd ${RBS_DIR}/_test
bundle exec steep check

$(git rev-parse --show-toplevel)/bin/check-untyped-call.rb
