D = Steep::Diagnostic

target :test do
  check "."

  repo_path "../../../"
  library "httparty:0.18"
  library "uri"
  library "net-http"
  signature "."

  configure_code_diagnostics(D::Ruby.all_error)
end
