module Ancestry
  module MaterializedPath2[AncestryBaseClass, Relation, PrimaryKey]
    include MaterializedPath[AncestryBaseClass, Relation, PrimaryKey]

    def indirects_of: (AncestryBaseClass | PrimaryKey object) -> Relation

    def ordered_by_ancestry: (?untyped? order) -> Relation

    def descendants_by_ancestry: (String ancestry) -> Arel::Nodes::Matches

    def ancestry_root: () -> String

    def child_ancestry_sql: () -> String

    def ancestry_depth_sql: () -> String

    def generate_ancestry: (Array[PrimaryKey]? ancestor_ids) -> String

    def self.construct_depth_sql: (String table_name, String ancestry_column, String ancestry_delimiter) -> String

    private

    def ancestry_nil_allowed?: () -> false

    def ancestry_format_regexp: ('[0-9]+' | '[-A-Fa-f0-9]{36}' primary_key_format) -> Regexp

    module InstanceMethods[PrimaryKey]
      def child_ancestry: () -> String

      def child_ancestry_before_last_save: () -> String
    end
  end
end
