module Ancestry
  module MaterializedPathPg
    def update_descendants_with_new_ancestry: () -> void

    def update_descendants_hook: (Hash[String | Symbol, untyped] update_clause, String old_ancestry, String new_ancestry) -> Hash[String | Symbol, untyped]
  end
end
