module Stripe
  module Billing
    class CreditBalanceSummaryService < StripeService
      def retrieve: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Billing::CreditBalanceSummary
    end
  end
end
