module Stripe
  module Billing
    class MeterEventSummaryService < StripeService
      def list: (String id, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::Billing::MeterEventSummary]
    end
  end
end
