module Stripe
  module Billing
    class MeterEventAdjustmentService < StripeService
      def create: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Billing::MeterEventAdjustment
    end
  end
end
