rainbow = Rainbow("hello")

rainbow.color(:pink)
rainbow.reset
  .italic
  .bold
  .underline
  .blink
  .inverse
  .hide
  .black
  .red
  .green
  .yellow
  .blue
  .magenta
  .cyan
  .white

Rainbow.enabled
Rainbow.enabled = false
Rainbow.uncolor("a string")

# X11 color names
Rainbow('Hi').aliceblue
Rainbow('Hi').antiquewhite
Rainbow('Hi').aqua
Rainbow('Hi').aquamarine
Rainbow('Hi').azure
Rainbow('Hi').beige
Rainbow('Hi').bisque
Rainbow('Hi').blanchedalmond
Rainbow('Hi').blueviolet
Rainbow('Hi').brown
Rainbow('Hi').burlywood
Rainbow('Hi').cadetblue
Rainbow('Hi').chartreuse
Rainbow('Hi').chocolate
Rainbow('Hi').coral
Rainbow('Hi').cornflower
Rainbow('Hi').cornsilk
Rainbow('Hi').crimson
Rainbow('Hi').darkblue
Rainbow('Hi').darkcyan
Rainbow('Hi').darkgoldenrod
Rainbow('Hi').darkgray
Rainbow('Hi').darkgreen
Rainbow('Hi').darkkhaki
Rainbow('Hi').darkmagenta
Rainbow('Hi').darkolivegreen
Rainbow('Hi').darkorange
Rainbow('Hi').darkorchid
Rainbow('Hi').darkred
Rainbow('Hi').darksalmon
Rainbow('Hi').darkseagreen
Rainbow('Hi').darkslateblue
Rainbow('Hi').darkslategray
Rainbow('Hi').darkturquoise
Rainbow('Hi').darkviolet
Rainbow('Hi').deeppink
Rainbow('Hi').deepskyblue
Rainbow('Hi').dimgray
Rainbow('Hi').dodgerblue
Rainbow('Hi').firebrick
Rainbow('Hi').floralwhite
Rainbow('Hi').forestgreen
Rainbow('Hi').fuchsia
Rainbow('Hi').gainsboro
Rainbow('Hi').ghostwhite
Rainbow('Hi').gold
Rainbow('Hi').goldenrod
Rainbow('Hi').gray
Rainbow('Hi').greenyellow
Rainbow('Hi').honeydew
Rainbow('Hi').hotpink
Rainbow('Hi').indianred
Rainbow('Hi').indigo
Rainbow('Hi').ivory
Rainbow('Hi').khaki
Rainbow('Hi').lavender
Rainbow('Hi').lavenderblush
Rainbow('Hi').lawngreen
Rainbow('Hi').lemonchiffon
Rainbow('Hi').lightblue
Rainbow('Hi').lightcoral
Rainbow('Hi').lightcyan
Rainbow('Hi').lightgoldenrod
Rainbow('Hi').lightgray
Rainbow('Hi').lightgreen
Rainbow('Hi').lightpink
Rainbow('Hi').lightsalmon
Rainbow('Hi').lightseagreen
Rainbow('Hi').lightskyblue
Rainbow('Hi').lightslategray
Rainbow('Hi').lightsteelblue
Rainbow('Hi').lightyellow
Rainbow('Hi').lime
Rainbow('Hi').limegreen
Rainbow('Hi').linen
Rainbow('Hi').maroon
Rainbow('Hi').mediumaquamarine
Rainbow('Hi').mediumblue
Rainbow('Hi').mediumorchid
Rainbow('Hi').mediumpurple
Rainbow('Hi').mediumseagreen
Rainbow('Hi').mediumslateblue
Rainbow('Hi').mediumspringgreen
Rainbow('Hi').mediumturquoise
Rainbow('Hi').mediumvioletred
Rainbow('Hi').midnightblue
Rainbow('Hi').mintcream
Rainbow('Hi').mistyrose
Rainbow('Hi').moccasin
Rainbow('Hi').navajowhite
Rainbow('Hi').navyblue
Rainbow('Hi').oldlace
Rainbow('Hi').olive
Rainbow('Hi').olivedrab
Rainbow('Hi').orange
Rainbow('Hi').orangered
Rainbow('Hi').orchid
Rainbow('Hi').palegoldenrod
Rainbow('Hi').palegreen
Rainbow('Hi').paleturquoise
Rainbow('Hi').palevioletred
Rainbow('Hi').papayawhip
Rainbow('Hi').peachpuff
Rainbow('Hi').peru
Rainbow('Hi').pink
Rainbow('Hi').plum
Rainbow('Hi').powderblue
Rainbow('Hi').purple
Rainbow('Hi').rebeccapurple
Rainbow('Hi').rosybrown
Rainbow('Hi').royalblue
Rainbow('Hi').saddlebrown
Rainbow('Hi').salmon
Rainbow('Hi').sandybrown
Rainbow('Hi').seagreen
Rainbow('Hi').seashell
Rainbow('Hi').sienna
Rainbow('Hi').silver
Rainbow('Hi').skyblue
Rainbow('Hi').slateblue
Rainbow('Hi').slategray
Rainbow('Hi').snow
Rainbow('Hi').springgreen
Rainbow('Hi').steelblue
Rainbow('Hi').tan
Rainbow('Hi').teal
Rainbow('Hi').thistle
Rainbow('Hi').tomato
Rainbow('Hi').turquoise
Rainbow('Hi').violet
Rainbow('Hi').webgray
Rainbow('Hi').webgreen
Rainbow('Hi').webmaroon
Rainbow('Hi').webpurple
Rainbow('Hi').wheat
Rainbow('Hi').whitesmoke
Rainbow('Hi').yellowgreen
