D = Steep::Diagnostic

target :test do
  check "."
  signature "."

  repo_path "../../../"
  library "operator_recordable"

  library "activemodel"
  library "activerecord"
  library "activesupport"
  library "date"
  library "erb"
  library "logger"
  library "monitor"
  library "mutex_m"
  library "singleton"
  library 'time'

  configure_code_diagnostics(D::Ruby.all_error)
end
