class ApplicationRecord < ActiveRecord::Base
  include OperatorRecordable::Extension
  extend OperatorRecordable::Extension::ClassMethods
end

class Post < ApplicationRecord
end

class Operator < ApplicationRecord
end
