module Geocoder
  #
  # Search for information about an address or a set of coordinates.
  #
  def self.search: (untyped query, ?::Hash[untyped, untyped] options) -> untyped

  #
  # Look up the coordinates of the given street or IP address.
  #
  def self.coordinates: (untyped address, ?::Hash[untyped, untyped] options) -> (untyped | nil)

  #
  # Look up the address of the given coordinates ([lat,lon])
  # or IP address (string).
  #
  def self.address: (untyped query, ?::Hash[untyped, untyped] options) -> (untyped | nil)
end
