D = Steep::Diagnostic

target :test do
  check "."
  signature "."

  repo_path "../../../"
  library "http"
  library "forwardable"
  library "delegate"

  configure_code_diagnostics(D::Ruby.all_error)
end
