module Ancestry
  module MaterializedPath2[AncestryBaseClass, Relation, PrimaryKey]
    include MaterializedPath[AncestryBaseClass, Relation, PrimaryKey]

    def indirects_of: (AncestryBaseClass | PrimaryKey object) -> Relation

    def ordered_by_ancestry: (?untyped? order) -> Relation

    def descendants_by_ancestry: (String ancestry) -> Arel::Nodes::Matches

    def ancestry_root: () -> String

    def child_ancestry_sql: () -> String

    def ancestry_depth_sql: () -> String

    def generate_ancestry: (Array[PrimaryKey]? ancestor_ids) -> String

    def self.generate: [T] (Array[T]? ancestor_ids, String delimiter, String root) -> String

    def self.child_ancestry_value: [T] (String? ancestry_value, T id, String delimiter) -> String

    def self.child_ancestry_sql: (String table_name, String | Symbol ancestry_column, String | Symbol primary_key, String delimiter, String adapter) -> String

    def self.descendants_condition: (Arel::Attributes::Attribute attr, String child_ancestry, String _delimiter) -> Arel::Nodes::Matches

    def self.indirects_condition: (Arel::Attributes::Attribute attr, String child_ancestry, String delimiter) -> Arel::Nodes::Matches

    def self.construct_depth_sql: (String table_name, String | Symbol ancestry_column, String ancestry_delimiter) -> String

    def self.validation_options: ('[0-9]+' | '[-A-Fa-f0-9]{36}' primary_key_format, String delimiter) -> { format: { with: Regexp }, allow_nil: false }

    private

    def ancestry_validation_options: ('[0-9]+' | '[-A-Fa-f0-9]{36}' ancestry_primary_key_format) -> { format: { with: Regexp }, allow_nil: bool }

    module InstanceMethods[PrimaryKey]
      def child_ancestry: () -> String

      def child_ancestry_before_last_save: () -> String
    end
  end
end
