class TestCallbackObject < ActiveRecord::Base
  def local_condition1: () -> bool
  def local_condition2: () -> bool
  def local_condition3: () -> bool

  RAILS_60_DOCS_EXAMPLE: [Symbol, ^(TestCallbackObject) [self: TestCallbackObject] -> bool, ^(TestCallbackObject) [self: TestCallbackObject] -> bool]

  def custom_validation: () -> void
end

