class User < ActiveRecord::Base
  class ActiveRecord_Relation < ActiveRecord::Relation
  end

  extend ActiveRecord::Base::ClassMethods[User, ActiveRecord_Relation, Integer]

  def something: () -> untyped
end
