target :test do
  signature "."
  check "."

  repo_path "../../../"

  library "pathname"
  library "logger"
  library "mutex_m"
  library "date"
  library "monitor"
  library "singleton"
  library "tsort"

  library "activerecord:6.0.3.2"
  library "activesupport:6.0.3.2"
  library "actionpack:6.0.3.2"
  library "activejob:6.0.3.2"
  library "activemodel:6.0.3.2"
  library "actionview:6.0.3.2"
  library "activerecord:6.0.3.2"
  library "railties:6.0.3.2"

  typing_options :strict
end
