D = Steep::Diagnostic

target :test do
  signature "."
  check "."

  repo_path "../../../"

  library "pathname"
  library "logger"
  library "mutex_m"
  library "date"
  library "monitor"
  library "singleton"
  library "tsort"
  library 'time'

  library "activerecord:6.0"
  library "activesupport:6.0"
  library "activemodel:6.0"

  configure_code_diagnostics(D::Ruby.all_error)
end
