module Arbre
  class Element
    module BuilderMethods
      module ClassMethods
        def builder_method: (_ToS) -> void
      end
    end

    extend BuilderMethods::ClassMethods
  end

  module HTML
    class Tag < Element
    end

    class Div < Tag
    end
  end

  class Component < HTML::Div
  end
end
