D = Steep::Diagnostic

target :test do
  check "."
  signature '.'

  repo_path "../../../"

  library "pathname"
  library "aws-sdk-core:3"
  library "aws-sdk-s3:1"

  configure_code_diagnostics(D::Ruby.all_error)
end
