module Stripe
  module V2
    module Core
      class AccountService < StripeService
        attr_reader persons: ::Stripe::V2::Core::Accounts::PersonService

        attr_reader person_tokens: ::Stripe::V2::Core::Accounts::PersonTokenService

        def close: (String id, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::V2::Core::Account

        def create: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::V2::Core::Account

        def list: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::V2::ListObject[::Stripe::V2::Core::Account]

        def retrieve: (String id, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::V2::Core::Account

        def update: (String id, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::V2::Core::Account
      end
    end
  end
end
