module Stripe
  module V2
    module Core
      class AccountLinkService < StripeService
        def create: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::V2::Core::AccountLink
      end
    end
  end
end
