module Stripe
  module V2
    module Core
      class EventService < StripeService
        def list: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::V2::ListObject[::Stripe::V2::Core::Event]

        def retrieve: (String id, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::V2::Core::Event
      end
    end
  end
end
