module Google
  module Apis
    module BigqueryV2
      class AggregateClassificationMetrics
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class AggregationThresholdPolicy
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class Argument
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class ArimaCoefficients
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class ArimaFittingMetrics
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class ArimaForecastingMetrics
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class ArimaModelInfo
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class ArimaOrder
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class ArimaResult
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class ArimaSingleModelForecastingMetrics
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class AuditConfig
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class AuditLogConfig
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class AvroOptions
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class BiEngineReason
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class BiEngineStatistics
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class BigLakeConfiguration
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class BigQueryModelTraining
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class BigtableColumn
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class BigtableColumnFamily
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class BigtableOptions
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class BinaryClassificationMetrics
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class BinaryConfusionMatrix
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class Binding
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class BqmlIterationResult
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class BqmlTrainingRun
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        class TrainingOptions
          # class Representation < Google::Apis::Core::JsonRepresentation
          # end

          include Google::Apis::Core::JsonObjectSupport
        end

        include Google::Apis::Core::JsonObjectSupport
      end

      class CategoricalValue
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class CategoryCount
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class CloneDefinition
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class Cluster
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class ClusterInfo
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class Clustering
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class ClusteringMetrics
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class ConfusionMatrix
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class ConnectionProperty
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class CsvOptions
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class DataFormatOptions
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class DataMaskingStatistics
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class DataPolicyOption
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class DataSplitResult
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class Dataset
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        class Access
          # class Representation < Google::Apis::Core::JsonRepresentation
          # end

          include Google::Apis::Core::JsonObjectSupport
        end

        class Tag
          # class Representation < Google::Apis::Core::JsonRepresentation
          # end

          include Google::Apis::Core::JsonObjectSupport
        end

        include Google::Apis::Core::JsonObjectSupport
      end

      class DatasetAccessEntry
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class DatasetList
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        class Dataset
          # class Representation < Google::Apis::Core::JsonRepresentation
          # end

          include Google::Apis::Core::JsonObjectSupport
        end

        include Google::Apis::Core::JsonObjectSupport
      end

      class DatasetReference
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class DestinationTableProperties
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class DifferentialPrivacyPolicy
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class DimensionalityReductionMetrics
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class DmlStatistics
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class DoubleCandidates
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class DoubleHparamSearchSpace
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class DoubleRange
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class EncryptionConfiguration
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class Entry
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class ErrorProto
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class EvaluationMetrics
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class ExplainQueryStage
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class ExplainQueryStep
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class Explanation
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class ExportDataStatistics
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class Expr
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class ExternalCatalogDatasetOptions
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class ExternalCatalogTableOptions
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class ExternalDataConfiguration
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class ExternalDatasetReference
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class ExternalServiceCost
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class FeatureValue
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class ForeignTypeInfo
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class ForeignViewDefinition
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class GetIamPolicyRequest
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class GetPolicyOptions
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class GetQueryResultsResponse
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class GetServiceAccountResponse
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class GlobalExplanation
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class GoogleSheetsOptions
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class HighCardinalityJoin
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class HivePartitioningOptions
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class HparamSearchSpaces
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class HparamTuningTrial
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class IndexUnusedReason
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class InputDataChange
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class IntArray
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class IntArrayHparamSearchSpace
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class IntCandidates
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class IntHparamSearchSpace
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class IntRange
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class IterationResult
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class Job
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class CancelJobResponse
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class JobConfiguration
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class JobConfigurationExtract
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class JobConfigurationLoad
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class JobConfigurationQuery
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class JobConfigurationTableCopy
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class JobCreationReason
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class JobList
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        class Job
          # class Representation < Google::Apis::Core::JsonRepresentation
          # end

          include Google::Apis::Core::JsonObjectSupport
        end

        include Google::Apis::Core::JsonObjectSupport
      end

      class JobReference
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class JobStatistics
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        class ReservationUsage
          # class Representation < Google::Apis::Core::JsonRepresentation
          # end

          include Google::Apis::Core::JsonObjectSupport
        end

        include Google::Apis::Core::JsonObjectSupport
      end

      class JobStatistics2
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        class ReservationUsage
          # class Representation < Google::Apis::Core::JsonRepresentation
          # end

          include Google::Apis::Core::JsonObjectSupport
        end

        include Google::Apis::Core::JsonObjectSupport
      end

      class JobStatistics3
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class JobStatistics4
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class JobStatistics5
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class JobStatus
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class JoinRestrictionPolicy
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class JsonOptions
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class LinkedDatasetMetadata
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class LinkedDatasetSource
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class ListModelsResponse
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class ListRoutinesResponse
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class ListRowAccessPoliciesResponse
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class LoadQueryStatistics
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class LocationMetadata
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class MaterializedView
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class MaterializedViewDefinition
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class MaterializedViewStatistics
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class MaterializedViewStatus
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class MetadataCacheStatistics
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class MlStatistics
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class Model
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class ModelDefinition
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        class ModelOptions
          # class Representation < Google::Apis::Core::JsonRepresentation
          # end

          include Google::Apis::Core::JsonObjectSupport
        end

        include Google::Apis::Core::JsonObjectSupport
      end

      class ModelExtractOptions
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class ModelReference
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class MultiClassClassificationMetrics
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class ParquetOptions
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class PartitionSkew
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class PartitionedColumn
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class PartitioningDefinition
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class PerformanceInsights
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class Policy
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class PrincipalComponentInfo
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class PrivacyPolicy
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class ProjectList
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        class Project
          # class Representation < Google::Apis::Core::JsonRepresentation
          # end

          include Google::Apis::Core::JsonObjectSupport
        end

        include Google::Apis::Core::JsonObjectSupport
      end

      class ProjectReference
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class QueryInfo
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class QueryParameter
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class QueryParameterType
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        class StructType
          # class Representation < Google::Apis::Core::JsonRepresentation
          # end

          include Google::Apis::Core::JsonObjectSupport
        end

        include Google::Apis::Core::JsonObjectSupport
      end

      class QueryParameterValue
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class QueryRequest
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class QueryResponse
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class QueryTimelineSample
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class RangePartitioning
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        class Range
          # class Representation < Google::Apis::Core::JsonRepresentation
          # end

          include Google::Apis::Core::JsonObjectSupport
        end

        include Google::Apis::Core::JsonObjectSupport
      end

      class RangeValue
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class RankingMetrics
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class RegressionMetrics
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class RemoteFunctionOptions
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class RemoteModelInfo
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class RestrictionConfig
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class Routine
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class RoutineReference
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class Row
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class RowAccessPolicy
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class RowAccessPolicyReference
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class RowLevelSecurityStatistics
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class ScriptOptions
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class ScriptStackFrame
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class ScriptStatistics
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class SearchStatistics
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class SerDeInfo
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class SessionInfo
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class SetIamPolicyRequest
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class SkewSource
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class SnapshotDefinition
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class SparkLoggingInfo
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class SparkOptions
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class SparkStatistics
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class StagePerformanceChangeInsight
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class StagePerformanceStandaloneInsight
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class StandardSqlDataType
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class StandardSqlField
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class StandardSqlStructType
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class StandardSqlTableType
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class StorageDescriptor
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class Streamingbuffer
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class StringHparamSearchSpace
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class SystemVariables
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class Table
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class TableCell
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class TableConstraints
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        class ForeignKey
          # class Representation < Google::Apis::Core::JsonRepresentation
          # end

          class ColumnReference
            # class Representation < Google::Apis::Core::JsonRepresentation
            # end

            include Google::Apis::Core::JsonObjectSupport
          end

          class ReferencedTable
            # class Representation < Google::Apis::Core::JsonRepresentation
            # end

            include Google::Apis::Core::JsonObjectSupport
          end

          include Google::Apis::Core::JsonObjectSupport
        end

        class PrimaryKey
          # class Representation < Google::Apis::Core::JsonRepresentation
          # end

          include Google::Apis::Core::JsonObjectSupport
        end

        include Google::Apis::Core::JsonObjectSupport
      end

      class InsertAllTableDataRequest
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        class Row
          # class Representation < Google::Apis::Core::JsonRepresentation
          # end

          include Google::Apis::Core::JsonObjectSupport
        end

        include Google::Apis::Core::JsonObjectSupport
      end

      class InsertAllTableDataResponse
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        class InsertError
          # class Representation < Google::Apis::Core::JsonRepresentation
          # end

          include Google::Apis::Core::JsonObjectSupport
        end

        include Google::Apis::Core::JsonObjectSupport
      end

      class TableDataList
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class TableFieldSchema
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        class Categories
          # class Representation < Google::Apis::Core::JsonRepresentation
          # end

          include Google::Apis::Core::JsonObjectSupport
        end

        class PolicyTags
          # class Representation < Google::Apis::Core::JsonRepresentation
          # end

          include Google::Apis::Core::JsonObjectSupport
        end

        class RangeElementType
          # class Representation < Google::Apis::Core::JsonRepresentation
          # end

          include Google::Apis::Core::JsonObjectSupport
        end

        include Google::Apis::Core::JsonObjectSupport
      end

      class TableList
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        class Table
          # class Representation < Google::Apis::Core::JsonRepresentation
          # end

          class View
            # class Representation < Google::Apis::Core::JsonRepresentation
            # end

            include Google::Apis::Core::JsonObjectSupport
          end

          include Google::Apis::Core::JsonObjectSupport
        end

        include Google::Apis::Core::JsonObjectSupport
      end

      class TableMetadataCacheUsage
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class TableReference
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class TableReplicationInfo
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class TableRow
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class TableSchema
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class TestIamPermissionsRequest
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class TestIamPermissionsResponse
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class TimePartitioning
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class TrainingOptions
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class TrainingRun
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class TransactionInfo
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class TransformColumn
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class UndeleteDatasetRequest
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class UserDefinedFunctionResource
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class VectorSearchStatistics
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class ViewDefinition
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        include Google::Apis::Core::JsonObjectSupport
      end

      class AggregateClassificationMetrics
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class AggregationThresholdPolicy
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class Argument
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class ArimaCoefficients
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class ArimaFittingMetrics
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class ArimaForecastingMetrics
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class ArimaModelInfo
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class ArimaOrder
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class ArimaResult
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class ArimaSingleModelForecastingMetrics
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class AuditConfig
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class AuditLogConfig
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class AvroOptions
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class BiEngineReason
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class BiEngineStatistics
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class BigLakeConfiguration
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class BigQueryModelTraining
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class BigtableColumn
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class BigtableColumnFamily
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class BigtableOptions
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class BinaryClassificationMetrics
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class BinaryConfusionMatrix
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class Binding
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class BqmlIterationResult
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class BqmlTrainingRun
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        class TrainingOptions
          # @private
          # class Representation < Google::Apis::Core::JsonRepresentation
          # end
        end
      end

      class CategoricalValue
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class CategoryCount
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class CloneDefinition
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class Cluster
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class ClusterInfo
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class Clustering
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class ClusteringMetrics
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class ConfusionMatrix
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class ConnectionProperty
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class CsvOptions
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class DataFormatOptions
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class DataMaskingStatistics
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class DataPolicyOption
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class DataSplitResult
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class Dataset
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        class Access
          # @private
          # class Representation < Google::Apis::Core::JsonRepresentation
          # end
        end

        class Tag
          # @private
          # class Representation < Google::Apis::Core::JsonRepresentation
          # end
        end
      end

      class DatasetAccessEntry
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class DatasetList
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        class Dataset
          # @private
          # class Representation < Google::Apis::Core::JsonRepresentation
          # end
        end
      end

      class DatasetReference
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class DestinationTableProperties
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class DifferentialPrivacyPolicy
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class DimensionalityReductionMetrics
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class DmlStatistics
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class DoubleCandidates
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class DoubleHparamSearchSpace
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class DoubleRange
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class EncryptionConfiguration
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class Entry
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class ErrorProto
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class EvaluationMetrics
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class ExplainQueryStage
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class ExplainQueryStep
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class Explanation
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class ExportDataStatistics
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class Expr
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class ExternalCatalogDatasetOptions
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class ExternalCatalogTableOptions
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class ExternalDataConfiguration
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class ExternalDatasetReference
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class ExternalServiceCost
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class FeatureValue
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class ForeignTypeInfo
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class ForeignViewDefinition
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class GetIamPolicyRequest
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class GetPolicyOptions
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class GetQueryResultsResponse
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class GetServiceAccountResponse
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class GlobalExplanation
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class GoogleSheetsOptions
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class HighCardinalityJoin
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class HivePartitioningOptions
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class HparamSearchSpaces
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class HparamTuningTrial
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class IndexUnusedReason
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class InputDataChange
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class IntArray
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class IntArrayHparamSearchSpace
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class IntCandidates
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class IntHparamSearchSpace
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class IntRange
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class IterationResult
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class Job
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class CancelJobResponse
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class JobConfiguration
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class JobConfigurationExtract
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class JobConfigurationLoad
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class JobConfigurationQuery
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class JobConfigurationTableCopy
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class JobCreationReason
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class JobList
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        class Job
          # @private
          # class Representation < Google::Apis::Core::JsonRepresentation
          # end
        end
      end

      class JobReference
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class JobStatistics
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        class ReservationUsage
          # @private
          # class Representation < Google::Apis::Core::JsonRepresentation
          # end
        end
      end

      class JobStatistics2
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        class ReservationUsage
          # @private
          # class Representation < Google::Apis::Core::JsonRepresentation
          # end
        end
      end

      class JobStatistics3
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class JobStatistics4
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class JobStatistics5
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class JobStatus
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class JoinRestrictionPolicy
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class JsonOptions
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class LinkedDatasetMetadata
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class LinkedDatasetSource
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class ListModelsResponse
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class ListRoutinesResponse
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class ListRowAccessPoliciesResponse
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class LoadQueryStatistics
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class LocationMetadata
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class MaterializedView
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class MaterializedViewDefinition
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class MaterializedViewStatistics
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class MaterializedViewStatus
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class MetadataCacheStatistics
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class MlStatistics
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class Model
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class ModelDefinition
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        class ModelOptions
          # @private
          # class Representation < Google::Apis::Core::JsonRepresentation
          # end
        end
      end

      class ModelExtractOptions
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class ModelReference
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class MultiClassClassificationMetrics
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class ParquetOptions
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class PartitionSkew
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class PartitionedColumn
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class PartitioningDefinition
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class PerformanceInsights
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class Policy
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class PrincipalComponentInfo
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class PrivacyPolicy
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class ProjectList
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        class Project
          # @private
          # class Representation < Google::Apis::Core::JsonRepresentation
          # end
        end
      end

      class ProjectReference
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class QueryInfo
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class QueryParameter
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class QueryParameterType
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        class StructType
          # @private
          # class Representation < Google::Apis::Core::JsonRepresentation
          # end
        end
      end

      class QueryParameterValue
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class QueryRequest
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class QueryResponse
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class QueryTimelineSample
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class RangePartitioning
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        class Range
          # @private
          # class Representation < Google::Apis::Core::JsonRepresentation
          # end
        end
      end

      class RangeValue
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class RankingMetrics
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class RegressionMetrics
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class RemoteFunctionOptions
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class RemoteModelInfo
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class RestrictionConfig
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class Routine
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class RoutineReference
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class Row
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class RowAccessPolicy
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class RowAccessPolicyReference
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class RowLevelSecurityStatistics
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class ScriptOptions
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class ScriptStackFrame
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class ScriptStatistics
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class SearchStatistics
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class SerDeInfo
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class SessionInfo
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class SetIamPolicyRequest
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class SkewSource
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class SnapshotDefinition
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class SparkLoggingInfo
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class SparkOptions
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class SparkStatistics
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class StagePerformanceChangeInsight
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class StagePerformanceStandaloneInsight
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class StandardSqlDataType
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class StandardSqlField
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class StandardSqlStructType
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class StandardSqlTableType
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class StorageDescriptor
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class Streamingbuffer
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class StringHparamSearchSpace
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class SystemVariables
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class Table
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class TableCell
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class TableConstraints
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        class ForeignKey
          # @private
          # class Representation < Google::Apis::Core::JsonRepresentation
          # end

          class ColumnReference
            # @private
            # class Representation < Google::Apis::Core::JsonRepresentation
            # end
          end

          class ReferencedTable
            # @private
            # class Representation < Google::Apis::Core::JsonRepresentation
            # end
          end
        end

        class PrimaryKey
          # @private
          # class Representation < Google::Apis::Core::JsonRepresentation
          # end
        end
      end

      class InsertAllTableDataRequest
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        class Row
          # @private
          # class Representation < Google::Apis::Core::JsonRepresentation
          # end
        end
      end

      class InsertAllTableDataResponse
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        class InsertError
          # @private
          # class Representation < Google::Apis::Core::JsonRepresentation
          # end
        end
      end

      class TableDataList
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class TableFieldSchema
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        class Categories
          # @private
          # class Representation < Google::Apis::Core::JsonRepresentation
          # end
        end

        class PolicyTags
          # @private
          # class Representation < Google::Apis::Core::JsonRepresentation
          # end
        end

        class RangeElementType
          # @private
          # class Representation < Google::Apis::Core::JsonRepresentation
          # end
        end
      end

      class TableList
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end

        class Table
          # @private
          # class Representation < Google::Apis::Core::JsonRepresentation
          # end

          class View
            # @private
            # class Representation < Google::Apis::Core::JsonRepresentation
            # end
          end
        end
      end

      class TableMetadataCacheUsage
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class TableReference
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class TableReplicationInfo
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class TableRow
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class TableSchema
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class TestIamPermissionsRequest
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class TestIamPermissionsResponse
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class TimePartitioning
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class TrainingOptions
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class TrainingRun
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class TransactionInfo
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class TransformColumn
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class UndeleteDatasetRequest
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class UserDefinedFunctionResource
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class VectorSearchStatistics
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end

      class ViewDefinition
        # @private
        # class Representation < Google::Apis::Core::JsonRepresentation
        # end
      end
    end
  end
end
