#!/bin/bash

set -xe

REPO=$(git rev-parse --show-toplevel)/gems
bundle exec rbs --repo=$REPO \
  -rmonitor -rdate -rerb -rsingleton -rlogger -rmutex_m -ractivesupport -rtime \
  -ractivemodel validate --silent

# TODO
# $(git rev-parse --show-toplevel)/bin/check-untyped-call.rb
