module RestClient
  class Exception < RuntimeError
    def http_code: () -> Integer?
    def http_headers: () -> Hash[untyped, untyped]?
    def http_body: () -> String?
    def to_s: () -> String
    def message: () -> String
  end

  class ExceptionWithResponse < Exception
  end

  class Continue
  end

  class SwitchingProtocols
  end

  class Processing
  end

  class OK
  end

  class Created
  end

  class Accepted
  end

  class NonAuthoritativeInformation
  end

  class NoContent
  end

  class ResetContent
  end

  class PartialContent
  end

  class MultiStatus
  end

  class AlreadyReported
  end

  class IMUsed
  end

  class MultipleChoices
  end

  class MovedPermanently
  end

  class Found
  end

  class SeeOther
  end

  class NotModified
  end

  class UseProxy
  end

  class SwitchProxy
  end

  class TemporaryRedirect
  end

  class PermanentRedirect
  end

  class BadRequest
  end

  class Unauthorized
  end

  class PaymentRequired
  end

  class Forbidden
  end

  class NotFound
  end

  class MethodNotAllowed
  end

  class NotAcceptable
  end

  class ProxyAuthenticationRequired
  end

  class RequestTimeout
  end

  class Conflict
  end

  class Gone
  end

  class LengthRequired
  end

  class PreconditionFailed
  end

  class PayloadTooLarge
  end

  class URITooLong
  end

  class UnsupportedMediaType
  end

  class RangeNotSatisfiable
  end

  class ExpectationFailed
  end

  class ImATeapot
  end

  class TooManyConnectionsFromThisIP
  end

  class UnprocessableEntity
  end

  class Locked
  end

  class FailedDependency
  end

  class UnorderedCollection
  end

  class UpgradeRequired
  end

  class PreconditionRequired
  end

  class TooManyRequests
  end

  class RequestHeaderFieldsTooLarge
  end

  class RetryWith
  end

  class BlockedByWindowsParentalControls
  end

  class InternalServerError
  end

  class NotImplemented
  end

  class BadGateway
  end

  class ServiceUnavailable
  end

  class GatewayTimeout
  end

  class HTTPVersionNotSupported
  end

  class VariantAlsoNegotiates
  end

  class InsufficientStorage
  end

  class LoopDetected
  end

  class BandwidthLimitExceeded
  end

  class NotExtended
  end

  class NetworkAuthenticationRequired
  end

  module Exceptions
    class Timeout < RequestTimeout
    end

    class OpenTimeout < Timeout
    end

    class ReadTimeout < Timeout
    end
  end

  class ServerBrokeConnection < Exception
  end

  class SSLCertificateNotVerified < Exception
  end
end
