source "https://rubygems.org"

gem "rails", path: "_src"
gem "orthoses"# , path: "../../../orthoses"
gem "orthoses-rails"# , path: "../../../orthoses-rails"
gem "rbs"# , path: "../../../rbs"

gem "rake"
gem "sqlite3"
if RUBY_VERSION >= "3.1"
  gem "net-smtp", require: false
  gem "net-imap", require: false
  gem "net-pop", require: false
  gem "psych", "~> 3"
end
