module Stripe
  module Apps
    class Secret < APIResource
      class Scope < ::Stripe::StripeObject
        def type: () -> String

        def user: () -> String?
      end

      def created: () -> Integer

      def deleted: () -> bool?

      def expires_at: () -> Integer?

      def id: () -> String

      def livemode: () -> bool

      def name: () -> String

      def object: () -> String

      def payload: () -> String?

      def scope: () -> Scope

      def self.create: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Apps::Secret

      def self.delete_where: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Apps::Secret

      def self.find: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Apps::Secret

      def self.list: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::Apps::Secret]
    end
  end
end
