# protobuf gem generates Ruby code depending on Google::Protobuf::FileOptions

module Google
  module Protobuf
    class FileOptions < ::Protobuf::Message
      class OptimizeMode < ::Protobuf::Enum
        SPEED: instance
        CODE_SIZE: instance
        LITE_RUNTIME: instance
      end
    end
  end
end
