module Protobuf
  # An interface with `#to_proto` method which returns a protobuf message object.
  interface _ToProto[M < Message]
    def to_proto: () -> M
  end

  # An interface with `#to_hash` method which returns a hash compatible convertible to a message object.
  #
  interface _ToHash[H < Hash[untyped, untyped]]
    def to_hash: () -> H
  end
end
