module Retryable
  # This module holds the Retryable version information.
  module Version
    def major: () -> Integer

    def minor: () -> Integer

    def patch: () -> Integer

    def to_h: () -> { major: Integer, minor: Integer, patch: Integer }

    def to_a: () -> Array[Integer]

    def to_s: () -> String
  end
end
