module Stripe
  module Checkout
    class SessionLineItemService < StripeService
      def list: (String session, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::LineItem]
    end
  end
end
