module Kernel
  def Async: [Result] (*untyped arguments, **untyped options) { (::Async::Task[untyped], *untyped) -> Result } -> ::Async::Task[Result]

  def Sync: [Result] () { (::Async::Task[untyped]) -> Result } -> Result
end
