D = Steep::Diagnostic

target :test do
  check "."
  signature '.'

  repo_path "../../../"
  library "net-http"
  library "net-protocol"
  library "timeout"

  configure_code_diagnostics(D::Ruby.all_error)
end
