D = Steep::Diagnostic

target :test do
  check "."

  repo_path "../../../"
  library "delayed_job:4.1"


  library 'pathname'
  library 'logger'
  library 'mutex_m'
  library 'date'
  library 'monitor'
  library 'singleton'
  library 'tsort'
  library 'time'

  library 'rack'
  library 'cgi'
  library 'uri'
  library 'activesupport'
  library 'actionpack'
  library 'activejob'
  library 'activemodel'
  library 'actionview'
  library 'activerecord'
  library 'railties'

  configure_code_diagnostics(D::Ruby.all_error)
end
