module Stripe
  class ErrorObject < StripeObject
    def advice_code: () -> String?

    def charge: () -> String?

    def code: () -> String?

    def decline_code: () -> String?

    def doc_url: () -> String?

    def message: () -> String?

    def network_advice_code: () -> String?

    def network_decline_code: () -> String?

    def param: () -> String?

    def payment_intent: () -> ::Stripe::PaymentIntent?

    def payment_method: () -> ::Stripe::PaymentMethod?

    def payment_method_type: () -> String?

    def request_log_url: () -> String?

    def setup_intent: () -> ::Stripe::SetupIntent?

    def source: () -> (::Stripe::Account | ::Stripe::BankAccount | ::Stripe::Card | ::Stripe::Source)?

    def type: () -> String

    def user_message: () -> String?
  end

  class OAuthErrorObject < StripeObject
    def error: () -> String?

    def error_description: () -> String?
  end
end
