module Google
  module Apis
    module Core
      # Adds to_hash to objects
      module Hashable
        # Convert object to hash representation
        #
        # @return [Hash]
        def to_h: () -> untyped

        # Recursively serialize an object
        #
        # @param [Object] val
        # @return [Hash]
        def self.process_value: (untyped val) -> untyped
      end
    end
  end
end
