module Google
  module Apis
    module Core
      # Logging support
      module Logging
        # Get the logger instance
        # @return [Logger]
        def logger: () -> untyped
      end
    end
  end
end
