# Remove the fake type if the real type is available
module Que
  class Job
  end
end

# Remove the fake type if the real type is available
class QC
  class Queue
  end
end

# Glue code that could be made more detailed if Sidekiq is available.
module Sidekiq
  module Job
  end
end

# Remove the fake type if the real type is available
module Sneakers
  module Worker
  end
end

# Remove the fake type if the real type is available
module SuckerPunch
  module Job
  end
end
