class Colour < ActiveHash::Base
  include ActiveHash::Enum
  extend ActiveHash::Enum::Methods
end

class Pallete < ActiveHash::Base
  include ActiveHash::Associations
  extend ActiveHash::Associations::Methods
end
