class User
  def admin?: () -> bool
end

class Post < ActiveRecord::Base
end

class Ability
  include CanCan::Ability

  def initialize: (User user) -> void
end

class TestController < ActionController::Base
  @post: Post

  def show: () -> void
end
