module Stripe
  module Radar
    class EarlyFraudWarning < APIResource
      def actionable: () -> bool

      def charge: () -> (String | ::Stripe::Charge)

      def created: () -> Integer

      def fraud_type: () -> String

      def id: () -> String

      def livemode: () -> bool

      def object: () -> String

      def payment_intent: () -> (String | ::Stripe::PaymentIntent)?

      def self.list: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::Radar::EarlyFraudWarning]
    end
  end
end
