module Stripe
  module Radar
    class ValueList < APIResource
      def alias: () -> String

      def created: () -> Integer

      def created_by: () -> String

      def deleted: () -> bool?

      def id: () -> String

      def item_type: () -> String

      def list_items: () -> ::Stripe::ListObject[::Stripe::Radar::ValueListItem]

      def livemode: () -> bool

      def metadata: () -> ::Stripe::StripeObject

      def name: () -> String

      def object: () -> String

      def self.create: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Radar::ValueList

      def self.delete: (String value_list, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Radar::ValueList

      def delete: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Radar::ValueList

      def self.list: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::Radar::ValueList]

      def self.update: (String value_list, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Radar::ValueList
    end
  end
end
