module Stripe
  module Radar
    class ValueListItem < APIResource
      def created: () -> Integer

      def created_by: () -> String

      def deleted: () -> bool?

      def id: () -> String

      def livemode: () -> bool

      def object: () -> String

      def value: () -> String

      def value_list: () -> String

      def self.create: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Radar::ValueListItem

      def self.delete: (String item, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Radar::ValueListItem

      def delete: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Radar::ValueListItem

      def self.list: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::Radar::ValueListItem]
    end
  end
end
