  # !!! GENERATED CODE !!!
  class OpenStruct
  end

  class Ripper
  end

  module Rake
    class TaskLib
    end
  end


  module WEBrick
    module HTTPServlet
      class AbstractServlet
      end
    end
  end

  module RDoc
    module Markup
      class ToHtml
      end
    end
  end
