module Stripe
  module BillingPortal
    class SessionService < StripeService
      def create: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::BillingPortal::Session
    end
  end
end
