module ActiveSupport
  module Cache
    module Strategy
      module LocalCache
        class LocalCacheRegistry
          def initialize: () -> void
          def cache_for: (untyped local_cache_key) -> untyped
          def set_cache_for: (untyped local_cache_key, untyped value) -> untyped
          def self.set_cache_for: (untyped l, untyped v) -> untyped
          def self.cache_for: (untyped l) -> untyped
          extend ActiveSupport::PerThreadRegistry
        end
      end
    end
  end
end
