#!ruby

require 'pathname'

VERSION = '6.0.3.2'

def sh!(*args, **kwargs)
  system(*args, **kwargs, exception: true)
end

base = Pathname(__dir__) / '../'
repo = base.join('../../')

%w[activemodel activesupport].each do |gem|
  sh! repo.join(gem, VERSION, '_script/test').to_s
end

sh!('bundle', 'install', chdir: base.join('_rbs_rails'))
sh!({ 'RAILS_VERSION' => VERSION, 'RBS_REPO_DIR' => repo.to_s }, 'bundle', 'exec', 'rake', chdir: base.join('_rbs_rails'))
