module Flexirest
  module Callbacks
    module ClassMethods
      def before_request: (Symbol method_name) -> void
                        | () { (Symbol name, Request request) -> (false | :retry | untyped) } -> void
      def after_request: (Symbol method_name) -> void
                       | () { (Symbol name, Request request) -> (false | :retry | untyped) } -> void
    end
  end
end
