module Flexirest
  module Configuration
    module ClassMethods
      def base_url: () -> (String | Array[String])
                  | (String value) -> String
                  | (Array[String] value) -> Array[String]
      def base_url=: (String value) -> String
      def request_body_type: (?Symbol value) -> Symbol
      def request_body_type=: (Symbol value) -> Symbol
      def whiny_missing: (?bool value) -> bool
      def verbose!: () -> true
      def verbose: (?bool value) -> bool
    end
  end
end
