module Flexirest
  class NoAttributeException < StandardError
  end

  class ValidationFailedException < StandardError
  end

  class MissingOptionalLibraryError < StandardError
  end

  def self.name: () -> String
  def self.name=: (String value) -> String
end
