module Flexirest
  class HeadersList
    def []=: (String key, untyped value) -> untyped
    def []: (String key) -> untyped
    def each: (?bool split_multiple_headers) { (String key, untyped value) -> void } -> void
    def delete: (String key) -> untyped
    def keys: () -> Array[String]
  end
end
