module Flexirest
  module Mapping
    module ClassMethods
      def get: (Symbol name, String url, ?Hash[untyped, untyped] options) -> untyped
      def put: (Symbol name, String url, ?Hash[untyped, untyped] options) -> untyped
      def post: (Symbol name, String url, ?Hash[untyped, untyped] options) -> untyped
      def delete: (Symbol name, String url, ?Hash[untyped, untyped] options) -> untyped
      def patch: (Symbol name, String url, ?Hash[untyped, untyped] options) -> untyped
    end
  end
end
