module SPS
  class Account
    include ActiveModel::Validations
    extend ::SPS::Converter
    include ::SPS::Converter::InstanceMethods

    attr_accessor name: ::String?
    attr_accessor iban: ::String?
    attr_accessor bic: ::String?

    def initialize: (
        debtor_account_attributes_type attributes
      ) -> void
  end
end
