module SPS
  class DebtorAccount < ::SPS::Account
    include ActiveModel::Validations
    extend ::SPS::Converter
    include ::SPS::Converter::InstanceMethods

    def initialize: (
        debtor_account_attributes_type account_options
      ) -> self
  end
end
