module SPS
  class StructuredRemittanceInformation
    include ActiveModel::Validations
    extend ::SPS::Converter
    include ::SPS::Converter::InstanceMethods

    attr_accessor proprietary: ::String
    attr_accessor reference: ::String

    def initialize: (
        {
          proprietary: ::String,
          reference: ::String
        } attributes
      ) -> void
  end
end
