target :test do
  signature "."
  check "."

  repo_path "../../../"

  library "pathname"
  library "logger"
  library "mutex_m"
  library "date"
  library "monitor"
  library "singleton"
  library "tsort"
  library "rack"

  library "activerecord:6.1.4.1"
  library "activesupport:6.1.4.1"
  library "actionpack:6.1.4.1"
  library "activejob:6.1.4.1"
  library "activemodel:6.1.4.1"
  library "actionview:6.1.4.1"
  library "railties:6.1.4.1"

  typing_options :strict
end
