module Shoryuken
  module Logging
    def self.initialize_logger: (?Logger::logdev? log_target) -> Logger

    def self.logger: () -> Logger

    def self.logger=: (Logger log) -> void

    def self.with_context: (untyped msg) { () -> void } -> void
  end
end
