module Shoryuken
  class Queue
    def visibility_timeout: () -> Integer
    def delete_messages: (untyped options) -> void
    def send_message: (untyped options) -> void
    def send_messages: (untyped options) -> void
    def receive_messages: (untyped options) -> void
    def fifo?: () -> bool
  end
end
