module Shoryuken
  module Worker
    module ClassMethods
      def shoryuken_options: (?queue: String, ?delete: bool, ?auto_delete: bool, ?auto_visibility_timeout: bool, ?retry_intervals: Numeric, ?batch: bool, ?body_parser: untyped) -> void
    end
  end
end
