module Devise
  class SessionsController < ::DeviseController
  end
end

# NOTE: `DeviseController` was not defined under the `Devise` module.
# https://github.com/heartcombo/devise/blob/fec67f98f26fcd9a79072e4581b1bd40d0c7fa1d/app/controllers/devise_controller.rb#L4
class DeviseController
end
