module Stripe
  module Issuing
    class PhysicalBundle < APIResource
      class Features < ::Stripe::StripeObject
        def card_logo: () -> String

        def carrier_text: () -> String

        def second_line: () -> String
      end

      def features: () -> Features

      def id: () -> String

      def livemode: () -> bool

      def name: () -> String

      def object: () -> String

      def status: () -> String

      def type: () -> String

      def self.list: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::Issuing::PhysicalBundle]
    end
  end
end
