module Stripe
  class AccountLink < APIResource
    def created: () -> Integer

    def expires_at: () -> Integer

    def object: () -> String

    def url: () -> String

    def self.create: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::AccountLink
  end
end
