module Stripe
  class AccountSession < APIResource
    class Components < ::Stripe::StripeObject
      class AccountManagement < ::Stripe::StripeObject
        class Features < ::Stripe::StripeObject
          def disable_stripe_user_authentication: () -> bool

          def external_account_collection: () -> bool
        end

        def enabled: () -> bool

        def features: () -> Features
      end

      class AccountOnboarding < ::Stripe::StripeObject
        class Features < ::Stripe::StripeObject
          def disable_stripe_user_authentication: () -> bool

          def external_account_collection: () -> bool
        end

        def enabled: () -> bool

        def features: () -> Features
      end

      class BalanceReport < ::Stripe::StripeObject
        class Features < ::Stripe::StripeObject
        end

        def enabled: () -> bool

        def features: () -> Features
      end

      class Balances < ::Stripe::StripeObject
        class Features < ::Stripe::StripeObject
          def disable_stripe_user_authentication: () -> bool

          def edit_payout_schedule: () -> bool

          def external_account_collection: () -> bool

          def instant_payouts: () -> bool

          def standard_payouts: () -> bool
        end

        def enabled: () -> bool

        def features: () -> Features
      end

      class DisputesList < ::Stripe::StripeObject
        class Features < ::Stripe::StripeObject
          def capture_payments: () -> bool

          def destination_on_behalf_of_charge_management: () -> bool

          def dispute_management: () -> bool

          def refund_management: () -> bool

          def smart_disputes_management: () -> bool
        end

        def enabled: () -> bool

        def features: () -> Features
      end

      class Documents < ::Stripe::StripeObject
        class Features < ::Stripe::StripeObject
        end

        def enabled: () -> bool

        def features: () -> Features
      end

      class FinancialAccount < ::Stripe::StripeObject
        class Features < ::Stripe::StripeObject
          def disable_stripe_user_authentication: () -> bool

          def external_account_collection: () -> bool

          def send_money: () -> bool

          def transfer_balance: () -> bool
        end

        def enabled: () -> bool

        def features: () -> Features
      end

      class FinancialAccountTransactions < ::Stripe::StripeObject
        class Features < ::Stripe::StripeObject
          def card_spend_dispute_management: () -> bool
        end

        def enabled: () -> bool

        def features: () -> Features
      end

      class InstantPayoutsPromotion < ::Stripe::StripeObject
        class Features < ::Stripe::StripeObject
          def disable_stripe_user_authentication: () -> bool

          def external_account_collection: () -> bool

          def instant_payouts: () -> bool
        end

        def enabled: () -> bool

        def features: () -> Features
      end

      class IssuingCard < ::Stripe::StripeObject
        class Features < ::Stripe::StripeObject
          def card_management: () -> bool

          def card_spend_dispute_management: () -> bool

          def cardholder_management: () -> bool

          def spend_control_management: () -> bool
        end

        def enabled: () -> bool

        def features: () -> Features
      end

      class IssuingCardsList < ::Stripe::StripeObject
        class Features < ::Stripe::StripeObject
          def card_management: () -> bool

          def card_spend_dispute_management: () -> bool

          def cardholder_management: () -> bool

          def disable_stripe_user_authentication: () -> bool

          def spend_control_management: () -> bool
        end

        def enabled: () -> bool

        def features: () -> Features
      end

      class NotificationBanner < ::Stripe::StripeObject
        class Features < ::Stripe::StripeObject
          def disable_stripe_user_authentication: () -> bool

          def external_account_collection: () -> bool
        end

        def enabled: () -> bool

        def features: () -> Features
      end

      class PaymentDetails < ::Stripe::StripeObject
        class Features < ::Stripe::StripeObject
          def capture_payments: () -> bool

          def destination_on_behalf_of_charge_management: () -> bool

          def dispute_management: () -> bool

          def refund_management: () -> bool

          def smart_disputes_management: () -> bool
        end

        def enabled: () -> bool

        def features: () -> Features
      end

      class PaymentDisputes < ::Stripe::StripeObject
        class Features < ::Stripe::StripeObject
          def destination_on_behalf_of_charge_management: () -> bool

          def dispute_management: () -> bool

          def refund_management: () -> bool

          def smart_disputes_management: () -> bool
        end

        def enabled: () -> bool

        def features: () -> Features
      end

      class PaymentMethodSettings < ::Stripe::StripeObject
        class Features < ::Stripe::StripeObject
          def disable_stripe_user_authentication: () -> bool
        end

        def enabled: () -> bool

        def features: () -> Features
      end

      class Payments < ::Stripe::StripeObject
        class Features < ::Stripe::StripeObject
          def capture_payments: () -> bool

          def destination_on_behalf_of_charge_management: () -> bool

          def dispute_management: () -> bool

          def refund_management: () -> bool

          def smart_disputes_management: () -> bool
        end

        def enabled: () -> bool

        def features: () -> Features
      end

      class PayoutDetails < ::Stripe::StripeObject
        class Features < ::Stripe::StripeObject
        end

        def enabled: () -> bool

        def features: () -> Features
      end

      class PayoutReconciliationReport < ::Stripe::StripeObject
        class Features < ::Stripe::StripeObject
        end

        def enabled: () -> bool

        def features: () -> Features
      end

      class Payouts < ::Stripe::StripeObject
        class Features < ::Stripe::StripeObject
          def disable_stripe_user_authentication: () -> bool

          def edit_payout_schedule: () -> bool

          def external_account_collection: () -> bool

          def instant_payouts: () -> bool

          def standard_payouts: () -> bool
        end

        def enabled: () -> bool

        def features: () -> Features
      end

      class PayoutsList < ::Stripe::StripeObject
        class Features < ::Stripe::StripeObject
        end

        def enabled: () -> bool

        def features: () -> Features
      end

      class TaxRegistrations < ::Stripe::StripeObject
        class Features < ::Stripe::StripeObject
        end

        def enabled: () -> bool

        def features: () -> Features
      end

      class TaxSettings < ::Stripe::StripeObject
        class Features < ::Stripe::StripeObject
        end

        def enabled: () -> bool

        def features: () -> Features
      end

      def account_management: () -> AccountManagement

      def account_onboarding: () -> AccountOnboarding

      def balance_report: () -> BalanceReport

      def balances: () -> Balances

      def disputes_list: () -> DisputesList

      def documents: () -> Documents

      def financial_account: () -> FinancialAccount

      def financial_account_transactions: () -> FinancialAccountTransactions

      def instant_payouts_promotion: () -> InstantPayoutsPromotion

      def issuing_card: () -> IssuingCard

      def issuing_cards_list: () -> IssuingCardsList

      def notification_banner: () -> NotificationBanner

      def payment_details: () -> PaymentDetails

      def payment_disputes: () -> PaymentDisputes

      def payment_method_settings: () -> PaymentMethodSettings

      def payments: () -> Payments

      def payout_details: () -> PayoutDetails

      def payout_reconciliation_report: () -> PayoutReconciliationReport

      def payouts: () -> Payouts

      def payouts_list: () -> PayoutsList

      def tax_registrations: () -> TaxRegistrations

      def tax_settings: () -> TaxSettings
    end

    def account: () -> String

    def client_secret: () -> String

    def components: () -> Components

    def expires_at: () -> Integer

    def livemode: () -> bool

    def object: () -> String

    def self.create: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::AccountSession
  end
end
