module Stripe
  class Account < APIResource
    class BusinessProfile < ::Stripe::StripeObject
      class AnnualRevenue < ::Stripe::StripeObject
        def amount: () -> Integer?

        def currency: () -> String?

        def fiscal_year_end: () -> String?
      end

      class MonthlyEstimatedRevenue < ::Stripe::StripeObject
        def amount: () -> Integer

        def currency: () -> String
      end

      class SupportAddress < ::Stripe::StripeObject
        def city: () -> String?

        def country: () -> String?

        def line1: () -> String?

        def line2: () -> String?

        def postal_code: () -> String?

        def state: () -> String?
      end

      def annual_revenue: () -> AnnualRevenue?

      def estimated_worker_count: () -> Integer?

      def mcc: () -> String?

      def minority_owned_business_designation: () -> ::Array[String]?

      def monthly_estimated_revenue: () -> MonthlyEstimatedRevenue?

      def name: () -> String?

      def product_description: () -> String?

      def specified_commercial_transactions_act_url: () -> String?

      def support_address: () -> SupportAddress?

      def support_email: () -> String?

      def support_phone: () -> String?

      def support_url: () -> String?

      def url: () -> String?
    end

    class Capabilities < ::Stripe::StripeObject
      def acss_debit_payments: () -> String?

      def affirm_payments: () -> String?

      def afterpay_clearpay_payments: () -> String?

      def alma_payments: () -> String?

      def amazon_pay_payments: () -> String?

      def app_distribution: () -> String?

      def au_becs_debit_payments: () -> String?

      def bacs_debit_payments: () -> String?

      def bancontact_payments: () -> String?

      def bank_transfer_payments: () -> String?

      def billie_payments: () -> String?

      def bizum_payments: () -> String?

      def blik_payments: () -> String?

      def blik_recurring_payments: () -> String?

      def boleto_payments: () -> String?

      def card_issuing: () -> String?

      def card_payments: () -> String?

      def cartes_bancaires_payments: () -> String?

      def cashapp_payments: () -> String?

      def crypto_payments: () -> String?

      def eps_payments: () -> String?

      def fpx_payments: () -> String?

      def gb_bank_transfer_payments: () -> String?

      def giropay_payments: () -> String?

      def grabpay_payments: () -> String?

      def ideal_payments: () -> String?

      def india_international_payments: () -> String?

      def jcb_payments: () -> String?

      def jp_bank_transfer_payments: () -> String?

      def kakao_pay_payments: () -> String?

      def klarna_payments: () -> String?

      def konbini_payments: () -> String?

      def kr_card_payments: () -> String?

      def legacy_payments: () -> String?

      def link_payments: () -> String?

      def mb_way_payments: () -> String?

      def mobilepay_payments: () -> String?

      def multibanco_payments: () -> String?

      def mx_bank_transfer_payments: () -> String?

      def naver_pay_payments: () -> String?

      def nz_bank_account_becs_debit_payments: () -> String?

      def oxxo_payments: () -> String?

      def p24_payments: () -> String?

      def pay_by_bank_payments: () -> String?

      def payco_payments: () -> String?

      def paynow_payments: () -> String?

      def paypay_payments: () -> String?

      def payto_payments: () -> String?

      def pix_payments: () -> String?

      def promptpay_payments: () -> String?

      def revolut_pay_payments: () -> String?

      def samsung_pay_payments: () -> String?

      def satispay_payments: () -> String?

      def scalapay_payments: () -> String?

      def sepa_bank_transfer_payments: () -> String?

      def sepa_debit_payments: () -> String?

      def sequra_payments: () -> String?

      def sofort_payments: () -> String?

      def sunbit_payments: () -> String?

      def swish_payments: () -> String?

      def tax_reporting_us_1099_k: () -> String?

      def tax_reporting_us_1099_misc: () -> String?

      def transfers: () -> String?

      def treasury: () -> String?

      def twint_payments: () -> String?

      def upi_payments: () -> String?

      def us_bank_account_ach_payments: () -> String?

      def us_bank_transfer_payments: () -> String?

      def zip_payments: () -> String?
    end

    class Company < ::Stripe::StripeObject
      class Address < ::Stripe::StripeObject
        def city: () -> String?

        def country: () -> String?

        def line1: () -> String?

        def line2: () -> String?

        def postal_code: () -> String?

        def state: () -> String?
      end

      class AddressKana < ::Stripe::StripeObject
        def city: () -> String?

        def country: () -> String?

        def line1: () -> String?

        def line2: () -> String?

        def postal_code: () -> String?

        def state: () -> String?

        def town: () -> String?
      end

      class AddressKanji < ::Stripe::StripeObject
        def city: () -> String?

        def country: () -> String?

        def line1: () -> String?

        def line2: () -> String?

        def postal_code: () -> String?

        def state: () -> String?

        def town: () -> String?
      end

      class AdministrativeAddress < ::Stripe::StripeObject
        def city: () -> String?

        def country: () -> String?

        def line1: () -> String?

        def line2: () -> String?

        def postal_code: () -> String?

        def state: () -> String?
      end

      class DirectorshipDeclaration < ::Stripe::StripeObject
        def date: () -> Integer?

        def ip: () -> String?

        def user_agent: () -> String?
      end

      class OwnershipDeclaration < ::Stripe::StripeObject
        def date: () -> Integer?

        def ip: () -> String?

        def user_agent: () -> String?
      end

      class PrincipalPlaceOfBusiness < ::Stripe::StripeObject
        def city: () -> String?

        def country: () -> String?

        def line1: () -> String?

        def line2: () -> String?

        def postal_code: () -> String?

        def state: () -> String?
      end

      class RegistrationDate < ::Stripe::StripeObject
        def day: () -> Integer?

        def month: () -> Integer?

        def year: () -> Integer?
      end

      class RepresentativeDeclaration < ::Stripe::StripeObject
        def date: () -> Integer?

        def ip: () -> String?

        def user_agent: () -> String?
      end

      class Verification < ::Stripe::StripeObject
        class Document < ::Stripe::StripeObject
          def back: () -> (String | ::Stripe::File)?

          def details: () -> String?

          def details_code: () -> String?

          def front: () -> (String | ::Stripe::File)?
        end

        def document: () -> Document
      end

      def address: () -> Address?

      def address_kana: () -> AddressKana?

      def address_kanji: () -> AddressKanji?

      def administrative_address: () -> AdministrativeAddress?

      def directors_provided: () -> bool?

      def directorship_declaration: () -> DirectorshipDeclaration?

      def executives_provided: () -> bool?

      def export_license_id: () -> String?

      def export_purpose_code: () -> String?

      def name: () -> String?

      def name_kana: () -> String?

      def name_kanji: () -> String?

      def owners_provided: () -> bool?

      def ownership_declaration: () -> OwnershipDeclaration?

      def ownership_exemption_reason: () -> String?

      def phone: () -> String?

      def principal_place_of_business: () -> PrincipalPlaceOfBusiness?

      def registration_date: () -> RegistrationDate?

      def representative_declaration: () -> RepresentativeDeclaration?

      def structure: () -> String?

      def tax_id_provided: () -> bool?

      def tax_id_registrar: () -> String?

      def vat_id_provided: () -> bool?

      def verification: () -> Verification?
    end

    class Controller < ::Stripe::StripeObject
      class Fees < ::Stripe::StripeObject
        def payer: () -> String
      end

      class Losses < ::Stripe::StripeObject
        def payments: () -> String
      end

      class StripeDashboard < ::Stripe::StripeObject
        def type: () -> String
      end

      def fees: () -> Fees?

      def is_controller: () -> bool?

      def losses: () -> Losses?

      def requirement_collection: () -> String?

      def stripe_dashboard: () -> StripeDashboard?

      def type: () -> String
    end

    class FutureRequirements < ::Stripe::StripeObject
      class Alternative < ::Stripe::StripeObject
        def alternative_fields_due: () -> ::Array[String]

        def original_fields_due: () -> ::Array[String]
      end

      class Error < ::Stripe::StripeObject
        def code: () -> String

        def reason: () -> String

        def requirement: () -> String
      end

      def alternatives: () -> ::Array[Alternative]?

      def current_deadline: () -> Integer?

      def currently_due: () -> ::Array[String]?

      def disabled_reason: () -> String?

      def errors: () -> ::Array[Error]?

      def eventually_due: () -> ::Array[String]?

      def past_due: () -> ::Array[String]?

      def pending_verification: () -> ::Array[String]?
    end

    class Groups < ::Stripe::StripeObject
      def payments_pricing: () -> String?
    end

    class Requirements < ::Stripe::StripeObject
      class Alternative < ::Stripe::StripeObject
        def alternative_fields_due: () -> ::Array[String]

        def original_fields_due: () -> ::Array[String]
      end

      class Error < ::Stripe::StripeObject
        def code: () -> String

        def reason: () -> String

        def requirement: () -> String
      end

      def alternatives: () -> ::Array[Alternative]?

      def current_deadline: () -> Integer?

      def currently_due: () -> ::Array[String]?

      def disabled_reason: () -> String?

      def errors: () -> ::Array[Error]?

      def eventually_due: () -> ::Array[String]?

      def past_due: () -> ::Array[String]?

      def pending_verification: () -> ::Array[String]?
    end

    class Settings < ::Stripe::StripeObject
      class BacsDebitPayments < ::Stripe::StripeObject
        def display_name: () -> String?

        def service_user_number: () -> String?
      end

      class Branding < ::Stripe::StripeObject
        def icon: () -> (String | ::Stripe::File)?

        def logo: () -> (String | ::Stripe::File)?

        def primary_color: () -> String?

        def secondary_color: () -> String?
      end

      class CardIssuing < ::Stripe::StripeObject
        class TosAcceptance < ::Stripe::StripeObject
          def date: () -> Integer?

          def ip: () -> String?

          def user_agent: () -> String?
        end

        def tos_acceptance: () -> TosAcceptance?
      end

      class CardPayments < ::Stripe::StripeObject
        class DeclineOn < ::Stripe::StripeObject
          def avs_failure: () -> bool

          def cvc_failure: () -> bool
        end

        def decline_on: () -> DeclineOn?

        def statement_descriptor_prefix: () -> String?

        def statement_descriptor_prefix_kana: () -> String?

        def statement_descriptor_prefix_kanji: () -> String?
      end

      class Dashboard < ::Stripe::StripeObject
        def display_name: () -> String?

        def timezone: () -> String?
      end

      class Invoices < ::Stripe::StripeObject
        def default_account_tax_ids: () -> ::Array[String | ::Stripe::TaxId]?

        def hosted_payment_method_save: () -> String?
      end

      class Payments < ::Stripe::StripeObject
        def statement_descriptor: () -> String?

        def statement_descriptor_kana: () -> String?

        def statement_descriptor_kanji: () -> String?
      end

      class Payouts < ::Stripe::StripeObject
        class Schedule < ::Stripe::StripeObject
          def delay_days: () -> Integer

          def interval: () -> String

          def monthly_anchor: () -> Integer?

          def monthly_payout_days: () -> ::Array[Integer]?

          def weekly_anchor: () -> String?

          def weekly_payout_days: () -> ::Array[String]?
        end

        def debit_negative_balances: () -> bool

        def schedule: () -> Schedule

        def statement_descriptor: () -> String?
      end

      class PaypayPayments < ::Stripe::StripeObject
        class Site < ::Stripe::StripeObject
          class Accessible < ::Stripe::StripeObject
          end

          class InDevelopment < ::Stripe::StripeObject
            def password_provided: () -> bool?

            def username: () -> String?
          end

          class Restricted < ::Stripe::StripeObject
            def payment_flow_file: () -> String?
          end

          def accessible: () -> Accessible?

          def in_development: () -> InDevelopment?

          def restricted: () -> Restricted?

          def type: () -> String?
        end

        def additional_files: () -> ::Array[String]?

        def goods_type: () -> String?

        def site: () -> Site?
      end

      class SepaDebitPayments < ::Stripe::StripeObject
        def creditor_id: () -> String?
      end

      class Treasury < ::Stripe::StripeObject
        class TosAcceptance < ::Stripe::StripeObject
          def date: () -> Integer?

          def ip: () -> String?

          def user_agent: () -> String?
        end

        def tos_acceptance: () -> TosAcceptance?
      end

      def bacs_debit_payments: () -> BacsDebitPayments?

      def branding: () -> Branding

      def card_issuing: () -> CardIssuing?

      def card_payments: () -> CardPayments

      def dashboard: () -> Dashboard

      def invoices: () -> Invoices?

      def payments: () -> Payments

      def payouts: () -> Payouts?

      def paypay_payments: () -> PaypayPayments?

      def sepa_debit_payments: () -> SepaDebitPayments?

      def treasury: () -> Treasury?
    end

    class TosAcceptance < ::Stripe::StripeObject
      def date: () -> Integer?

      def ip: () -> String?

      def service_agreement: () -> String?

      def user_agent: () -> String?
    end

    def business_profile: () -> BusinessProfile?

    def business_type: () -> String?

    def capabilities: () -> Capabilities?

    def charges_enabled: () -> bool?

    def company: () -> Company?

    def controller: () -> Controller?

    def country: () -> String?

    def created: () -> Integer?

    def default_currency: () -> String?

    def deleted: () -> bool?

    def details_submitted: () -> bool?

    def email: () -> String?

    def external_accounts: () -> ::Stripe::ListObject[::Stripe::BankAccount | ::Stripe::Card]?

    def future_requirements: () -> FutureRequirements?

    def groups: () -> Groups?

    def id: () -> String

    def individual: () -> ::Stripe::Person?

    def metadata: () -> ::Stripe::StripeObject?

    def object: () -> String

    def payouts_enabled: () -> bool?

    def requirements: () -> Requirements?

    def settings: () -> Settings?

    def tos_acceptance: () -> TosAcceptance?

    def type: () -> String?

    def self.create: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Account

    def self.delete: (String account, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Account

    def delete: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Account

    def self.list: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::Account]

    def persons: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::Person]

    def self.persons: (String account, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::Person]

    def reject: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Account

    def self.reject: (String account, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Account

    def unreject: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Account

    def self.unreject: (String account, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Account

    def self.update: (String account, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Account
  end
end
