module Stripe
  class ApplePayDomain < APIResource
    def created: () -> Integer

    def deleted: () -> bool?

    def domain_name: () -> String

    def id: () -> String

    def livemode: () -> bool

    def object: () -> String

    def self.create: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ApplePayDomain

    def self.delete: (String domain, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ApplePayDomain

    def delete: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ApplePayDomain

    def self.list: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::ApplePayDomain]
  end
end
