module Stripe
  class ApplicationFeeRefund < APIResource
    def amount: () -> Integer

    def balance_transaction: () -> (String | ::Stripe::BalanceTransaction)?

    def created: () -> Integer

    def currency: () -> String

    def fee: () -> (String | ::Stripe::ApplicationFee)

    def id: () -> String

    def metadata: () -> ::Stripe::StripeObject?

    def object: () -> String
  end
end
