module Stripe
  class BalanceTransaction < APIResource
    class FeeDetail < ::Stripe::StripeObject
      def amount: () -> Integer

      def application: () -> String?

      def currency: () -> String

      def description: () -> String?

      def type: () -> String
    end

    def amount: () -> Integer

    def available_on: () -> Integer

    def balance_type: () -> String

    def created: () -> Integer

    def currency: () -> String

    def description: () -> String?

    def exchange_rate: () -> Float?

    def fee: () -> Integer

    def fee_details: () -> ::Array[FeeDetail]

    def id: () -> String

    def net: () -> Integer

    def object: () -> String

    def reporting_category: () -> String

    def source: () -> (String | ::Stripe::ApplicationFee | ::Stripe::Charge | ::Stripe::ConnectCollectionTransfer | ::Stripe::CustomerCashBalanceTransaction | ::Stripe::Dispute | ::Stripe::ApplicationFeeRefund | ::Stripe::Issuing::Authorization | ::Stripe::Issuing::Dispute | ::Stripe::Issuing::Transaction | ::Stripe::Payout | ::Stripe::Refund | ::Stripe::ReserveTransaction | ::Stripe::TaxDeductedAtSource | ::Stripe::Topup | ::Stripe::Transfer | ::Stripe::TransferReversal)?

    def status: () -> String

    def type: () -> String

    def self.list: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::BalanceTransaction]
  end
end
