module Stripe
  class Card < APIResource
    class Networks < ::Stripe::StripeObject
      def preferred: () -> String?
    end

    def account: () -> (String | ::Stripe::Account)?

    def address_city: () -> String?

    def address_country: () -> String?

    def address_line1: () -> String?

    def address_line1_check: () -> String?

    def address_line2: () -> String?

    def address_state: () -> String?

    def address_zip: () -> String?

    def address_zip_check: () -> String?

    def allow_redisplay: () -> String?

    def available_payout_methods: () -> ::Array[String]?

    def brand: () -> String

    def country: () -> String?

    def currency: () -> String?

    def customer: () -> (String | ::Stripe::Customer)?

    def cvc_check: () -> String?

    def default_for_currency: () -> bool?

    def deleted: () -> bool?

    def dynamic_last4: () -> String?

    def exp_month: () -> Integer

    def exp_year: () -> Integer

    def fingerprint: () -> String?

    def funding: () -> String

    def id: () -> String

    def last4: () -> String

    def metadata: () -> ::Stripe::StripeObject?

    def name: () -> String?

    def networks: () -> Networks?

    def object: () -> String

    def regulated_status: () -> String?

    def status: () -> String?

    def tokenization_method: () -> String?
  end
end
