module Stripe
  class CashBalance < APIResource
    class Settings < ::Stripe::StripeObject
      def reconciliation_mode: () -> String

      def using_merchant_default: () -> bool
    end

    def available: () -> ::Stripe::StripeObject?

    def customer: () -> String

    def customer_account: () -> String?

    def livemode: () -> bool

    def object: () -> String

    def settings: () -> Settings
  end
end
