module Stripe
  class ConnectCollectionTransfer < APIResource
    def amount: () -> Integer

    def currency: () -> String

    def destination: () -> (String | ::Stripe::Account)

    def id: () -> String

    def livemode: () -> bool

    def object: () -> String
  end
end
