module Stripe
  class CustomerBalanceTransaction < APIResource
    def amount: () -> Integer

    def checkout_session: () -> (String | ::Stripe::Checkout::Session)?

    def created: () -> Integer

    def credit_note: () -> (String | ::Stripe::CreditNote)?

    def currency: () -> String

    def customer: () -> (String | ::Stripe::Customer)

    def customer_account: () -> String?

    def description: () -> String?

    def ending_balance: () -> Integer

    def id: () -> String

    def invoice: () -> (String | ::Stripe::Invoice)?

    def livemode: () -> bool

    def metadata: () -> ::Stripe::StripeObject?

    def object: () -> String

    def type: () -> String
  end
end
