module Stripe
  class Discount < StripeObject
    class Source < ::Stripe::StripeObject
      def coupon: () -> (String | ::Stripe::Coupon)?

      def type: () -> String
    end

    def checkout_session: () -> String?

    def customer: () -> (String | ::Stripe::Customer)?

    def customer_account: () -> String?

    def deleted: () -> bool?

    def end: () -> Integer?

    def id: () -> String

    def invoice: () -> String?

    def invoice_item: () -> String?

    def object: () -> String

    def promotion_code: () -> (String | ::Stripe::PromotionCode)?

    def source: () -> Source

    def start: () -> Integer

    def subscription: () -> String?

    def subscription_item: () -> String?
  end
end
