module Stripe
  class EphemeralKey < APIResource
    def created: () -> Integer

    def expires: () -> Integer

    def id: () -> String

    def livemode: () -> bool

    def object: () -> String

    def secret: () -> String?

    def self.delete: (String key, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::EphemeralKey

    def delete: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::EphemeralKey
  end
end
