module Stripe
  class ExchangeRate < APIResource
    def id: () -> String

    def object: () -> String

    def rates: () -> ::Stripe::StripeObject

    def self.list: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::ExchangeRate]
  end
end
