module Stripe
  class FileLink < APIResource
    def created: () -> Integer

    def expired: () -> bool

    def expires_at: () -> Integer?

    def file: () -> (String | ::Stripe::File)

    def id: () -> String

    def livemode: () -> bool

    def metadata: () -> ::Stripe::StripeObject

    def object: () -> String

    def url: () -> String?

    def self.create: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::FileLink

    def self.list: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::FileLink]

    def self.update: (String link, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::FileLink
  end
end
