module Stripe
  class File < APIResource
    def created: () -> Integer

    def expires_at: () -> Integer?

    def filename: () -> String?

    def id: () -> String

    def links: () -> ::Stripe::ListObject[::Stripe::FileLink]?

    def object: () -> String

    def purpose: () -> String

    def size: () -> Integer

    def title: () -> String?

    def type: () -> String?

    def url: () -> String?

    def self.create: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::File

    def self.list: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::File]
  end
end
