module Stripe
  class FundingInstructions < APIResource
    class BankTransfer < ::Stripe::StripeObject
      class FinancialAddress < ::Stripe::StripeObject
        class Aba < ::Stripe::StripeObject
          class AccountHolderAddress < ::Stripe::StripeObject
            def city: () -> String?

            def country: () -> String?

            def line1: () -> String?

            def line2: () -> String?

            def postal_code: () -> String?

            def state: () -> String?
          end

          class BankAddress < ::Stripe::StripeObject
            def city: () -> String?

            def country: () -> String?

            def line1: () -> String?

            def line2: () -> String?

            def postal_code: () -> String?

            def state: () -> String?
          end

          def account_holder_address: () -> AccountHolderAddress

          def account_holder_name: () -> String

          def account_number: () -> String

          def account_type: () -> String

          def bank_address: () -> BankAddress

          def bank_name: () -> String

          def routing_number: () -> String
        end

        class Iban < ::Stripe::StripeObject
          class AccountHolderAddress < ::Stripe::StripeObject
            def city: () -> String?

            def country: () -> String?

            def line1: () -> String?

            def line2: () -> String?

            def postal_code: () -> String?

            def state: () -> String?
          end

          class BankAddress < ::Stripe::StripeObject
            def city: () -> String?

            def country: () -> String?

            def line1: () -> String?

            def line2: () -> String?

            def postal_code: () -> String?

            def state: () -> String?
          end

          def account_holder_address: () -> AccountHolderAddress

          def account_holder_name: () -> String

          def bank_address: () -> BankAddress

          def bic: () -> String

          def country: () -> String

          def iban: () -> String
        end

        class SortCode < ::Stripe::StripeObject
          class AccountHolderAddress < ::Stripe::StripeObject
            def city: () -> String?

            def country: () -> String?

            def line1: () -> String?

            def line2: () -> String?

            def postal_code: () -> String?

            def state: () -> String?
          end

          class BankAddress < ::Stripe::StripeObject
            def city: () -> String?

            def country: () -> String?

            def line1: () -> String?

            def line2: () -> String?

            def postal_code: () -> String?

            def state: () -> String?
          end

          def account_holder_address: () -> AccountHolderAddress

          def account_holder_name: () -> String

          def account_number: () -> String

          def bank_address: () -> BankAddress

          def sort_code: () -> String
        end

        class Spei < ::Stripe::StripeObject
          class AccountHolderAddress < ::Stripe::StripeObject
            def city: () -> String?

            def country: () -> String?

            def line1: () -> String?

            def line2: () -> String?

            def postal_code: () -> String?

            def state: () -> String?
          end

          class BankAddress < ::Stripe::StripeObject
            def city: () -> String?

            def country: () -> String?

            def line1: () -> String?

            def line2: () -> String?

            def postal_code: () -> String?

            def state: () -> String?
          end

          def account_holder_address: () -> AccountHolderAddress

          def account_holder_name: () -> String

          def bank_address: () -> BankAddress

          def bank_code: () -> String

          def bank_name: () -> String

          def clabe: () -> String
        end

        class Swift < ::Stripe::StripeObject
          class AccountHolderAddress < ::Stripe::StripeObject
            def city: () -> String?

            def country: () -> String?

            def line1: () -> String?

            def line2: () -> String?

            def postal_code: () -> String?

            def state: () -> String?
          end

          class BankAddress < ::Stripe::StripeObject
            def city: () -> String?

            def country: () -> String?

            def line1: () -> String?

            def line2: () -> String?

            def postal_code: () -> String?

            def state: () -> String?
          end

          def account_holder_address: () -> AccountHolderAddress

          def account_holder_name: () -> String

          def account_number: () -> String

          def account_type: () -> String

          def bank_address: () -> BankAddress

          def bank_name: () -> String

          def swift_code: () -> String
        end

        class Zengin < ::Stripe::StripeObject
          class AccountHolderAddress < ::Stripe::StripeObject
            def city: () -> String?

            def country: () -> String?

            def line1: () -> String?

            def line2: () -> String?

            def postal_code: () -> String?

            def state: () -> String?
          end

          class BankAddress < ::Stripe::StripeObject
            def city: () -> String?

            def country: () -> String?

            def line1: () -> String?

            def line2: () -> String?

            def postal_code: () -> String?

            def state: () -> String?
          end

          def account_holder_address: () -> AccountHolderAddress

          def account_holder_name: () -> String?

          def account_number: () -> String?

          def account_type: () -> String?

          def bank_address: () -> BankAddress

          def bank_code: () -> String?

          def bank_name: () -> String?

          def branch_code: () -> String?

          def branch_name: () -> String?
        end

        def aba: () -> Aba?

        def iban: () -> Iban?

        def sort_code: () -> SortCode?

        def spei: () -> Spei?

        def supported_networks: () -> ::Array[String]?

        def swift: () -> Swift?

        def type: () -> String

        def zengin: () -> Zengin?
      end

      def country: () -> String

      def financial_addresses: () -> ::Array[FinancialAddress]

      def type: () -> String
    end

    def bank_transfer: () -> BankTransfer

    def currency: () -> String

    def funding_type: () -> String

    def livemode: () -> bool

    def object: () -> String
  end
end
