module Stripe
  class InvoiceRenderingTemplate < APIResource
    def created: () -> Integer

    def id: () -> String

    def livemode: () -> bool

    def metadata: () -> ::Stripe::StripeObject?

    def nickname: () -> String?

    def object: () -> String

    def status: () -> String

    def version: () -> Integer

    def archive: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::InvoiceRenderingTemplate

    def self.archive: (String template, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::InvoiceRenderingTemplate

    def self.list: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::InvoiceRenderingTemplate]

    def unarchive: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::InvoiceRenderingTemplate

    def self.unarchive: (String template, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::InvoiceRenderingTemplate
  end
end
