module Stripe
  class PaymentMethodConfiguration < APIResource
    class AcssDebit < ::Stripe::StripeObject
      class DisplayPreference < ::Stripe::StripeObject
        def overridable: () -> bool?

        def preference: () -> String

        def value: () -> String
      end

      def available: () -> bool

      def display_preference: () -> DisplayPreference
    end

    class Affirm < ::Stripe::StripeObject
      class DisplayPreference < ::Stripe::StripeObject
        def overridable: () -> bool?

        def preference: () -> String

        def value: () -> String
      end

      def available: () -> bool

      def display_preference: () -> DisplayPreference
    end

    class AfterpayClearpay < ::Stripe::StripeObject
      class DisplayPreference < ::Stripe::StripeObject
        def overridable: () -> bool?

        def preference: () -> String

        def value: () -> String
      end

      def available: () -> bool

      def display_preference: () -> DisplayPreference
    end

    class Alipay < ::Stripe::StripeObject
      class DisplayPreference < ::Stripe::StripeObject
        def overridable: () -> bool?

        def preference: () -> String

        def value: () -> String
      end

      def available: () -> bool

      def display_preference: () -> DisplayPreference
    end

    class Alma < ::Stripe::StripeObject
      class DisplayPreference < ::Stripe::StripeObject
        def overridable: () -> bool?

        def preference: () -> String

        def value: () -> String
      end

      def available: () -> bool

      def display_preference: () -> DisplayPreference
    end

    class AmazonPay < ::Stripe::StripeObject
      class DisplayPreference < ::Stripe::StripeObject
        def overridable: () -> bool?

        def preference: () -> String

        def value: () -> String
      end

      def available: () -> bool

      def display_preference: () -> DisplayPreference
    end

    class ApplePay < ::Stripe::StripeObject
      class DisplayPreference < ::Stripe::StripeObject
        def overridable: () -> bool?

        def preference: () -> String

        def value: () -> String
      end

      def available: () -> bool

      def display_preference: () -> DisplayPreference
    end

    class AuBecsDebit < ::Stripe::StripeObject
      class DisplayPreference < ::Stripe::StripeObject
        def overridable: () -> bool?

        def preference: () -> String

        def value: () -> String
      end

      def available: () -> bool

      def display_preference: () -> DisplayPreference
    end

    class BacsDebit < ::Stripe::StripeObject
      class DisplayPreference < ::Stripe::StripeObject
        def overridable: () -> bool?

        def preference: () -> String

        def value: () -> String
      end

      def available: () -> bool

      def display_preference: () -> DisplayPreference
    end

    class Bancontact < ::Stripe::StripeObject
      class DisplayPreference < ::Stripe::StripeObject
        def overridable: () -> bool?

        def preference: () -> String

        def value: () -> String
      end

      def available: () -> bool

      def display_preference: () -> DisplayPreference
    end

    class Billie < ::Stripe::StripeObject
      class DisplayPreference < ::Stripe::StripeObject
        def overridable: () -> bool?

        def preference: () -> String

        def value: () -> String
      end

      def available: () -> bool

      def display_preference: () -> DisplayPreference
    end

    class Bizum < ::Stripe::StripeObject
      class DisplayPreference < ::Stripe::StripeObject
        def overridable: () -> bool?

        def preference: () -> String

        def value: () -> String
      end

      def available: () -> bool

      def display_preference: () -> DisplayPreference
    end

    class Blik < ::Stripe::StripeObject
      class DisplayPreference < ::Stripe::StripeObject
        def overridable: () -> bool?

        def preference: () -> String

        def value: () -> String
      end

      def available: () -> bool

      def display_preference: () -> DisplayPreference
    end

    class Boleto < ::Stripe::StripeObject
      class DisplayPreference < ::Stripe::StripeObject
        def overridable: () -> bool?

        def preference: () -> String

        def value: () -> String
      end

      def available: () -> bool

      def display_preference: () -> DisplayPreference
    end

    class Card < ::Stripe::StripeObject
      class DisplayPreference < ::Stripe::StripeObject
        def overridable: () -> bool?

        def preference: () -> String

        def value: () -> String
      end

      def available: () -> bool

      def display_preference: () -> DisplayPreference
    end

    class CartesBancaires < ::Stripe::StripeObject
      class DisplayPreference < ::Stripe::StripeObject
        def overridable: () -> bool?

        def preference: () -> String

        def value: () -> String
      end

      def available: () -> bool

      def display_preference: () -> DisplayPreference
    end

    class Cashapp < ::Stripe::StripeObject
      class DisplayPreference < ::Stripe::StripeObject
        def overridable: () -> bool?

        def preference: () -> String

        def value: () -> String
      end

      def available: () -> bool

      def display_preference: () -> DisplayPreference
    end

    class Crypto < ::Stripe::StripeObject
      class DisplayPreference < ::Stripe::StripeObject
        def overridable: () -> bool?

        def preference: () -> String

        def value: () -> String
      end

      def available: () -> bool

      def display_preference: () -> DisplayPreference
    end

    class CustomerBalance < ::Stripe::StripeObject
      class DisplayPreference < ::Stripe::StripeObject
        def overridable: () -> bool?

        def preference: () -> String

        def value: () -> String
      end

      def available: () -> bool

      def display_preference: () -> DisplayPreference
    end

    class Eps < ::Stripe::StripeObject
      class DisplayPreference < ::Stripe::StripeObject
        def overridable: () -> bool?

        def preference: () -> String

        def value: () -> String
      end

      def available: () -> bool

      def display_preference: () -> DisplayPreference
    end

    class Fpx < ::Stripe::StripeObject
      class DisplayPreference < ::Stripe::StripeObject
        def overridable: () -> bool?

        def preference: () -> String

        def value: () -> String
      end

      def available: () -> bool

      def display_preference: () -> DisplayPreference
    end

    class Giropay < ::Stripe::StripeObject
      class DisplayPreference < ::Stripe::StripeObject
        def overridable: () -> bool?

        def preference: () -> String

        def value: () -> String
      end

      def available: () -> bool

      def display_preference: () -> DisplayPreference
    end

    class GooglePay < ::Stripe::StripeObject
      class DisplayPreference < ::Stripe::StripeObject
        def overridable: () -> bool?

        def preference: () -> String

        def value: () -> String
      end

      def available: () -> bool

      def display_preference: () -> DisplayPreference
    end

    class Grabpay < ::Stripe::StripeObject
      class DisplayPreference < ::Stripe::StripeObject
        def overridable: () -> bool?

        def preference: () -> String

        def value: () -> String
      end

      def available: () -> bool

      def display_preference: () -> DisplayPreference
    end

    class Ideal < ::Stripe::StripeObject
      class DisplayPreference < ::Stripe::StripeObject
        def overridable: () -> bool?

        def preference: () -> String

        def value: () -> String
      end

      def available: () -> bool

      def display_preference: () -> DisplayPreference
    end

    class Jcb < ::Stripe::StripeObject
      class DisplayPreference < ::Stripe::StripeObject
        def overridable: () -> bool?

        def preference: () -> String

        def value: () -> String
      end

      def available: () -> bool

      def display_preference: () -> DisplayPreference
    end

    class KakaoPay < ::Stripe::StripeObject
      class DisplayPreference < ::Stripe::StripeObject
        def overridable: () -> bool?

        def preference: () -> String

        def value: () -> String
      end

      def available: () -> bool

      def display_preference: () -> DisplayPreference
    end

    class Klarna < ::Stripe::StripeObject
      class DisplayPreference < ::Stripe::StripeObject
        def overridable: () -> bool?

        def preference: () -> String

        def value: () -> String
      end

      def available: () -> bool

      def display_preference: () -> DisplayPreference
    end

    class Konbini < ::Stripe::StripeObject
      class DisplayPreference < ::Stripe::StripeObject
        def overridable: () -> bool?

        def preference: () -> String

        def value: () -> String
      end

      def available: () -> bool

      def display_preference: () -> DisplayPreference
    end

    class KrCard < ::Stripe::StripeObject
      class DisplayPreference < ::Stripe::StripeObject
        def overridable: () -> bool?

        def preference: () -> String

        def value: () -> String
      end

      def available: () -> bool

      def display_preference: () -> DisplayPreference
    end

    class Link < ::Stripe::StripeObject
      class DisplayPreference < ::Stripe::StripeObject
        def overridable: () -> bool?

        def preference: () -> String

        def value: () -> String
      end

      def available: () -> bool

      def display_preference: () -> DisplayPreference
    end

    class MbWay < ::Stripe::StripeObject
      class DisplayPreference < ::Stripe::StripeObject
        def overridable: () -> bool?

        def preference: () -> String

        def value: () -> String
      end

      def available: () -> bool

      def display_preference: () -> DisplayPreference
    end

    class Mobilepay < ::Stripe::StripeObject
      class DisplayPreference < ::Stripe::StripeObject
        def overridable: () -> bool?

        def preference: () -> String

        def value: () -> String
      end

      def available: () -> bool

      def display_preference: () -> DisplayPreference
    end

    class Multibanco < ::Stripe::StripeObject
      class DisplayPreference < ::Stripe::StripeObject
        def overridable: () -> bool?

        def preference: () -> String

        def value: () -> String
      end

      def available: () -> bool

      def display_preference: () -> DisplayPreference
    end

    class NaverPay < ::Stripe::StripeObject
      class DisplayPreference < ::Stripe::StripeObject
        def overridable: () -> bool?

        def preference: () -> String

        def value: () -> String
      end

      def available: () -> bool

      def display_preference: () -> DisplayPreference
    end

    class NzBankAccount < ::Stripe::StripeObject
      class DisplayPreference < ::Stripe::StripeObject
        def overridable: () -> bool?

        def preference: () -> String

        def value: () -> String
      end

      def available: () -> bool

      def display_preference: () -> DisplayPreference
    end

    class Oxxo < ::Stripe::StripeObject
      class DisplayPreference < ::Stripe::StripeObject
        def overridable: () -> bool?

        def preference: () -> String

        def value: () -> String
      end

      def available: () -> bool

      def display_preference: () -> DisplayPreference
    end

    class P24 < ::Stripe::StripeObject
      class DisplayPreference < ::Stripe::StripeObject
        def overridable: () -> bool?

        def preference: () -> String

        def value: () -> String
      end

      def available: () -> bool

      def display_preference: () -> DisplayPreference
    end

    class PayByBank < ::Stripe::StripeObject
      class DisplayPreference < ::Stripe::StripeObject
        def overridable: () -> bool?

        def preference: () -> String

        def value: () -> String
      end

      def available: () -> bool

      def display_preference: () -> DisplayPreference
    end

    class Payco < ::Stripe::StripeObject
      class DisplayPreference < ::Stripe::StripeObject
        def overridable: () -> bool?

        def preference: () -> String

        def value: () -> String
      end

      def available: () -> bool

      def display_preference: () -> DisplayPreference
    end

    class Paynow < ::Stripe::StripeObject
      class DisplayPreference < ::Stripe::StripeObject
        def overridable: () -> bool?

        def preference: () -> String

        def value: () -> String
      end

      def available: () -> bool

      def display_preference: () -> DisplayPreference
    end

    class Paypal < ::Stripe::StripeObject
      class DisplayPreference < ::Stripe::StripeObject
        def overridable: () -> bool?

        def preference: () -> String

        def value: () -> String
      end

      def available: () -> bool

      def display_preference: () -> DisplayPreference
    end

    class Paypay < ::Stripe::StripeObject
      class DisplayPreference < ::Stripe::StripeObject
        def overridable: () -> bool?

        def preference: () -> String

        def value: () -> String
      end

      def available: () -> bool

      def display_preference: () -> DisplayPreference
    end

    class Payto < ::Stripe::StripeObject
      class DisplayPreference < ::Stripe::StripeObject
        def overridable: () -> bool?

        def preference: () -> String

        def value: () -> String
      end

      def available: () -> bool

      def display_preference: () -> DisplayPreference
    end

    class Pix < ::Stripe::StripeObject
      class DisplayPreference < ::Stripe::StripeObject
        def overridable: () -> bool?

        def preference: () -> String

        def value: () -> String
      end

      def available: () -> bool

      def display_preference: () -> DisplayPreference
    end

    class Promptpay < ::Stripe::StripeObject
      class DisplayPreference < ::Stripe::StripeObject
        def overridable: () -> bool?

        def preference: () -> String

        def value: () -> String
      end

      def available: () -> bool

      def display_preference: () -> DisplayPreference
    end

    class RevolutPay < ::Stripe::StripeObject
      class DisplayPreference < ::Stripe::StripeObject
        def overridable: () -> bool?

        def preference: () -> String

        def value: () -> String
      end

      def available: () -> bool

      def display_preference: () -> DisplayPreference
    end

    class SamsungPay < ::Stripe::StripeObject
      class DisplayPreference < ::Stripe::StripeObject
        def overridable: () -> bool?

        def preference: () -> String

        def value: () -> String
      end

      def available: () -> bool

      def display_preference: () -> DisplayPreference
    end

    class Satispay < ::Stripe::StripeObject
      class DisplayPreference < ::Stripe::StripeObject
        def overridable: () -> bool?

        def preference: () -> String

        def value: () -> String
      end

      def available: () -> bool

      def display_preference: () -> DisplayPreference
    end

    class Scalapay < ::Stripe::StripeObject
      class DisplayPreference < ::Stripe::StripeObject
        def overridable: () -> bool?

        def preference: () -> String

        def value: () -> String
      end

      def available: () -> bool

      def display_preference: () -> DisplayPreference
    end

    class SepaDebit < ::Stripe::StripeObject
      class DisplayPreference < ::Stripe::StripeObject
        def overridable: () -> bool?

        def preference: () -> String

        def value: () -> String
      end

      def available: () -> bool

      def display_preference: () -> DisplayPreference
    end

    class Sequra < ::Stripe::StripeObject
      class DisplayPreference < ::Stripe::StripeObject
        def overridable: () -> bool?

        def preference: () -> String

        def value: () -> String
      end

      def available: () -> bool

      def display_preference: () -> DisplayPreference
    end

    class Sofort < ::Stripe::StripeObject
      class DisplayPreference < ::Stripe::StripeObject
        def overridable: () -> bool?

        def preference: () -> String

        def value: () -> String
      end

      def available: () -> bool

      def display_preference: () -> DisplayPreference
    end

    class Sunbit < ::Stripe::StripeObject
      class DisplayPreference < ::Stripe::StripeObject
        def overridable: () -> bool?

        def preference: () -> String

        def value: () -> String
      end

      def available: () -> bool

      def display_preference: () -> DisplayPreference
    end

    class Swish < ::Stripe::StripeObject
      class DisplayPreference < ::Stripe::StripeObject
        def overridable: () -> bool?

        def preference: () -> String

        def value: () -> String
      end

      def available: () -> bool

      def display_preference: () -> DisplayPreference
    end

    class Twint < ::Stripe::StripeObject
      class DisplayPreference < ::Stripe::StripeObject
        def overridable: () -> bool?

        def preference: () -> String

        def value: () -> String
      end

      def available: () -> bool

      def display_preference: () -> DisplayPreference
    end

    class Upi < ::Stripe::StripeObject
      class DisplayPreference < ::Stripe::StripeObject
        def overridable: () -> bool?

        def preference: () -> String

        def value: () -> String
      end

      def available: () -> bool

      def display_preference: () -> DisplayPreference
    end

    class UsBankAccount < ::Stripe::StripeObject
      class DisplayPreference < ::Stripe::StripeObject
        def overridable: () -> bool?

        def preference: () -> String

        def value: () -> String
      end

      def available: () -> bool

      def display_preference: () -> DisplayPreference
    end

    class WechatPay < ::Stripe::StripeObject
      class DisplayPreference < ::Stripe::StripeObject
        def overridable: () -> bool?

        def preference: () -> String

        def value: () -> String
      end

      def available: () -> bool

      def display_preference: () -> DisplayPreference
    end

    class Zip < ::Stripe::StripeObject
      class DisplayPreference < ::Stripe::StripeObject
        def overridable: () -> bool?

        def preference: () -> String

        def value: () -> String
      end

      def available: () -> bool

      def display_preference: () -> DisplayPreference
    end

    def acss_debit: () -> AcssDebit?

    def active: () -> bool

    def affirm: () -> Affirm?

    def afterpay_clearpay: () -> AfterpayClearpay?

    def alipay: () -> Alipay?

    def alma: () -> Alma?

    def amazon_pay: () -> AmazonPay?

    def apple_pay: () -> ApplePay?

    def application: () -> String?

    def au_becs_debit: () -> AuBecsDebit?

    def bacs_debit: () -> BacsDebit?

    def bancontact: () -> Bancontact?

    def billie: () -> Billie?

    def bizum: () -> Bizum?

    def blik: () -> Blik?

    def boleto: () -> Boleto?

    def card: () -> Card?

    def cartes_bancaires: () -> CartesBancaires?

    def cashapp: () -> Cashapp?

    def crypto: () -> Crypto?

    def customer_balance: () -> CustomerBalance?

    def eps: () -> Eps?

    def fpx: () -> Fpx?

    def giropay: () -> Giropay?

    def google_pay: () -> GooglePay?

    def grabpay: () -> Grabpay?

    def id: () -> String

    def ideal: () -> Ideal?

    def is_default: () -> bool

    def jcb: () -> Jcb?

    def kakao_pay: () -> KakaoPay?

    def klarna: () -> Klarna?

    def konbini: () -> Konbini?

    def kr_card: () -> KrCard?

    def link: () -> Link?

    def livemode: () -> bool

    def mb_way: () -> MbWay?

    def mobilepay: () -> Mobilepay?

    def multibanco: () -> Multibanco?

    def name: () -> String

    def naver_pay: () -> NaverPay?

    def nz_bank_account: () -> NzBankAccount?

    def object: () -> String

    def oxxo: () -> Oxxo?

    def p24: () -> P24?

    def parent: () -> String?

    def pay_by_bank: () -> PayByBank?

    def payco: () -> Payco?

    def paynow: () -> Paynow?

    def paypal: () -> Paypal?

    def paypay: () -> Paypay?

    def payto: () -> Payto?

    def pix: () -> Pix?

    def promptpay: () -> Promptpay?

    def revolut_pay: () -> RevolutPay?

    def samsung_pay: () -> SamsungPay?

    def satispay: () -> Satispay?

    def scalapay: () -> Scalapay?

    def sepa_debit: () -> SepaDebit?

    def sequra: () -> Sequra?

    def sofort: () -> Sofort?

    def sunbit: () -> Sunbit?

    def swish: () -> Swish?

    def twint: () -> Twint?

    def upi: () -> Upi?

    def us_bank_account: () -> UsBankAccount?

    def wechat_pay: () -> WechatPay?

    def zip: () -> Zip?

    def self.create: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::PaymentMethodConfiguration

    def self.list: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::PaymentMethodConfiguration]

    def self.update: (String configuration, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::PaymentMethodConfiguration
  end
end
