module Stripe
  class PaymentMethodDomain < APIResource
    class AmazonPay < ::Stripe::StripeObject
      class StatusDetails < ::Stripe::StripeObject
        def error_message: () -> String
      end

      def status: () -> String

      def status_details: () -> StatusDetails?
    end

    class ApplePay < ::Stripe::StripeObject
      class StatusDetails < ::Stripe::StripeObject
        def error_message: () -> String
      end

      def status: () -> String

      def status_details: () -> StatusDetails?
    end

    class GooglePay < ::Stripe::StripeObject
      class StatusDetails < ::Stripe::StripeObject
        def error_message: () -> String
      end

      def status: () -> String

      def status_details: () -> StatusDetails?
    end

    class Klarna < ::Stripe::StripeObject
      class StatusDetails < ::Stripe::StripeObject
        def error_message: () -> String
      end

      def status: () -> String

      def status_details: () -> StatusDetails?
    end

    class Link < ::Stripe::StripeObject
      class StatusDetails < ::Stripe::StripeObject
        def error_message: () -> String
      end

      def status: () -> String

      def status_details: () -> StatusDetails?
    end

    class Paypal < ::Stripe::StripeObject
      class StatusDetails < ::Stripe::StripeObject
        def error_message: () -> String
      end

      def status: () -> String

      def status_details: () -> StatusDetails?
    end

    def amazon_pay: () -> AmazonPay

    def apple_pay: () -> ApplePay

    def created: () -> Integer

    def domain_name: () -> String

    def enabled: () -> bool

    def google_pay: () -> GooglePay

    def id: () -> String

    def klarna: () -> Klarna

    def link: () -> Link

    def livemode: () -> bool

    def object: () -> String

    def paypal: () -> Paypal

    def self.create: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::PaymentMethodDomain

    def self.list: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::PaymentMethodDomain]

    def self.update: (String payment_method_domain, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::PaymentMethodDomain

    def validate: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::PaymentMethodDomain

    def self.validate: (String payment_method_domain, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::PaymentMethodDomain
  end
end
