module Stripe
  class ProductFeature < APIResource
    def deleted: () -> bool?

    def entitlement_feature: () -> ::Stripe::Entitlements::Feature

    def id: () -> String

    def livemode: () -> bool

    def object: () -> String
  end
end
