module Stripe
  class Refund < APIResource
    class DestinationDetails < ::Stripe::StripeObject
      class Affirm < ::Stripe::StripeObject
      end

      class AfterpayClearpay < ::Stripe::StripeObject
      end

      class Alipay < ::Stripe::StripeObject
      end

      class Alma < ::Stripe::StripeObject
      end

      class AmazonPay < ::Stripe::StripeObject
      end

      class AuBankTransfer < ::Stripe::StripeObject
      end

      class Blik < ::Stripe::StripeObject
        def network_decline_code: () -> String?

        def reference: () -> String?

        def reference_status: () -> String?
      end

      class BrBankTransfer < ::Stripe::StripeObject
        def reference: () -> String?

        def reference_status: () -> String?
      end

      class Card < ::Stripe::StripeObject
        def reference: () -> String?

        def reference_status: () -> String?

        def reference_type: () -> String?

        def type: () -> String
      end

      class Cashapp < ::Stripe::StripeObject
      end

      class Crypto < ::Stripe::StripeObject
        def reference: () -> String?
      end

      class CustomerCashBalance < ::Stripe::StripeObject
      end

      class Eps < ::Stripe::StripeObject
      end

      class EuBankTransfer < ::Stripe::StripeObject
        def reference: () -> String?

        def reference_status: () -> String?
      end

      class GbBankTransfer < ::Stripe::StripeObject
        def reference: () -> String?

        def reference_status: () -> String?
      end

      class Giropay < ::Stripe::StripeObject
      end

      class Grabpay < ::Stripe::StripeObject
      end

      class JpBankTransfer < ::Stripe::StripeObject
        def reference: () -> String?

        def reference_status: () -> String?
      end

      class Klarna < ::Stripe::StripeObject
      end

      class MbWay < ::Stripe::StripeObject
        def reference: () -> String?

        def reference_status: () -> String?
      end

      class Multibanco < ::Stripe::StripeObject
        def reference: () -> String?

        def reference_status: () -> String?
      end

      class MxBankTransfer < ::Stripe::StripeObject
        def reference: () -> String?

        def reference_status: () -> String?
      end

      class NzBankTransfer < ::Stripe::StripeObject
      end

      class P24 < ::Stripe::StripeObject
        def reference: () -> String?

        def reference_status: () -> String?
      end

      class Paynow < ::Stripe::StripeObject
      end

      class Paypal < ::Stripe::StripeObject
        def network_decline_code: () -> String?
      end

      class Pix < ::Stripe::StripeObject
      end

      class Revolut < ::Stripe::StripeObject
      end

      class Scalapay < ::Stripe::StripeObject
      end

      class Sofort < ::Stripe::StripeObject
      end

      class Swish < ::Stripe::StripeObject
        def network_decline_code: () -> String?

        def reference: () -> String?

        def reference_status: () -> String?
      end

      class ThBankTransfer < ::Stripe::StripeObject
        def reference: () -> String?

        def reference_status: () -> String?
      end

      class Twint < ::Stripe::StripeObject
      end

      class UsBankTransfer < ::Stripe::StripeObject
        def reference: () -> String?

        def reference_status: () -> String?
      end

      class WechatPay < ::Stripe::StripeObject
      end

      class Zip < ::Stripe::StripeObject
      end

      def affirm: () -> Affirm?

      def afterpay_clearpay: () -> AfterpayClearpay?

      def alipay: () -> Alipay?

      def alma: () -> Alma?

      def amazon_pay: () -> AmazonPay?

      def au_bank_transfer: () -> AuBankTransfer?

      def blik: () -> Blik?

      def br_bank_transfer: () -> BrBankTransfer?

      def card: () -> Card?

      def cashapp: () -> Cashapp?

      def crypto: () -> Crypto?

      def customer_cash_balance: () -> CustomerCashBalance?

      def eps: () -> Eps?

      def eu_bank_transfer: () -> EuBankTransfer?

      def gb_bank_transfer: () -> GbBankTransfer?

      def giropay: () -> Giropay?

      def grabpay: () -> Grabpay?

      def jp_bank_transfer: () -> JpBankTransfer?

      def klarna: () -> Klarna?

      def mb_way: () -> MbWay?

      def multibanco: () -> Multibanco?

      def mx_bank_transfer: () -> MxBankTransfer?

      def nz_bank_transfer: () -> NzBankTransfer?

      def p24: () -> P24?

      def paynow: () -> Paynow?

      def paypal: () -> Paypal?

      def pix: () -> Pix?

      def revolut: () -> Revolut?

      def scalapay: () -> Scalapay?

      def sofort: () -> Sofort?

      def swish: () -> Swish?

      def th_bank_transfer: () -> ThBankTransfer?

      def twint: () -> Twint?

      def type: () -> String

      def us_bank_transfer: () -> UsBankTransfer?

      def wechat_pay: () -> WechatPay?

      def zip: () -> Zip?
    end

    class NextAction < ::Stripe::StripeObject
      class DisplayDetails < ::Stripe::StripeObject
        class EmailSent < ::Stripe::StripeObject
          def email_sent_at: () -> Integer

          def email_sent_to: () -> String
        end

        def email_sent: () -> EmailSent

        def expires_at: () -> Integer
      end

      def display_details: () -> DisplayDetails?

      def type: () -> String
    end

    class PresentmentDetails < ::Stripe::StripeObject
      def presentment_amount: () -> Integer

      def presentment_currency: () -> String
    end

    def amount: () -> Integer

    def balance_transaction: () -> (String | ::Stripe::BalanceTransaction)?

    def charge: () -> (String | ::Stripe::Charge)?

    def created: () -> Integer

    def currency: () -> String

    def customer: () -> (String | ::Stripe::Customer)?

    def customer_account: () -> String?

    def description: () -> String?

    def destination_details: () -> DestinationDetails?

    def failure_balance_transaction: () -> (String | ::Stripe::BalanceTransaction)?

    def failure_reason: () -> String?

    def id: () -> String

    def instructions_email: () -> String?

    def metadata: () -> ::Stripe::StripeObject?

    def next_action: () -> NextAction?

    def object: () -> String

    def payment_intent: () -> (String | ::Stripe::PaymentIntent)?

    def payment_method: () -> (String | ::Stripe::PaymentMethod)?

    def pending_reason: () -> String?

    def presentment_details: () -> PresentmentDetails?

    def reason: () -> String?

    def receipt_number: () -> String?

    def source_transfer_reversal: () -> (String | ::Stripe::TransferReversal)?

    def status: () -> String?

    def transfer_reversal: () -> (String | ::Stripe::TransferReversal)?

    def cancel: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Refund

    def self.cancel: (String refund, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Refund

    def self.create: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Refund

    def self.list: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::Refund]

    def self.update: (String refund, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Refund
  end
end
