module Stripe
  class ReserveTransaction < APIResource
    def amount: () -> Integer

    def currency: () -> String

    def description: () -> String?

    def id: () -> String

    def object: () -> String
  end
end
