module Stripe
  class Source < APIResource
    class AchCreditTransfer < ::Stripe::StripeObject
      def account_number: () -> String?

      def bank_name: () -> String?

      def fingerprint: () -> String?

      def refund_account_holder_name: () -> String?

      def refund_account_holder_type: () -> String?

      def refund_routing_number: () -> String?

      def routing_number: () -> String?

      def swift_code: () -> String?
    end

    class AchDebit < ::Stripe::StripeObject
      def bank_name: () -> String?

      def country: () -> String?

      def fingerprint: () -> String?

      def last4: () -> String?

      def routing_number: () -> String?

      def type: () -> String?
    end

    class AcssDebit < ::Stripe::StripeObject
      def bank_address_city: () -> String?

      def bank_address_line_1: () -> String?

      def bank_address_line_2: () -> String?

      def bank_address_postal_code: () -> String?

      def bank_name: () -> String?

      def category: () -> String?

      def country: () -> String?

      def fingerprint: () -> String?

      def last4: () -> String?

      def routing_number: () -> String?
    end

    class Alipay < ::Stripe::StripeObject
      def data_string: () -> String?

      def native_url: () -> String?

      def statement_descriptor: () -> String?
    end

    class AuBecsDebit < ::Stripe::StripeObject
      def bsb_number: () -> String?

      def fingerprint: () -> String?

      def last4: () -> String?
    end

    class Bancontact < ::Stripe::StripeObject
      def bank_code: () -> String?

      def bank_name: () -> String?

      def bic: () -> String?

      def iban_last4: () -> String?

      def preferred_language: () -> String?

      def statement_descriptor: () -> String?
    end

    class Card < ::Stripe::StripeObject
      def address_line1_check: () -> String?

      def address_zip_check: () -> String?

      def brand: () -> String?

      def country: () -> String?

      def cvc_check: () -> String?

      def dynamic_last4: () -> String?

      def exp_month: () -> Integer?

      def exp_year: () -> Integer?

      def fingerprint: () -> String?

      def funding: () -> String?

      def last4: () -> String?

      def name: () -> String?

      def three_d_secure: () -> String?

      def tokenization_method: () -> String?
    end

    class CardPresent < ::Stripe::StripeObject
      def application_cryptogram: () -> String?

      def application_preferred_name: () -> String?

      def authorization_code: () -> String?

      def authorization_response_code: () -> String?

      def brand: () -> String?

      def country: () -> String?

      def cvm_type: () -> String?

      def data_type: () -> String?

      def dedicated_file_name: () -> String?

      def emv_auth_data: () -> String?

      def evidence_customer_signature: () -> String?

      def evidence_transaction_certificate: () -> String?

      def exp_month: () -> Integer?

      def exp_year: () -> Integer?

      def fingerprint: () -> String?

      def funding: () -> String?

      def last4: () -> String?

      def pos_device_id: () -> String?

      def pos_entry_mode: () -> String?

      def read_method: () -> String?

      def reader: () -> String?

      def terminal_verification_results: () -> String?

      def transaction_status_information: () -> String?
    end

    class CodeVerification < ::Stripe::StripeObject
      def attempts_remaining: () -> Integer

      def status: () -> String
    end

    class Eps < ::Stripe::StripeObject
      def reference: () -> String?

      def statement_descriptor: () -> String?
    end

    class Giropay < ::Stripe::StripeObject
      def bank_code: () -> String?

      def bank_name: () -> String?

      def bic: () -> String?

      def statement_descriptor: () -> String?
    end

    class Ideal < ::Stripe::StripeObject
      def bank: () -> String?

      def bic: () -> String?

      def iban_last4: () -> String?

      def statement_descriptor: () -> String?
    end

    class Klarna < ::Stripe::StripeObject
      def background_image_url: () -> String?

      def client_token: () -> String?

      def first_name: () -> String?

      def last_name: () -> String?

      def locale: () -> String?

      def logo_url: () -> String?

      def page_title: () -> String?

      def pay_later_asset_urls_descriptive: () -> String?

      def pay_later_asset_urls_standard: () -> String?

      def pay_later_name: () -> String?

      def pay_later_redirect_url: () -> String?

      def pay_now_asset_urls_descriptive: () -> String?

      def pay_now_asset_urls_standard: () -> String?

      def pay_now_name: () -> String?

      def pay_now_redirect_url: () -> String?

      def pay_over_time_asset_urls_descriptive: () -> String?

      def pay_over_time_asset_urls_standard: () -> String?

      def pay_over_time_name: () -> String?

      def pay_over_time_redirect_url: () -> String?

      def payment_method_categories: () -> String?

      def purchase_country: () -> String?

      def purchase_type: () -> String?

      def redirect_url: () -> String?

      def shipping_delay: () -> Integer?

      def shipping_first_name: () -> String?

      def shipping_last_name: () -> String?
    end

    class Multibanco < ::Stripe::StripeObject
      def entity: () -> String?

      def reference: () -> String?

      def refund_account_holder_address_city: () -> String?

      def refund_account_holder_address_country: () -> String?

      def refund_account_holder_address_line1: () -> String?

      def refund_account_holder_address_line2: () -> String?

      def refund_account_holder_address_postal_code: () -> String?

      def refund_account_holder_address_state: () -> String?

      def refund_account_holder_name: () -> String?

      def refund_iban: () -> String?
    end

    class Owner < ::Stripe::StripeObject
      class Address < ::Stripe::StripeObject
        def city: () -> String?

        def country: () -> String?

        def line1: () -> String?

        def line2: () -> String?

        def postal_code: () -> String?

        def state: () -> String?
      end

      class VerifiedAddress < ::Stripe::StripeObject
        def city: () -> String?

        def country: () -> String?

        def line1: () -> String?

        def line2: () -> String?

        def postal_code: () -> String?

        def state: () -> String?
      end

      def address: () -> Address?

      def email: () -> String?

      def name: () -> String?

      def phone: () -> String?

      def verified_address: () -> VerifiedAddress?

      def verified_email: () -> String?

      def verified_name: () -> String?

      def verified_phone: () -> String?
    end

    class P24 < ::Stripe::StripeObject
      def reference: () -> String?
    end

    class Receiver < ::Stripe::StripeObject
      def address: () -> String?

      def amount_charged: () -> Integer

      def amount_received: () -> Integer

      def amount_returned: () -> Integer

      def refund_attributes_method: () -> String

      def refund_attributes_status: () -> String
    end

    class Redirect < ::Stripe::StripeObject
      def failure_reason: () -> String?

      def return_url: () -> String

      def status: () -> String

      def url: () -> String
    end

    class SepaDebit < ::Stripe::StripeObject
      def bank_code: () -> String?

      def branch_code: () -> String?

      def country: () -> String?

      def fingerprint: () -> String?

      def last4: () -> String?

      def mandate_reference: () -> String?

      def mandate_url: () -> String?
    end

    class Sofort < ::Stripe::StripeObject
      def bank_code: () -> String?

      def bank_name: () -> String?

      def bic: () -> String?

      def country: () -> String?

      def iban_last4: () -> String?

      def preferred_language: () -> String?

      def statement_descriptor: () -> String?
    end

    class SourceOrder < ::Stripe::StripeObject
      class Item < ::Stripe::StripeObject
        def amount: () -> Integer?

        def currency: () -> String?

        def description: () -> String?

        def parent: () -> String?

        def quantity: () -> Integer?

        def type: () -> String?
      end

      class Shipping < ::Stripe::StripeObject
        class Address < ::Stripe::StripeObject
          def city: () -> String?

          def country: () -> String?

          def line1: () -> String?

          def line2: () -> String?

          def postal_code: () -> String?

          def state: () -> String?
        end

        def address: () -> Address?

        def carrier: () -> String?

        def name: () -> String?

        def phone: () -> String?

        def tracking_number: () -> String?
      end

      def amount: () -> Integer

      def currency: () -> String

      def email: () -> String?

      def items: () -> ::Array[Item]?

      def shipping: () -> Shipping?
    end

    class ThreeDSecure < ::Stripe::StripeObject
      def address_line1_check: () -> String?

      def address_zip_check: () -> String?

      def authenticated: () -> bool?

      def brand: () -> String?

      def card: () -> String?

      def country: () -> String?

      def customer: () -> String?

      def cvc_check: () -> String?

      def dynamic_last4: () -> String?

      def exp_month: () -> Integer?

      def exp_year: () -> Integer?

      def fingerprint: () -> String?

      def funding: () -> String?

      def last4: () -> String?

      def name: () -> String?

      def three_d_secure: () -> String?

      def tokenization_method: () -> String?
    end

    class Wechat < ::Stripe::StripeObject
      def prepay_id: () -> String?

      def qr_code_url: () -> String?

      def statement_descriptor: () -> String?
    end

    def ach_credit_transfer: () -> AchCreditTransfer?

    def ach_debit: () -> AchDebit?

    def acss_debit: () -> AcssDebit?

    def alipay: () -> Alipay?

    def allow_redisplay: () -> String?

    def amount: () -> Integer?

    def au_becs_debit: () -> AuBecsDebit?

    def bancontact: () -> Bancontact?

    def card: () -> Card?

    def card_present: () -> CardPresent?

    def client_secret: () -> String

    def code_verification: () -> CodeVerification?

    def created: () -> Integer

    def currency: () -> String?

    def customer: () -> String?

    def eps: () -> Eps?

    def flow: () -> String

    def giropay: () -> Giropay?

    def id: () -> String

    def ideal: () -> Ideal?

    def klarna: () -> Klarna?

    def livemode: () -> bool

    def metadata: () -> ::Stripe::StripeObject?

    def multibanco: () -> Multibanco?

    def object: () -> String

    def owner: () -> Owner?

    def p24: () -> P24?

    def receiver: () -> Receiver?

    def redirect: () -> Redirect?

    def sepa_debit: () -> SepaDebit?

    def sofort: () -> Sofort?

    def source_order: () -> SourceOrder?

    def statement_descriptor: () -> String?

    def status: () -> String

    def three_d_secure: () -> ThreeDSecure?

    def type: () -> String

    def usage: () -> String?

    def wechat: () -> Wechat?

    def self.create: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Source

    def self.update: (String source, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Source

    def verify: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Source

    def self.verify: (String source, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Source
  end
end
