module Stripe
  class SourceTransaction < StripeObject
    class AchCreditTransfer < ::Stripe::StripeObject
      def customer_data: () -> String?

      def fingerprint: () -> String?

      def last4: () -> String?

      def routing_number: () -> String?
    end

    class ChfCreditTransfer < ::Stripe::StripeObject
      def reference: () -> String?

      def sender_address_country: () -> String?

      def sender_address_line1: () -> String?

      def sender_iban: () -> String?

      def sender_name: () -> String?
    end

    class GbpCreditTransfer < ::Stripe::StripeObject
      def fingerprint: () -> String?

      def funding_method: () -> String?

      def last4: () -> String?

      def reference: () -> String?

      def sender_account_number: () -> String?

      def sender_name: () -> String?

      def sender_sort_code: () -> String?
    end

    class PaperCheck < ::Stripe::StripeObject
      def available_at: () -> String?

      def invoices: () -> String?
    end

    class SepaCreditTransfer < ::Stripe::StripeObject
      def reference: () -> String?

      def sender_iban: () -> String?

      def sender_name: () -> String?
    end

    def ach_credit_transfer: () -> AchCreditTransfer?

    def amount: () -> Integer

    def chf_credit_transfer: () -> ChfCreditTransfer?

    def created: () -> Integer

    def currency: () -> String

    def gbp_credit_transfer: () -> GbpCreditTransfer?

    def id: () -> String

    def livemode: () -> bool

    def object: () -> String

    def paper_check: () -> PaperCheck?

    def sepa_credit_transfer: () -> SepaCreditTransfer?

    def source: () -> String

    def status: () -> String

    def type: () -> String
  end
end
