module Stripe
  class TaxCode < APIResource
    class Requirements < ::Stripe::StripeObject
      def performance_location: () -> String
    end

    def description: () -> String

    def id: () -> String

    def name: () -> String

    def object: () -> String

    def requirements: () -> Requirements?

    def self.list: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::TaxCode]
  end
end
