module Stripe
  class TaxDeductedAtSource < APIResource
    def id: () -> String

    def object: () -> String

    def period_end: () -> Integer

    def period_start: () -> Integer

    def tax_deduction_account_number: () -> String
  end
end
