module Stripe
  class TaxRate < APIResource
    class FlatAmount < ::Stripe::StripeObject
      def amount: () -> Integer

      def currency: () -> String
    end

    def active: () -> bool

    def country: () -> String?

    def created: () -> Integer

    def description: () -> String?

    def display_name: () -> String

    def effective_percentage: () -> Float?

    def flat_amount: () -> FlatAmount?

    def id: () -> String

    def inclusive: () -> bool

    def jurisdiction: () -> String?

    def jurisdiction_level: () -> String?

    def livemode: () -> bool

    def metadata: () -> ::Stripe::StripeObject?

    def object: () -> String

    def percentage: () -> Float

    def rate_type: () -> String?

    def state: () -> String?

    def tax_type: () -> String?

    def self.create: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::TaxRate

    def self.list: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::TaxRate]

    def self.update: (String tax_rate, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::TaxRate
  end
end
