module Stripe
  class Token < APIResource
    def bank_account: () -> ::Stripe::BankAccount?

    def card: () -> ::Stripe::Card?

    def client_ip: () -> String?

    def created: () -> Integer

    def id: () -> String

    def livemode: () -> bool

    def object: () -> String

    def type: () -> String

    def used: () -> bool

    def self.create: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Token
  end
end
