module Stripe
  class TransferReversal < APIResource
    def amount: () -> Integer

    def balance_transaction: () -> (String | ::Stripe::BalanceTransaction)?

    def created: () -> Integer

    def currency: () -> String

    def destination_payment_refund: () -> (String | ::Stripe::Refund)?

    def id: () -> String

    def metadata: () -> ::Stripe::StripeObject?

    def object: () -> String

    def source_refund: () -> (String | ::Stripe::Refund)?

    def transfer: () -> (String | ::Stripe::Transfer)
  end
end
