module Stripe
  class WebhookEndpoint < APIResource
    def api_version: () -> String?

    def application: () -> String?

    def created: () -> Integer

    def deleted: () -> bool?

    def description: () -> String?

    def enabled_events: () -> ::Array[String]

    def id: () -> String

    def livemode: () -> bool

    def metadata: () -> ::Stripe::StripeObject

    def object: () -> String

    def secret: () -> String?

    def status: () -> String

    def url: () -> String

    def self.create: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::WebhookEndpoint

    def self.delete: (String webhook_endpoint, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::WebhookEndpoint

    def delete: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::WebhookEndpoint

    def self.list: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::WebhookEndpoint]

    def self.update: (String webhook_endpoint, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::WebhookEndpoint
  end
end
