class YARD::CodeObjects::CodeObjectList < ::Array[untyped]
  # Creates a new object list associated with a namespace
  #
  # @param [NamespaceObject] owner the namespace the list should be associated with
  # @return [CodeObjectList]
  def initialize: (?YARD::CodeObjects::NamespaceObject owner) -> void
  # Adds a new value to the list
  #
  # @param [Base] value a code object to add
  # @return [CodeObjectList] self
  def push: (YARD::CodeObjects::Base value) -> YARD::CodeObjects::CodeObjectList
  def <<: (YARD::CodeObjects::Base value) -> YARD::CodeObjects::CodeObjectList
end
