module Zip
  DEFAULT_RESTORE_OPTIONS: { restore_ownership: bool, restore_permissions: bool, restore_times: bool }
  ZLIB_FLUSHING_STRATEGY: Integer

  def self.unicode_names: () -> bool
  def self.unicode_names=: (bool) -> bool

  def self.on_exists_proc: () -> bool
  def self.on_exists_proc=: (bool) -> bool

  def self.continue_on_exists_proc: () -> bool
  def self.continue_on_exists_proc=: (bool) -> bool

  def self.sort_entries: () -> bool
  def self.sort_entries=: (bool) -> bool

  def self.default_compression: () -> Integer
  def self.default_compression=: (Integer) -> Integer

  def self.write_zip64_support: () -> bool
  def self.write_zip64_support=: (bool) -> bool

  def self.warn_invalid_date: () -> bool
  def self.warn_invalid_date=: (bool) -> bool

  def self.case_insensitive_match: () -> bool
  def self.case_insensitive_match=: (bool) -> bool

  def self.force_entry_names_encoding: () -> String?
  def self.force_entry_names_encoding=: (String?) -> String?

  def self.validate_entry_sizes: () -> bool
  def self.validate_entry_sizes=: (bool) -> bool

  def self.setup: () { (Zip) -> void } -> void

  def self.reset!: () -> void
end
