module Zip
  extend Zip

  DEFAULT_RESTORE_OPTIONS: { restore_ownership: bool, restore_permissions: bool, restore_times: bool }
  ZLIB_FLUSHING_STRATEGY: Integer

  def unicode_names: () -> bool
  def unicode_names=: (bool) -> bool

  def on_exists_proc: () -> bool
  def on_exists_proc=: (bool) -> bool

  def continue_on_exists_proc: () -> bool
  def continue_on_exists_proc=: (bool) -> bool

  def sort_entries: () -> bool
  def sort_entries=: (bool) -> bool

  def default_compression: () -> Integer
  def default_compression=: (Integer) -> Integer

  def write_zip64_support: () -> bool
  def write_zip64_support=: (bool) -> bool

  def warn_invalid_date: () -> bool
  def warn_invalid_date=: (bool) -> bool

  def case_insensitive_match: () -> bool
  def case_insensitive_match=: (bool) -> bool

  def force_entry_names_encoding: () -> String?
  def force_entry_names_encoding=: (String?) -> String?

  def validate_entry_sizes: () -> bool
  def validate_entry_sizes=: (bool) -> bool

  def setup: () { (Zip) -> void } -> void

  def reset!: () -> void
end
