module LLHttp
  class Error < StandardError
  end

  class Parser
    def initialize: (untyped delegate, ?type: Symbol) -> void
    def reset: () -> void
    def <<: (String data) -> void
    def status_code: () -> Integer
    def http_major: () -> Integer
    def http_minor: () -> Integer
  end

  class Delegate
    def initialize: () -> void
  end
end
