module Stripe
  module Treasury
    class FinancialAccountService < StripeService
      attr_reader features: ::Stripe::Treasury::FinancialAccountFeaturesService

      def close: (String financial_account, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Treasury::FinancialAccount

      def create: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Treasury::FinancialAccount

      def list: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::Treasury::FinancialAccount]

      def retrieve: (String financial_account, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Treasury::FinancialAccount

      def update: (String financial_account, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Treasury::FinancialAccount
    end
  end
end
