module Stripe
  module Treasury
    class OutboundTransferService < StripeService
      def cancel: (String outbound_transfer, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Treasury::OutboundTransfer

      def create: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Treasury::OutboundTransfer

      def list: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::Treasury::OutboundTransfer]

      def retrieve: (String outbound_transfer, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Treasury::OutboundTransfer
    end
  end
end
