module Stripe
  module Treasury
    class TransactionService < StripeService
      def list: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::Treasury::Transaction]

      def retrieve: (String id, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Treasury::Transaction
    end
  end
end
