module ActiveDecorator
  class Decorator
    def self?.instance: () -> ActiveDecorator::Decorator
    def decorate: (untyped obj) -> untyped
  end

  module ViewContext
    def self.current: () -> (untyped | [])
  end
end
