module Roo
  module Formatters
    module CSV
      def to_csv: (?untyped? filename, ?untyped? old_separator, ?untyped? old_sheet, ?separator: ::String, ?sheet: untyped) -> untyped

      private

      # Write all cells to the csv file. File can be a filename or nil. If the
      # file argument is nil the output goes to STDOUT
      def write_csv_content: (?untyped? file, ?untyped? sheet, ?::String separator) -> (nil | untyped)

      # The content of a cell in the csv output
      def cell_to_csv: (untyped row, untyped col, untyped sheet) -> ("" | untyped)
    end
  end
end
