module Roo
  module Formatters
    module Matrix
      # returns a matrix object from the whole sheet or a rectangular area of a sheet
      def to_matrix: (?int? from_row, ?int? from_column, ?int? to_row, ?int? to_column, ?(string | int) sheet) -> untyped # TODO add type Matrix
    end
  end
end
