module Roo
  module Formatters
    module Matrix
      # returns a matrix object from the whole sheet or a rectangular area of a sheet
      def to_matrix: (?untyped? from_row, ?untyped? from_column, ?untyped? to_row, ?untyped? to_column, ?untyped sheet) -> untyped
    end
  end
end
