module Roo
  module Formatters
    module YAML
      # returns a rectangular area (default: all cells) as yaml-output
      # you can add additional attributes with the prefix parameter like:
      # oo.to_yaml({"file"=>"flightdata_2007-06-26", "sheet" => "1"})
      def to_yaml: (?Hash[_ToS, _ToS] prefix, ?Integer? from_row, ?Integer? from_column, ?Integer? to_row, ?Integer? to_column, ?String | Integer sheet) -> String
    end
  end
end
