module Roo
  module Formatters
    module YAML
      # returns a rectangular area (default: all cells) as yaml-output
      # you can add additional attributes with the prefix parameter like:
      # oo.to_yaml({"file"=>"flightdata_2007-06-26", "sheet" => "1"})
      def to_yaml: (?Hash[_ToS, _ToS] prefix, ?int? from_row, ?int? from_column, ?int? to_row, ?int? to_column, ?string | int sheet) -> string
    end
  end
end
