inherit_from: ../../.rubocop.yml

# Please specify only supported versions.
RBS/Layout:
  Enabled: true
  Include:
    - "gems/activemodel/7.1/**/*.rbs"
RBS/Lint:
  Enabled: true
  Include:
    - "gems/activemodel/7.1/**/*.rbs"
RBS/Style:
  Enabled: true
  Include:
    - "gems/activemodel/7.1/**/*.rbs"
