class AvatarUploader < CarrierWave::Uploader::Base
end

class MyUploader < CarrierWave::Uploader::Base
  include CarrierWave::RMagick
end

class ApplicationRecord < ActiveRecord::Base
end

class User < ApplicationRecord
  def avatar: () -> AvatarUploader
end
