module Mysql2
  class Client[ResultType]
    def xquery: (String sql, *untyped, as: :hash, **untyped) -> ResultAsHash
              | (String sql, *untyped, as: :array, **untyped) -> ResultAsArray
              | (String sql, *untyped, **untyped) -> ResultType
  end
end
