class Product < ActiveRecord::Base
  module RelationMethods
    def where: (?promoted: bool) -> ::Product::ActiveRecord_Relation
    def promoted: () -> ::Product::ActiveRecord_Relation
    def regular: () -> ::Product::ActiveRecord_Relation
  end
  extend RelationMethods
  class ActiveRecord_Relation < ::ActiveRecord::Relation
    include ::Product::RelationMethods
    include ::_ActiveRecord_Relation[::Product, ::Integer]
    include ::Enumerable[::Product]
  end

  extend Paranoia::ClassMethods[::Product, ::Product::ActiveRecord_Relation]
  include Paranoia::InstanceMethods[::Product]

  def requires_search_engine_update?: -> bool

  def update_document_in_search_engine: () -> void

  def remove_document_from_search_engine: () -> void
end
