module BindingOfCaller
  VERSION: String

  module BindingExtensions
    def of_caller: (Integer) -> Binding
    def callers: -> Array[Binding]
    def frame_count: -> Integer
    def frame_type: -> Symbol?
    def frame_description: -> String?
  end
end

class Binding
  include BindingOfCaller::BindingExtensions
end
