module Sidekiq
  class Embedded
    include Sidekiq::Component

    def quiet: () -> void

    def run: () -> void

    def stop: () -> void

    private

    def housekeeping: () -> void

    def initialize: (Config config) -> void
  end
end
