module Sidekiq
  module JobUtil
    def normalize_item: (Hash[string, untyped] item) -> Hash[string, untyped]

    def normalized_hash: (untyped item_class) -> Hash[string, untyped]

    def validate: (Hash[string, untyped] item) -> void

    def verify_json: (Hash[string, untyped] item) -> void

    private

    def json_unsafe?: (untyped item) -> bool

    TRANSIENT_ATTRIBUTES: ::Array[String]
  end
end
