module Sidekiq
  class RedisClientAdapter
    def new_client: () -> CompatClient

    private

    def client_opts: (Hash[Symbol, untyped] options) -> Hash[Symbol, untyped]

    def initialize: (Hash[Symbol, untyped] options) -> void

    class CompatClient
      def config: () -> Config
    end
  end
end
