module Sidekiq
  class TransactionAwareClient
    def push: (Hash[string, untyped] item) -> String

    def push_bulk: (untyped items) -> Array[String?]

    private

    def initialize: (?pool: untyped, ?config: Config) -> void
  end
end
