module Stripe
  module Apps
    class SecretService < StripeService
      def create: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Apps::Secret

      def delete_where: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Apps::Secret

      def find: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Apps::Secret

      def list: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::Apps::Secret]
    end
  end
end
