module Spreadsheet
  def self.open: (::String | ::File io_or_path, ?::String mode) ?{ (untyped) -> untyped } -> Excel::Workbook?

  class Workbook
  end

  module Excel
    class Workbook < Spreadsheet::Workbook
    end
  end
end
