class YARD::Server::DocServerSerializer < ::YARD::Serializers::FileSystemSerializer
  def initialize: (?untyped _command) -> void
  def serialized_path: (untyped object) -> untyped
  private def urlencode: (untyped name) -> untyped
end
