class YARD::Server::WebrickAdapter < ::YARD::Server::Adapter
  # Initializes a WEBrick server. If {Adapter#server_options} contains a
  # +:daemonize+ key set to true, the server will be daemonized.
  def start: () -> untyped
end
