module Zip
  class ExtraField
    class Generic
      def self.register_map: -> void

      def self.name: -> Symbol

      def initial_parse: (String binstr) -> ([Integer, String] | false)

      def suppress?: -> bool

      def to_local_bin: -> String

      def to_c_dir_bin: -> String
    end
  end
end
