module Zip
  class ExtraField
    class Unknown < ExtraField::Generic
      def initialize: -> void

      def merge: (String binstr, ?local: bool) -> void

      def to_local_bin: -> String

      def to_c_dir_bin: -> String

      def ==: (untyped other) -> bool
    end
  end
end
