module Stripe
  module V2
    module Commerce
      module ProductCatalog
        class ImportService < StripeService
          def create: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::V2::Commerce::ProductCatalogImport

          def list: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::V2::ListObject[::Stripe::V2::Commerce::ProductCatalogImport]

          def retrieve: (String id, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::V2::Commerce::ProductCatalogImport
        end
      end
    end
  end
end
