module Stripe
  module Identity
    class VerificationReportService < StripeService
      def list: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::Identity::VerificationReport]

      def retrieve: (String report, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Identity::VerificationReport
    end
  end
end
