module Stripe
  module Identity
    class VerificationSessionService < StripeService
      def cancel: (String session, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Identity::VerificationSession

      def create: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Identity::VerificationSession

      def list: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::Identity::VerificationSession]

      def redact: (String session, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Identity::VerificationSession

      def retrieve: (String session, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Identity::VerificationSession

      def update: (String session, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Identity::VerificationSession
    end
  end
end
