module Stripe
  module Reporting
    class ReportType < APIResource
      def data_available_end: () -> Integer

      def data_available_start: () -> Integer

      def default_columns: () -> ::Array[String]?

      def id: () -> String

      def livemode: () -> bool

      def name: () -> String

      def object: () -> String

      def updated: () -> Integer

      def version: () -> Integer

      def self.list: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::Reporting::ReportType]
    end
  end
end
