module Stripe
  module V2
    module Commerce
      class ProductCatalogService < StripeService
        attr_reader imports: ::Stripe::V2::Commerce::ProductCatalog::ImportService
      end
    end
  end
end
