module Stripe
  module Climate
    class Product < APIResource
      class CurrentPricesPerMetricTon < ::Stripe::StripeObject
        def amount_fees: () -> Integer

        def amount_subtotal: () -> Integer

        def amount_total: () -> Integer
      end

      def created: () -> Integer

      def current_prices_per_metric_ton: () -> ::Stripe::StripeObject

      def delivery_year: () -> Integer?

      def id: () -> String

      def livemode: () -> bool

      def metric_tons_available: () -> BigDecimal

      def name: () -> String

      def object: () -> String

      def suppliers: () -> ::Array[::Stripe::Climate::Supplier]

      def self.list: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::Climate::Product]
    end
  end
end
