module Stripe
  module Climate
    class Supplier < APIResource
      class Location < ::Stripe::StripeObject
        def city: () -> String?

        def country: () -> String

        def latitude: () -> Float?

        def longitude: () -> Float?

        def region: () -> String?
      end

      def id: () -> String

      def info_url: () -> String

      def livemode: () -> bool

      def locations: () -> ::Array[Location]

      def name: () -> String

      def object: () -> String

      def removal_pathway: () -> String

      def self.list: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::Climate::Supplier]
    end
  end
end
