module ApmTraceable
  class Configuration
    class InsufficientConfigurationError < StandardError
    end

    def adapter: () -> _Trace

    def adapter=: (String | Symbol | [String | Symbol, Hash[Symbol, untyped]] args) -> void
  end
end
