module ApmTraceable
  module Tracer
    module ClassMethods
      def trace_methods: (*String | Symbol method_names) -> void
    end

    def trace_span: (*untyped args, **untyped options) ?{ (?) -> untyped } -> untyped
  end
end
