module Stripe
  module Radar
    class EarlyFraudWarningService < StripeService
      def list: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::Radar::EarlyFraudWarning]

      def retrieve: (String early_fraud_warning, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Radar::EarlyFraudWarning
    end
  end
end
