module Stripe
  module Radar
    class ValueListService < StripeService
      def create: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Radar::ValueList

      def delete: (String value_list, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Radar::ValueList

      def list: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::Radar::ValueList]

      def retrieve: (String value_list, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Radar::ValueList

      def update: (String value_list, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Radar::ValueList
    end
  end
end
