class Integer < ::Numeric
  #   2.months # => 2 months
  def months: () -> ActiveSupport::Duration

  # Returns a Duration instance matching the number of years provided.
  #
  #   2.years # => 2 years
  def years: () -> ActiveSupport::Duration
end
