class NilClass
  def try: () { (untyped) -> untyped } -> nil
         | () { () -> untyped } -> nil
         | (Object::name method_name, *untyped args) ?{ (*untyped) -> untyped } -> nil

  def try!: () { (untyped) -> untyped } -> nil
          | () { () -> untyped } -> nil
          | (Object::name method_name, *untyped args) ?{ (*untyped) -> untyped } -> nil

end
