class Numeric
  def kilobytes: () -> self
  def megabytes: () -> self
  def gigabytes: () -> self
  def terabytes: () -> self
  def petabytes: () -> self
  def exabytes: () -> self
  def seconds: () -> ActiveSupport::Duration
  def minutes: () -> ActiveSupport::Duration
  def hours: () -> ActiveSupport::Duration
  def days: () -> ActiveSupport::Duration
  def weeks: () -> ActiveSupport::Duration
  def fortnights: () -> ActiveSupport::Duration
  def in_milliseconds: () -> self
end
