module Stripe
  module Tax
    class AssociationService < StripeService
      def find: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Tax::Association
    end
  end
end
