module Stripe
  module Tax
    class CalculationService < StripeService
      attr_reader line_items: ::Stripe::Tax::CalculationLineItemService

      def create: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Tax::Calculation

      def retrieve: (String calculation, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Tax::Calculation
    end
  end
end
