module Stripe
  module Tax
    class CalculationLineItemService < StripeService
      def list: (String calculation, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::Tax::CalculationLineItem]
    end
  end
end
