module Stripe
  module Tax
    class SettingsService < StripeService
      def retrieve: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Tax::Settings

      def update: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Tax::Settings
    end
  end
end
