module Stripe
  module Tax
    class TransactionService < StripeService
      attr_reader line_items: ::Stripe::Tax::TransactionLineItemService

      def create_from_calculation: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Tax::Transaction

      def create_reversal: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Tax::Transaction

      def retrieve: (String transaction, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Tax::Transaction
    end
  end
end
