module Stripe
  module Tax
    class TransactionLineItemService < StripeService
      def list: (String transaction, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::Tax::TransactionLineItem]
    end
  end
end
