class MyApp < Sinatra::Base
  # Methods defined in the helpers block must be recognized as instance
  # methods for method calls from within other helper blocks, and as
  # singleton methods for calls from HTTP verbs (get, post, patch, etc.).
  def self.foo: () -> String
  def foo: () -> String
  def self.bar: () -> String
  def bar: () -> String

  class HttpError < StandardError
    attr_reader code: Integer

    def initialize: (Integer) -> void
  end
end
