module ClimateControl
  def self.modify: [T] (?Hash[_ToS, String?] environment_overrides) { () -> T } -> T
  def self.unsafe_modify: [T] (?Hash[_ToS, String?] environment_overrides) { () -> T } -> T
end
