module Stripe
  module Events
    class V1AccountApplicationDeauthorizedEvent < Stripe::V2::Core::Event
      def self.lookup_type: () -> "v1.account.application.deauthorized"
    end

    class V1AccountApplicationDeauthorizedEventNotification < Stripe::V2::Core::EventNotification
      def self.lookup_type: () -> "v1.account.application.deauthorized"
    end
  end
end
