module Stripe
  module Events
    class V1BillingMeterErrorReportTriggeredEvent < Stripe::V2::Core::Event
      def self.lookup_type: () -> "v1.billing.meter.error_report_triggered"

      attr_reader data: untyped

      attr_reader related_object: untyped

      def fetch_related_object: () -> untyped
    end

    class V1BillingMeterErrorReportTriggeredEventNotification < Stripe::V2::Core::EventNotification
      def self.lookup_type: () -> "v1.billing.meter.error_report_triggered"

      attr_reader related_object: ::Stripe::V2::Core::RelatedObject

      def fetch_related_object: () -> untyped
    end
  end
end
