module Stripe
  module Events
    class V1BillingCreditGrantUpdatedEvent < Stripe::V2::Core::Event
      def self.lookup_type: () -> "v1.billing.credit_grant.updated"

      def fetch_related_object: () -> untyped

      attr_reader related_object: untyped
    end

    class V1BillingCreditGrantUpdatedEventNotification < Stripe::V2::Core::EventNotification
      def self.lookup_type: () -> "v1.billing.credit_grant.updated"

      attr_reader related_object: ::Stripe::V2::Core::RelatedObject

      def fetch_related_object: () -> untyped
    end
  end
end
