module Stripe
  module Events
    class V1CustomerTaxIdCreatedEvent < Stripe::V2::Core::Event
      def self.lookup_type: () -> "v1.customer.tax_id.created"

      def fetch_related_object: () -> untyped

      attr_reader related_object: untyped
    end

    class V1CustomerTaxIdCreatedEventNotification < Stripe::V2::Core::EventNotification
      def self.lookup_type: () -> "v1.customer.tax_id.created"

      attr_reader related_object: ::Stripe::V2::Core::RelatedObject

      def fetch_related_object: () -> untyped
    end
  end
end
