module Stripe
  module Events
    class V1CustomerDiscountUpdatedEvent < Stripe::V2::Core::Event
      def self.lookup_type: () -> "v1.customer.discount.updated"

      def fetch_related_object: () -> untyped

      attr_reader related_object: untyped
    end

    class V1CustomerDiscountUpdatedEventNotification < Stripe::V2::Core::EventNotification
      def self.lookup_type: () -> "v1.customer.discount.updated"

      attr_reader related_object: ::Stripe::V2::Core::RelatedSingletonObject

      def fetch_related_object: () -> untyped
    end
  end
end
