module Stripe
  module Events
    class V1CustomerSubscriptionResumedEvent < Stripe::V2::Core::Event
      def self.lookup_type: () -> "v1.customer.subscription.resumed"

      def fetch_related_object: () -> untyped

      attr_reader related_object: untyped
    end

    class V1CustomerSubscriptionResumedEventNotification < Stripe::V2::Core::EventNotification
      def self.lookup_type: () -> "v1.customer.subscription.resumed"

      attr_reader related_object: ::Stripe::V2::Core::RelatedObject

      def fetch_related_object: () -> untyped
    end
  end
end
