module Stripe
  module Events
    class V1FinancialConnectionsAccountSupportedPaymentMethodTypesUpdatedEvent < Stripe::V2::Core::Event
      def self.lookup_type: () -> "v1.financial_connections.account.supported_payment_method_types_updated"

      def fetch_related_object: () -> untyped

      attr_reader related_object: untyped
    end

    class V1FinancialConnectionsAccountSupportedPaymentMethodTypesUpdatedEventNotification < Stripe::V2::Core::EventNotification
      def self.lookup_type: () -> "v1.financial_connections.account.supported_payment_method_types_updated"

      attr_reader related_object: ::Stripe::V2::Core::RelatedObject

      def fetch_related_object: () -> untyped
    end
  end
end
