module Stripe
  module Events
    class V1IssuingCardholderUpdatedEvent < Stripe::V2::Core::Event
      def self.lookup_type: () -> "v1.issuing_cardholder.updated"

      def fetch_related_object: () -> untyped

      attr_reader related_object: untyped
    end

    class V1IssuingCardholderUpdatedEventNotification < Stripe::V2::Core::EventNotification
      def self.lookup_type: () -> "v1.issuing_cardholder.updated"

      attr_reader related_object: ::Stripe::V2::Core::RelatedObject

      def fetch_related_object: () -> untyped
    end
  end
end
