module Stripe
  module Events
    class V1IdentityVerificationSessionRequiresInputEvent < Stripe::V2::Core::Event
      def self.lookup_type: () -> "v1.identity.verification_session.requires_input"

      def fetch_related_object: () -> untyped

      attr_reader related_object: untyped
    end

    class V1IdentityVerificationSessionRequiresInputEventNotification < Stripe::V2::Core::EventNotification
      def self.lookup_type: () -> "v1.identity.verification_session.requires_input"

      attr_reader related_object: ::Stripe::V2::Core::RelatedObject

      def fetch_related_object: () -> untyped
    end
  end
end
