module Stripe
  module Events
    class V1RadarEarlyFraudWarningCreatedEvent < Stripe::V2::Core::Event
      def self.lookup_type: () -> "v1.radar.early_fraud_warning.created"

      def fetch_related_object: () -> untyped

      attr_reader related_object: untyped
    end

    class V1RadarEarlyFraudWarningCreatedEventNotification < Stripe::V2::Core::EventNotification
      def self.lookup_type: () -> "v1.radar.early_fraud_warning.created"

      attr_reader related_object: ::Stripe::V2::Core::RelatedObject

      def fetch_related_object: () -> untyped
    end
  end
end
