module Stripe
  module Events
    class V2CoreAccountPersonDeletedEvent < Stripe::V2::Core::Event
      def self.lookup_type: () -> "v2.core.account_person.deleted"

      attr_reader data: untyped

      attr_reader related_object: untyped

      def fetch_related_object: () -> untyped
    end

    class V2CoreAccountPersonDeletedEventNotification < Stripe::V2::Core::EventNotification
      def self.lookup_type: () -> "v2.core.account_person.deleted"

      attr_reader related_object: ::Stripe::V2::Core::RelatedObject

      def fetch_related_object: () -> untyped
    end
  end
end
