module Stripe
  module Events
    class V2CoreEventDestinationPingEvent < Stripe::V2::Core::Event
      def self.lookup_type: () -> "v2.core.event_destination.ping"

      def fetch_related_object: () -> untyped

      attr_reader related_object: untyped
    end

    class V2CoreEventDestinationPingEventNotification < Stripe::V2::Core::EventNotification
      def self.lookup_type: () -> "v2.core.event_destination.ping"

      attr_reader related_object: ::Stripe::V2::Core::RelatedObject

      def fetch_related_object: () -> untyped
    end
  end
end
