module Stripe
  module Events
    class V2CoreAccountIncludingIdentityUpdatedEvent < Stripe::V2::Core::Event
      def self.lookup_type: () -> "v2.core.account[identity].updated"

      def fetch_related_object: () -> untyped

      attr_reader related_object: untyped
    end

    class V2CoreAccountIncludingIdentityUpdatedEventNotification < Stripe::V2::Core::EventNotification
      def self.lookup_type: () -> "v2.core.account[identity].updated"

      attr_reader related_object: ::Stripe::V2::Core::RelatedObject

      def fetch_related_object: () -> untyped
    end
  end
end
