inherit_from: ../../.rubocop.yml

# Please specify only supported versions.
RBS/Layout:
  Enabled: true
  Include:
    - "gems/actionpack/7.2/**/*.rbs"
RBS/Lint:
  Enabled: true
  Include:
    - "gems/actionpack/7.2/**/*.rbs"
RBS/Style:
  Enabled: true
  Include:
    - "gems/actionpack/7.2/**/*.rbs"

