D = Steep::Diagnostic

target :test do
  check "."
  signature '.'

  repo_path "../../../"
  library "faraday"
  library "uri"
  library "forwardable"

  configure_code_diagnostics(D::Ruby.all_error)
end
