module CodeOwnership
  def self.for_file: (String) -> CodeTeams::Team?
  def self.for_team: (CodeTeams::Team | String) -> String
  def self.for_backtrace: (Array[String]?, ?excluded_teams: Array[CodeTeams::Team]) -> CodeTeams::Team?
  def self.for_class: (Class | Module) -> CodeTeams::Team?
  def self.validate!: (?autocorrect: bool, ?stage_changes: bool, files: Array[String]?) -> void
end
