module Stripe
  module V2
    module Billing
      class MeterEventAdjustment < APIResource
        class Cancel < ::Stripe::StripeObject
          def identifier: () -> String
        end

        def cancel: () -> Cancel

        def created: () -> String

        def event_name: () -> String

        def id: () -> String

        def livemode: () -> bool

        def object: () -> String

        def status: () -> String

        def type: () -> String
      end
    end
  end
end
