module Stripe
  module V2
    module Billing
      class MeterEvent < APIResource
        def created: () -> String

        def event_name: () -> String

        def identifier: () -> String

        def livemode: () -> bool

        def object: () -> String

        def payload: () -> ::Stripe::StripeObject

        def timestamp: () -> String
      end
    end
  end
end
