module Stripe
  module Sigma
    class ScheduledQueryRunService < StripeService
      def list: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::Sigma::ScheduledQueryRun]

      def retrieve: (String scheduled_query_run, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Sigma::ScheduledQueryRun
    end
  end
end
