module ActiveAdmin
  module Devise
    class SessionsController < ::Devise::SessionsController
    end
  end

  class Component < Arbre::Component
  end

  module Views
    class Panel < Component
    end

    class StatusTag < Component
    end
  end

  class Page
  end
end
