module Stripe
  module Billing
    class FeedbackOption < APIResource
      class StatusTransitions < ::Stripe::StripeObject
        def deactivated_at: () -> Integer?
      end

      def description: () -> String

      def id: () -> String

      def livemode: () -> bool

      def object: () -> String

      def status: () -> String

      def status_transitions: () -> StatusTransitions

      def self.create: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Billing::FeedbackOption

      def deactivate: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Billing::FeedbackOption

      def self.deactivate: (String id, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Billing::FeedbackOption

      def self.list: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::Billing::FeedbackOption]

      def self.update: (String id, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Billing::FeedbackOption
    end
  end
end
