module Stripe
  module Billing
    class MeterEventAdjustment < APIResource
      class Cancel < ::Stripe::StripeObject
        def identifier: () -> String?
      end

      def cancel: () -> Cancel?

      def event_name: () -> String

      def livemode: () -> bool

      def object: () -> String

      def status: () -> String

      def type: () -> String

      def self.create: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Billing::MeterEventAdjustment
    end
  end
end
