module Stripe
  module Billing
    class MeterEvent < APIResource
      def created: () -> Integer

      def event_name: () -> String

      def identifier: () -> String

      def livemode: () -> bool

      def object: () -> String

      def payload: () -> ::Stripe::StripeObject

      def timestamp: () -> Integer

      def self.create: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Billing::MeterEvent
    end
  end
end
