module Stripe
  module Billing
    class MeterEventSummary < APIResource
      def aggregated_value: () -> Float

      def end_time: () -> Integer

      def id: () -> String

      def livemode: () -> bool

      def meter: () -> String

      def object: () -> String

      def start_time: () -> Integer
    end
  end
end
