# attr_accessor in #each
class ActiveRecord::Encryption::Context
  attr_accessor key_provider: untyped
  attr_accessor key_generator: untyped
  attr_accessor cipher: untyped
  attr_accessor message_serializer: untyped
  attr_accessor encryptor: untyped
  attr_accessor frozen_encryption: untyped
end
