module AcLibraryRb
  class Convolution
    def initialize: (?Integer mod) -> void
                  | (Integer mod, Integer primitive_root) -> void

    def convolution: (Array[Integer] a, Array[Integer] b) -> Array[Integer]
  end
end
