module AcLibraryRb
  class DSU
    def initialize: (Integer n) -> void

    def merge: (Integer a, Integer b) -> void
    alias unite merge

    def same: (Integer a, Integer b) -> bool

    def leader: (Integer a) -> Integer

    def size: (Integer a) -> Integer

    def groups: () -> Array[Array[Integer]]
  end

  class UnionFind = DSU
end
