module AcLibraryRb
  class FenwickTree
    def initialize: (Integer n) -> void
                  | (Array[Integer] a) -> void

    def add: (Integer pos, Integer x) -> void

    def sum: (Integer l, Integer r) -> Integer
    def _sum: (Integer pos) -> Integer
  end
end
