module AcLibraryRb
  def pow_mod: (Integer x, Integer n, Integer mod) -> Integer
  def inv_mod: (Integer x, Integer mod) -> Integer
  def crt: (Array[Integer] r, Array[Integer] m) -> [Integer, Integer]
  def floor_sum: (Integer n, Integer m, Integer a, Integer b) -> Integer
end
