module AcLibraryRb
  class MaxFlow
    def initialize: (Integer n) -> void

    def add_edge: (Integer from, Integer to, Integer cap) -> void

    def flow: (Integer s, Integer t, ?Integer flow_limit) -> Integer

    def min_cut: (Integer s) -> Array[bool]

    def get_edge: (Integer i) -> [Integer, Integer, Integer, Integer]
    def edges: () -> Array[[Integer, Integer, Integer, Integer]]
    def change_edge: (Integer i, Integer new_cap, Integer new_flow) -> void
  end
end
