module AcLibraryRb
  class MinCostFlow
    def initialize: (Integer n) -> void

    def add_edge: (Integer from, Integer to, Integer cap, Integer cost) -> void

    def flow: (Integer s, Integer t, ?Integer flow_limit) -> Integer

    def slope: (Integer s, Integer t, ?Integer flow_limit) -> Array[[Integer, Integer]]

    def get_edge: (Integer i) -> [Integer, Integer, Integer, Integer, Integer]
    def edges: () -> Array[[Integer, Integer, Integer, Integer, Integer]]
  end
end
