module AcLibraryRb
  class PriorityQueue[T]
    def initialize: (?Array[T] array) -> void
                  | (?Array[T] array) { (T, T) -> boolish } -> void

    def push: (T x) -> void
    alias << push
    alias append push

    def pop: () -> T?
    def get: () -> T?
    alias top get

    def empty?: () -> bool
    def heap: () -> Array[T]
  end
end
