module AcLibraryRb
  class Segtree[S]
    def initialize: (Integer | Array[S] v, S e) { (S x, S y) -> S } -> void
                  | (Integer | Array[S] v, ^(S x, S y) -> S op, S e) -> void

    def set: (Integer pos, S x) -> void
    def get: (Integer pos) -> S
    def prod: (Integer l, Integer r) -> S
    def all_prod: () -> S
    def max_right: (Integer l) { (S x) -> bool } -> Integer
    def min_left: (Integer r) { (S x) -> bool } -> Integer
  end
end
