module AcLibraryRb
  interface _Comparable
    def <=>: (self, self) -> Integer
  end
  def suffix_array: (String s) -> Array[Integer]
                  | [T < _Comparable] (Array[T] a) -> Array[Integer]
                  | (Array[Integer] a, Integer upper) -> Array[Integer]

  def lcp_array: (String s, Array[Integer] sa) -> Array[Integer]

  def z_algorithm: (String s) -> Array[Integer]
                  | [T < _Comparable] (Array[T] a) -> Array[Integer]
end
