module AcLibraryRb
  class TwoSat
    def initialize: (Integer n) -> void

    def add_clause: (Integer i, Integer f, Integer j, Integer g) -> void

    def satisfiable?: () -> [Boolean, Array[Boolean]]
    alias satisfiable satisfiable?

    def answer: () -> Array[Boolean]
  end
end
