module AcLibraryRb
  class TwoSat
    def initialize: (Integer n) -> void

    def add_clause: (Integer i, bool f, Integer j, bool g) -> void

    def satisfiable?: () -> bool
    alias satisfiable satisfiable?

    def answer: () -> Array[bool?]
  end
end
