module Stripe
  module TestHelpers
    module Terminal
      class ReaderService < StripeService
        def present_payment_method: (String reader, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Terminal::Reader

        def succeed_input_collection: (String reader, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Terminal::Reader

        def timeout_input_collection: (String reader, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Terminal::Reader
      end
    end
  end
end
