class CustomAlgorithm
  def alg: () -> ::String
  def sign: (data: ::String, signing_key: untyped) -> ::String
  def valid_alg?: (String alg_to_validate) -> bool
  def verify: (data: untyped, signature: ::String, verification_key: untyped) -> bool
end
