module RuboCop
  module AST
    class ProcessedSource
      def raw_source: () -> String
      def buffer: () -> Parser::Source::Buffer
      def comments: () -> Array[Parser::Source::Comment]
    end

    module NodePattern
      module Macros
        def def_node_matcher: (Symbol, String) -> void
      end
    end
  end
end
