module Stripe
  module V2
    module Core
      class AccountPersonToken < APIResource
        def created: () -> String

        def expires_at: () -> String

        def id: () -> String

        def livemode: () -> bool

        def object: () -> String

        def used: () -> bool
      end
    end
  end
end
