module Stripe
  module V2
    module Core
      class AccountPerson < APIResource
        class AdditionalAddress < ::Stripe::StripeObject
          def city: () -> String?

          def country: () -> String?

          def line1: () -> String?

          def line2: () -> String?

          def postal_code: () -> String?

          def purpose: () -> String

          def state: () -> String?

          def town: () -> String?
        end

        class AdditionalName < ::Stripe::StripeObject
          def full_name: () -> String?

          def given_name: () -> String?

          def purpose: () -> String

          def surname: () -> String?
        end

        class AdditionalTermsOfService < ::Stripe::StripeObject
          class Account < ::Stripe::StripeObject
            def date: () -> String?

            def ip: () -> String?

            def user_agent: () -> String?
          end

          def account: () -> Account?
        end

        class Address < ::Stripe::StripeObject
          def city: () -> String?

          def country: () -> String?

          def line1: () -> String?

          def line2: () -> String?

          def postal_code: () -> String?

          def state: () -> String?

          def town: () -> String?
        end

        class DateOfBirth < ::Stripe::StripeObject
          def day: () -> Integer

          def month: () -> Integer

          def year: () -> Integer
        end

        class Documents < ::Stripe::StripeObject
          class CompanyAuthorization < ::Stripe::StripeObject
            def files: () -> ::Array[String]

            def type: () -> String
          end

          class Passport < ::Stripe::StripeObject
            def files: () -> ::Array[String]

            def type: () -> String
          end

          class PrimaryVerification < ::Stripe::StripeObject
            class FrontBack < ::Stripe::StripeObject
              def back: () -> String?

              def front: () -> String
            end

            def front_back: () -> FrontBack

            def type: () -> String
          end

          class SecondaryVerification < ::Stripe::StripeObject
            class FrontBack < ::Stripe::StripeObject
              def back: () -> String?

              def front: () -> String
            end

            def front_back: () -> FrontBack

            def type: () -> String
          end

          class Visa < ::Stripe::StripeObject
            def files: () -> ::Array[String]

            def type: () -> String
          end

          def company_authorization: () -> CompanyAuthorization?

          def passport: () -> Passport?

          def primary_verification: () -> PrimaryVerification?

          def secondary_verification: () -> SecondaryVerification?

          def visa: () -> Visa?
        end

        class IdNumber < ::Stripe::StripeObject
          def type: () -> String
        end

        class Relationship < ::Stripe::StripeObject
          def authorizer: () -> bool?

          def director: () -> bool?

          def executive: () -> bool?

          def legal_guardian: () -> bool?

          def owner: () -> bool?

          def percent_ownership: () -> BigDecimal?

          def representative: () -> bool?

          def title: () -> String?
        end

        class ScriptAddresses < ::Stripe::StripeObject
          class Kana < ::Stripe::StripeObject
            def city: () -> String?

            def country: () -> String?

            def line1: () -> String?

            def line2: () -> String?

            def postal_code: () -> String?

            def state: () -> String?

            def town: () -> String?
          end

          class Kanji < ::Stripe::StripeObject
            def city: () -> String?

            def country: () -> String?

            def line1: () -> String?

            def line2: () -> String?

            def postal_code: () -> String?

            def state: () -> String?

            def town: () -> String?
          end

          def kana: () -> Kana?

          def kanji: () -> Kanji?
        end

        class ScriptNames < ::Stripe::StripeObject
          class Kana < ::Stripe::StripeObject
            def given_name: () -> String?

            def surname: () -> String?
          end

          class Kanji < ::Stripe::StripeObject
            def given_name: () -> String?

            def surname: () -> String?
          end

          def kana: () -> Kana?

          def kanji: () -> Kanji?
        end

        def account: () -> String

        def additional_addresses: () -> ::Array[AdditionalAddress]?

        def additional_names: () -> ::Array[AdditionalName]?

        def additional_terms_of_service: () -> AdditionalTermsOfService?

        def address: () -> Address?

        def created: () -> String

        def date_of_birth: () -> DateOfBirth?

        def documents: () -> Documents?

        def email: () -> String?

        def given_name: () -> String?

        def id: () -> String

        def id_numbers: () -> ::Array[IdNumber]?

        def legal_gender: () -> String?

        def livemode: () -> bool

        def metadata: () -> ::Stripe::StripeObject?

        def nationalities: () -> ::Array[String]?

        def object: () -> String

        def phone: () -> String?

        def political_exposure: () -> String?

        def relationship: () -> Relationship?

        def script_addresses: () -> ScriptAddresses?

        def script_names: () -> ScriptNames?

        def surname: () -> String?

        def updated: () -> String
      end
    end
  end
end
