module Stripe
  module V2
    module Core
      class AccountLink < APIResource
        class UseCase < ::Stripe::StripeObject
          class AccountOnboarding < ::Stripe::StripeObject
            class CollectionOptions < ::Stripe::StripeObject
              def fields: () -> String?

              def future_requirements: () -> String?
            end

            def collection_options: () -> CollectionOptions?

            def refresh_url: () -> String

            def return_url: () -> String?
          end

          class AccountUpdate < ::Stripe::StripeObject
            class CollectionOptions < ::Stripe::StripeObject
              def fields: () -> String?

              def future_requirements: () -> String?
            end

            def collection_options: () -> CollectionOptions?

            def refresh_url: () -> String

            def return_url: () -> String?
          end

          def account_onboarding: () -> AccountOnboarding?

          def account_update: () -> AccountUpdate?

          def type: () -> String
        end

        def account: () -> String

        def created: () -> String

        def expires_at: () -> String

        def livemode: () -> bool

        def object: () -> String

        def url: () -> String

        def use_case: () -> UseCase
      end
    end
  end
end
