module Stripe
  module V2
    module Core
      class Account < APIResource
        class Configuration < ::Stripe::StripeObject
          class Customer < ::Stripe::StripeObject
            class AutomaticIndirectTax < ::Stripe::StripeObject
              class Location < ::Stripe::StripeObject
                def country: () -> String?

                def state: () -> String?
              end

              def exempt: () -> String?

              def ip_address: () -> String?

              def location: () -> Location?

              def location_source: () -> String?
            end

            class Billing < ::Stripe::StripeObject
              class Invoice < ::Stripe::StripeObject
                class CustomField < ::Stripe::StripeObject
                  def name: () -> String

                  def value: () -> String
                end

                class Rendering < ::Stripe::StripeObject
                  def amount_tax_display: () -> String?

                  def template: () -> String?
                end

                def custom_fields: () -> ::Array[CustomField]

                def footer: () -> String?

                def next_sequence: () -> Integer?

                def prefix: () -> String?

                def rendering: () -> Rendering?
              end

              def default_payment_method: () -> String?

              def invoice: () -> Invoice?
            end

            class Capabilities < ::Stripe::StripeObject
              class AutomaticIndirectTax < ::Stripe::StripeObject
                class StatusDetail < ::Stripe::StripeObject
                  def code: () -> String

                  def resolution: () -> String
                end

                def status: () -> String

                def status_details: () -> ::Array[StatusDetail]
              end

              def automatic_indirect_tax: () -> AutomaticIndirectTax?
            end

            class Shipping < ::Stripe::StripeObject
              class Address < ::Stripe::StripeObject
                def city: () -> String?

                def country: () -> String?

                def line1: () -> String?

                def line2: () -> String?

                def postal_code: () -> String?

                def state: () -> String?
              end

              def address: () -> Address?

              def name: () -> String?

              def phone: () -> String?
            end

            def applied: () -> bool

            def automatic_indirect_tax: () -> AutomaticIndirectTax?

            def billing: () -> Billing?

            def capabilities: () -> Capabilities?

            def shipping: () -> Shipping?

            def test_clock: () -> String?
          end

          class Merchant < ::Stripe::StripeObject
            class BacsDebitPayments < ::Stripe::StripeObject
              def display_name: () -> String?

              def service_user_number: () -> String?
            end

            class Branding < ::Stripe::StripeObject
              def icon: () -> String?

              def logo: () -> String?

              def primary_color: () -> String?

              def secondary_color: () -> String?
            end

            class Capabilities < ::Stripe::StripeObject
              class AchDebitPayments < ::Stripe::StripeObject
                class StatusDetail < ::Stripe::StripeObject
                  def code: () -> String

                  def resolution: () -> String
                end

                def status: () -> String

                def status_details: () -> ::Array[StatusDetail]
              end

              class AcssDebitPayments < ::Stripe::StripeObject
                class StatusDetail < ::Stripe::StripeObject
                  def code: () -> String

                  def resolution: () -> String
                end

                def status: () -> String

                def status_details: () -> ::Array[StatusDetail]
              end

              class AffirmPayments < ::Stripe::StripeObject
                class StatusDetail < ::Stripe::StripeObject
                  def code: () -> String

                  def resolution: () -> String
                end

                def status: () -> String

                def status_details: () -> ::Array[StatusDetail]
              end

              class AfterpayClearpayPayments < ::Stripe::StripeObject
                class StatusDetail < ::Stripe::StripeObject
                  def code: () -> String

                  def resolution: () -> String
                end

                def status: () -> String

                def status_details: () -> ::Array[StatusDetail]
              end

              class AlmaPayments < ::Stripe::StripeObject
                class StatusDetail < ::Stripe::StripeObject
                  def code: () -> String

                  def resolution: () -> String
                end

                def status: () -> String

                def status_details: () -> ::Array[StatusDetail]
              end

              class AmazonPayPayments < ::Stripe::StripeObject
                class StatusDetail < ::Stripe::StripeObject
                  def code: () -> String

                  def resolution: () -> String
                end

                def status: () -> String

                def status_details: () -> ::Array[StatusDetail]
              end

              class AuBecsDebitPayments < ::Stripe::StripeObject
                class StatusDetail < ::Stripe::StripeObject
                  def code: () -> String

                  def resolution: () -> String
                end

                def status: () -> String

                def status_details: () -> ::Array[StatusDetail]
              end

              class BacsDebitPayments < ::Stripe::StripeObject
                class StatusDetail < ::Stripe::StripeObject
                  def code: () -> String

                  def resolution: () -> String
                end

                def status: () -> String

                def status_details: () -> ::Array[StatusDetail]
              end

              class BancontactPayments < ::Stripe::StripeObject
                class StatusDetail < ::Stripe::StripeObject
                  def code: () -> String

                  def resolution: () -> String
                end

                def status: () -> String

                def status_details: () -> ::Array[StatusDetail]
              end

              class BlikPayments < ::Stripe::StripeObject
                class StatusDetail < ::Stripe::StripeObject
                  def code: () -> String

                  def resolution: () -> String
                end

                def status: () -> String

                def status_details: () -> ::Array[StatusDetail]
              end

              class BlikRecurringPayments < ::Stripe::StripeObject
                class StatusDetail < ::Stripe::StripeObject
                  def code: () -> String

                  def resolution: () -> String
                end

                def status: () -> String

                def status_details: () -> ::Array[StatusDetail]
              end

              class BoletoPayments < ::Stripe::StripeObject
                class StatusDetail < ::Stripe::StripeObject
                  def code: () -> String

                  def resolution: () -> String
                end

                def status: () -> String

                def status_details: () -> ::Array[StatusDetail]
              end

              class CardPayments < ::Stripe::StripeObject
                class StatusDetail < ::Stripe::StripeObject
                  def code: () -> String

                  def resolution: () -> String
                end

                def status: () -> String

                def status_details: () -> ::Array[StatusDetail]
              end

              class CartesBancairesPayments < ::Stripe::StripeObject
                class StatusDetail < ::Stripe::StripeObject
                  def code: () -> String

                  def resolution: () -> String
                end

                def status: () -> String

                def status_details: () -> ::Array[StatusDetail]
              end

              class CashappPayments < ::Stripe::StripeObject
                class StatusDetail < ::Stripe::StripeObject
                  def code: () -> String

                  def resolution: () -> String
                end

                def status: () -> String

                def status_details: () -> ::Array[StatusDetail]
              end

              class EpsPayments < ::Stripe::StripeObject
                class StatusDetail < ::Stripe::StripeObject
                  def code: () -> String

                  def resolution: () -> String
                end

                def status: () -> String

                def status_details: () -> ::Array[StatusDetail]
              end

              class FpxPayments < ::Stripe::StripeObject
                class StatusDetail < ::Stripe::StripeObject
                  def code: () -> String

                  def resolution: () -> String
                end

                def status: () -> String

                def status_details: () -> ::Array[StatusDetail]
              end

              class GbBankTransferPayments < ::Stripe::StripeObject
                class StatusDetail < ::Stripe::StripeObject
                  def code: () -> String

                  def resolution: () -> String
                end

                def status: () -> String

                def status_details: () -> ::Array[StatusDetail]
              end

              class GrabpayPayments < ::Stripe::StripeObject
                class StatusDetail < ::Stripe::StripeObject
                  def code: () -> String

                  def resolution: () -> String
                end

                def status: () -> String

                def status_details: () -> ::Array[StatusDetail]
              end

              class IdealPayments < ::Stripe::StripeObject
                class StatusDetail < ::Stripe::StripeObject
                  def code: () -> String

                  def resolution: () -> String
                end

                def status: () -> String

                def status_details: () -> ::Array[StatusDetail]
              end

              class JcbPayments < ::Stripe::StripeObject
                class StatusDetail < ::Stripe::StripeObject
                  def code: () -> String

                  def resolution: () -> String
                end

                def status: () -> String

                def status_details: () -> ::Array[StatusDetail]
              end

              class JpBankTransferPayments < ::Stripe::StripeObject
                class StatusDetail < ::Stripe::StripeObject
                  def code: () -> String

                  def resolution: () -> String
                end

                def status: () -> String

                def status_details: () -> ::Array[StatusDetail]
              end

              class KakaoPayPayments < ::Stripe::StripeObject
                class StatusDetail < ::Stripe::StripeObject
                  def code: () -> String

                  def resolution: () -> String
                end

                def status: () -> String

                def status_details: () -> ::Array[StatusDetail]
              end

              class KlarnaPayments < ::Stripe::StripeObject
                class StatusDetail < ::Stripe::StripeObject
                  def code: () -> String

                  def resolution: () -> String
                end

                def status: () -> String

                def status_details: () -> ::Array[StatusDetail]
              end

              class KonbiniPayments < ::Stripe::StripeObject
                class StatusDetail < ::Stripe::StripeObject
                  def code: () -> String

                  def resolution: () -> String
                end

                def status: () -> String

                def status_details: () -> ::Array[StatusDetail]
              end

              class KrCardPayments < ::Stripe::StripeObject
                class StatusDetail < ::Stripe::StripeObject
                  def code: () -> String

                  def resolution: () -> String
                end

                def status: () -> String

                def status_details: () -> ::Array[StatusDetail]
              end

              class LinkPayments < ::Stripe::StripeObject
                class StatusDetail < ::Stripe::StripeObject
                  def code: () -> String

                  def resolution: () -> String
                end

                def status: () -> String

                def status_details: () -> ::Array[StatusDetail]
              end

              class MobilepayPayments < ::Stripe::StripeObject
                class StatusDetail < ::Stripe::StripeObject
                  def code: () -> String

                  def resolution: () -> String
                end

                def status: () -> String

                def status_details: () -> ::Array[StatusDetail]
              end

              class MultibancoPayments < ::Stripe::StripeObject
                class StatusDetail < ::Stripe::StripeObject
                  def code: () -> String

                  def resolution: () -> String
                end

                def status: () -> String

                def status_details: () -> ::Array[StatusDetail]
              end

              class MxBankTransferPayments < ::Stripe::StripeObject
                class StatusDetail < ::Stripe::StripeObject
                  def code: () -> String

                  def resolution: () -> String
                end

                def status: () -> String

                def status_details: () -> ::Array[StatusDetail]
              end

              class NaverPayPayments < ::Stripe::StripeObject
                class StatusDetail < ::Stripe::StripeObject
                  def code: () -> String

                  def resolution: () -> String
                end

                def status: () -> String

                def status_details: () -> ::Array[StatusDetail]
              end

              class OxxoPayments < ::Stripe::StripeObject
                class StatusDetail < ::Stripe::StripeObject
                  def code: () -> String

                  def resolution: () -> String
                end

                def status: () -> String

                def status_details: () -> ::Array[StatusDetail]
              end

              class P24Payments < ::Stripe::StripeObject
                class StatusDetail < ::Stripe::StripeObject
                  def code: () -> String

                  def resolution: () -> String
                end

                def status: () -> String

                def status_details: () -> ::Array[StatusDetail]
              end

              class PayByBankPayments < ::Stripe::StripeObject
                class StatusDetail < ::Stripe::StripeObject
                  def code: () -> String

                  def resolution: () -> String
                end

                def status: () -> String

                def status_details: () -> ::Array[StatusDetail]
              end

              class PaycoPayments < ::Stripe::StripeObject
                class StatusDetail < ::Stripe::StripeObject
                  def code: () -> String

                  def resolution: () -> String
                end

                def status: () -> String

                def status_details: () -> ::Array[StatusDetail]
              end

              class PaynowPayments < ::Stripe::StripeObject
                class StatusDetail < ::Stripe::StripeObject
                  def code: () -> String

                  def resolution: () -> String
                end

                def status: () -> String

                def status_details: () -> ::Array[StatusDetail]
              end

              class PromptpayPayments < ::Stripe::StripeObject
                class StatusDetail < ::Stripe::StripeObject
                  def code: () -> String

                  def resolution: () -> String
                end

                def status: () -> String

                def status_details: () -> ::Array[StatusDetail]
              end

              class RevolutPayPayments < ::Stripe::StripeObject
                class StatusDetail < ::Stripe::StripeObject
                  def code: () -> String

                  def resolution: () -> String
                end

                def status: () -> String

                def status_details: () -> ::Array[StatusDetail]
              end

              class SamsungPayPayments < ::Stripe::StripeObject
                class StatusDetail < ::Stripe::StripeObject
                  def code: () -> String

                  def resolution: () -> String
                end

                def status: () -> String

                def status_details: () -> ::Array[StatusDetail]
              end

              class SatispayPayments < ::Stripe::StripeObject
                class StatusDetail < ::Stripe::StripeObject
                  def code: () -> String

                  def resolution: () -> String
                end

                def status: () -> String

                def status_details: () -> ::Array[StatusDetail]
              end

              class SepaBankTransferPayments < ::Stripe::StripeObject
                class StatusDetail < ::Stripe::StripeObject
                  def code: () -> String

                  def resolution: () -> String
                end

                def status: () -> String

                def status_details: () -> ::Array[StatusDetail]
              end

              class SepaDebitPayments < ::Stripe::StripeObject
                class StatusDetail < ::Stripe::StripeObject
                  def code: () -> String

                  def resolution: () -> String
                end

                def status: () -> String

                def status_details: () -> ::Array[StatusDetail]
              end

              class SequraPayments < ::Stripe::StripeObject
                class StatusDetail < ::Stripe::StripeObject
                  def code: () -> String

                  def resolution: () -> String
                end

                def status: () -> String

                def status_details: () -> ::Array[StatusDetail]
              end

              class StripeBalance < ::Stripe::StripeObject
                class Payouts < ::Stripe::StripeObject
                  class StatusDetail < ::Stripe::StripeObject
                    def code: () -> String

                    def resolution: () -> String
                  end

                  def status: () -> String

                  def status_details: () -> ::Array[StatusDetail]
                end

                def payouts: () -> Payouts?
              end

              class SunbitPayments < ::Stripe::StripeObject
                class StatusDetail < ::Stripe::StripeObject
                  def code: () -> String

                  def resolution: () -> String
                end

                def status: () -> String

                def status_details: () -> ::Array[StatusDetail]
              end

              class SwishPayments < ::Stripe::StripeObject
                class StatusDetail < ::Stripe::StripeObject
                  def code: () -> String

                  def resolution: () -> String
                end

                def status: () -> String

                def status_details: () -> ::Array[StatusDetail]
              end

              class TwintPayments < ::Stripe::StripeObject
                class StatusDetail < ::Stripe::StripeObject
                  def code: () -> String

                  def resolution: () -> String
                end

                def status: () -> String

                def status_details: () -> ::Array[StatusDetail]
              end

              class UsBankTransferPayments < ::Stripe::StripeObject
                class StatusDetail < ::Stripe::StripeObject
                  def code: () -> String

                  def resolution: () -> String
                end

                def status: () -> String

                def status_details: () -> ::Array[StatusDetail]
              end

              class ZipPayments < ::Stripe::StripeObject
                class StatusDetail < ::Stripe::StripeObject
                  def code: () -> String

                  def resolution: () -> String
                end

                def status: () -> String

                def status_details: () -> ::Array[StatusDetail]
              end

              def ach_debit_payments: () -> AchDebitPayments?

              def acss_debit_payments: () -> AcssDebitPayments?

              def affirm_payments: () -> AffirmPayments?

              def afterpay_clearpay_payments: () -> AfterpayClearpayPayments?

              def alma_payments: () -> AlmaPayments?

              def amazon_pay_payments: () -> AmazonPayPayments?

              def au_becs_debit_payments: () -> AuBecsDebitPayments?

              def bacs_debit_payments: () -> BacsDebitPayments?

              def bancontact_payments: () -> BancontactPayments?

              def blik_payments: () -> BlikPayments?

              def blik_recurring_payments: () -> BlikRecurringPayments?

              def boleto_payments: () -> BoletoPayments?

              def card_payments: () -> CardPayments?

              def cartes_bancaires_payments: () -> CartesBancairesPayments?

              def cashapp_payments: () -> CashappPayments?

              def eps_payments: () -> EpsPayments?

              def fpx_payments: () -> FpxPayments?

              def gb_bank_transfer_payments: () -> GbBankTransferPayments?

              def grabpay_payments: () -> GrabpayPayments?

              def ideal_payments: () -> IdealPayments?

              def jcb_payments: () -> JcbPayments?

              def jp_bank_transfer_payments: () -> JpBankTransferPayments?

              def kakao_pay_payments: () -> KakaoPayPayments?

              def klarna_payments: () -> KlarnaPayments?

              def konbini_payments: () -> KonbiniPayments?

              def kr_card_payments: () -> KrCardPayments?

              def link_payments: () -> LinkPayments?

              def mobilepay_payments: () -> MobilepayPayments?

              def multibanco_payments: () -> MultibancoPayments?

              def mx_bank_transfer_payments: () -> MxBankTransferPayments?

              def naver_pay_payments: () -> NaverPayPayments?

              def oxxo_payments: () -> OxxoPayments?

              def p24_payments: () -> P24Payments?

              def pay_by_bank_payments: () -> PayByBankPayments?

              def payco_payments: () -> PaycoPayments?

              def paynow_payments: () -> PaynowPayments?

              def promptpay_payments: () -> PromptpayPayments?

              def revolut_pay_payments: () -> RevolutPayPayments?

              def samsung_pay_payments: () -> SamsungPayPayments?

              def satispay_payments: () -> SatispayPayments?

              def sepa_bank_transfer_payments: () -> SepaBankTransferPayments?

              def sepa_debit_payments: () -> SepaDebitPayments?

              def sequra_payments: () -> SequraPayments?

              def stripe_balance: () -> StripeBalance?

              def sunbit_payments: () -> SunbitPayments?

              def swish_payments: () -> SwishPayments?

              def twint_payments: () -> TwintPayments?

              def us_bank_transfer_payments: () -> UsBankTransferPayments?

              def zip_payments: () -> ZipPayments?
            end

            class CardPayments < ::Stripe::StripeObject
              class DeclineOn < ::Stripe::StripeObject
                def avs_failure: () -> bool?

                def cvc_failure: () -> bool?
              end

              def decline_on: () -> DeclineOn?
            end

            class KonbiniPayments < ::Stripe::StripeObject
              class Support < ::Stripe::StripeObject
                class Hours < ::Stripe::StripeObject
                  def end_time: () -> String?

                  def start_time: () -> String?
                end

                def email: () -> String?

                def hours: () -> Hours?

                def phone: () -> String?
              end

              def support: () -> Support?
            end

            class ScriptStatementDescriptor < ::Stripe::StripeObject
              class Kana < ::Stripe::StripeObject
                def descriptor: () -> String?

                def prefix: () -> String?
              end

              class Kanji < ::Stripe::StripeObject
                def descriptor: () -> String?

                def prefix: () -> String?
              end

              def kana: () -> Kana?

              def kanji: () -> Kanji?
            end

            class SepaDebitPayments < ::Stripe::StripeObject
              def creditor_id: () -> String?
            end

            class StatementDescriptor < ::Stripe::StripeObject
              def descriptor: () -> String?

              def prefix: () -> String?
            end

            class Support < ::Stripe::StripeObject
              class Address < ::Stripe::StripeObject
                def city: () -> String?

                def country: () -> String?

                def line1: () -> String?

                def line2: () -> String?

                def postal_code: () -> String?

                def state: () -> String?

                def town: () -> String?
              end

              def address: () -> Address?

              def email: () -> String?

              def phone: () -> String?

              def url: () -> String?
            end

            def applied: () -> bool

            def bacs_debit_payments: () -> BacsDebitPayments?

            def branding: () -> Branding?

            def capabilities: () -> Capabilities?

            def card_payments: () -> CardPayments?

            def konbini_payments: () -> KonbiniPayments?

            def mcc: () -> String?

            def script_statement_descriptor: () -> ScriptStatementDescriptor?

            def sepa_debit_payments: () -> SepaDebitPayments?

            def statement_descriptor: () -> StatementDescriptor?

            def support: () -> Support?
          end

          class Recipient < ::Stripe::StripeObject
            class Capabilities < ::Stripe::StripeObject
              class StripeBalance < ::Stripe::StripeObject
                class Payouts < ::Stripe::StripeObject
                  class StatusDetail < ::Stripe::StripeObject
                    def code: () -> String

                    def resolution: () -> String
                  end

                  def status: () -> String

                  def status_details: () -> ::Array[StatusDetail]
                end

                class StripeTransfers < ::Stripe::StripeObject
                  class StatusDetail < ::Stripe::StripeObject
                    def code: () -> String

                    def resolution: () -> String
                  end

                  def status: () -> String

                  def status_details: () -> ::Array[StatusDetail]
                end

                def payouts: () -> Payouts?

                def stripe_transfers: () -> StripeTransfers?
              end

              def stripe_balance: () -> StripeBalance?
            end

            def applied: () -> bool

            def capabilities: () -> Capabilities?
          end

          def customer: () -> Customer?

          def merchant: () -> Merchant?

          def recipient: () -> Recipient?
        end

        class Defaults < ::Stripe::StripeObject
          class Profile < ::Stripe::StripeObject
            def business_url: () -> String?

            def doing_business_as: () -> String?

            def product_description: () -> String?
          end

          class Responsibilities < ::Stripe::StripeObject
            def fees_collector: () -> String?

            def losses_collector: () -> String?

            def requirements_collector: () -> String
          end

          def currency: () -> String?

          def locales: () -> ::Array[String]?

          def profile: () -> Profile?

          def responsibilities: () -> Responsibilities
        end

        class FutureRequirements < ::Stripe::StripeObject
          class Entry < ::Stripe::StripeObject
            class Error < ::Stripe::StripeObject
              def code: () -> String

              def description: () -> String
            end

            class Impact < ::Stripe::StripeObject
              class RestrictsCapability < ::Stripe::StripeObject
                class Deadline < ::Stripe::StripeObject
                  def status: () -> String
                end

                def capability: () -> String

                def configuration: () -> String

                def deadline: () -> Deadline
              end

              def restricts_capabilities: () -> ::Array[RestrictsCapability]?
            end

            class MinimumDeadline < ::Stripe::StripeObject
              def status: () -> String
            end

            class Reference < ::Stripe::StripeObject
              def inquiry: () -> String?

              def resource: () -> String?

              def type: () -> String
            end

            class RequestedReason < ::Stripe::StripeObject
              def code: () -> String
            end

            def awaiting_action_from: () -> String

            def description: () -> String

            def errors: () -> ::Array[Error]

            def impact: () -> Impact

            def minimum_deadline: () -> MinimumDeadline

            def reference: () -> Reference?

            def requested_reasons: () -> ::Array[RequestedReason]
          end

          class Summary < ::Stripe::StripeObject
            class MinimumDeadline < ::Stripe::StripeObject
              def status: () -> String

              def time: () -> String?
            end

            def minimum_deadline: () -> MinimumDeadline?
          end

          def entries: () -> ::Array[Entry]?

          def minimum_transition_date: () -> String?

          def summary: () -> Summary?
        end

        class Identity < ::Stripe::StripeObject
          class Attestations < ::Stripe::StripeObject
            class DirectorshipDeclaration < ::Stripe::StripeObject
              def date: () -> String?

              def ip: () -> String?

              def user_agent: () -> String?
            end

            class OwnershipDeclaration < ::Stripe::StripeObject
              def date: () -> String?

              def ip: () -> String?

              def user_agent: () -> String?
            end

            class PersonsProvided < ::Stripe::StripeObject
              def directors: () -> bool?

              def executives: () -> bool?

              def owners: () -> bool?

              def ownership_exemption_reason: () -> String?
            end

            class RepresentativeDeclaration < ::Stripe::StripeObject
              def date: () -> String?

              def ip: () -> String?

              def user_agent: () -> String?
            end

            class TermsOfService < ::Stripe::StripeObject
              class Account < ::Stripe::StripeObject
                def date: () -> String?

                def ip: () -> String?

                def user_agent: () -> String?
              end

              def account: () -> Account?
            end

            def directorship_declaration: () -> DirectorshipDeclaration?

            def ownership_declaration: () -> OwnershipDeclaration?

            def persons_provided: () -> PersonsProvided?

            def representative_declaration: () -> RepresentativeDeclaration?

            def terms_of_service: () -> TermsOfService?
          end

          class BusinessDetails < ::Stripe::StripeObject
            class AdditionalAddress < ::Stripe::StripeObject
              def city: () -> String?

              def country: () -> String?

              def line1: () -> String?

              def line2: () -> String?

              def postal_code: () -> String?

              def purpose: () -> String

              def state: () -> String?

              def town: () -> String?
            end

            class Address < ::Stripe::StripeObject
              def city: () -> String?

              def country: () -> String?

              def line1: () -> String?

              def line2: () -> String?

              def postal_code: () -> String?

              def state: () -> String?

              def town: () -> String?
            end

            class AnnualRevenue < ::Stripe::StripeObject
              def amount: () -> ::Stripe::V2::Amount?

              def fiscal_year_end: () -> String?
            end

            class Documents < ::Stripe::StripeObject
              class BankAccountOwnershipVerification < ::Stripe::StripeObject
                def files: () -> ::Array[String]

                def type: () -> String
              end

              class CompanyLicense < ::Stripe::StripeObject
                def files: () -> ::Array[String]

                def type: () -> String
              end

              class CompanyMemorandumOfAssociation < ::Stripe::StripeObject
                def files: () -> ::Array[String]

                def type: () -> String
              end

              class CompanyMinisterialDecree < ::Stripe::StripeObject
                def files: () -> ::Array[String]

                def type: () -> String
              end

              class CompanyRegistrationVerification < ::Stripe::StripeObject
                def files: () -> ::Array[String]

                def type: () -> String
              end

              class CompanyTaxIdVerification < ::Stripe::StripeObject
                def files: () -> ::Array[String]

                def type: () -> String
              end

              class PrimaryVerification < ::Stripe::StripeObject
                class FrontBack < ::Stripe::StripeObject
                  def back: () -> String?

                  def front: () -> String
                end

                def front_back: () -> FrontBack

                def type: () -> String
              end

              class ProofOfAddress < ::Stripe::StripeObject
                def files: () -> ::Array[String]

                def type: () -> String
              end

              class ProofOfRegistration < ::Stripe::StripeObject
                class Signer < ::Stripe::StripeObject
                  def person: () -> String
                end

                def files: () -> ::Array[String]

                def signer: () -> Signer?

                def type: () -> String
              end

              class ProofOfUltimateBeneficialOwnership < ::Stripe::StripeObject
                class Signer < ::Stripe::StripeObject
                  def person: () -> String
                end

                def files: () -> ::Array[String]

                def signer: () -> Signer?

                def type: () -> String
              end

              def bank_account_ownership_verification: () -> BankAccountOwnershipVerification?

              def company_license: () -> CompanyLicense?

              def company_memorandum_of_association: () -> CompanyMemorandumOfAssociation?

              def company_ministerial_decree: () -> CompanyMinisterialDecree?

              def company_registration_verification: () -> CompanyRegistrationVerification?

              def company_tax_id_verification: () -> CompanyTaxIdVerification?

              def primary_verification: () -> PrimaryVerification?

              def proof_of_address: () -> ProofOfAddress?

              def proof_of_registration: () -> ProofOfRegistration?

              def proof_of_ultimate_beneficial_ownership: () -> ProofOfUltimateBeneficialOwnership?
            end

            class IdNumber < ::Stripe::StripeObject
              def registrar: () -> String?

              def type: () -> String
            end

            class MonthlyEstimatedRevenue < ::Stripe::StripeObject
              def amount: () -> ::Stripe::V2::Amount?
            end

            class RegistrationDate < ::Stripe::StripeObject
              def day: () -> Integer

              def month: () -> Integer

              def year: () -> Integer
            end

            class ScriptAddresses < ::Stripe::StripeObject
              class Kana < ::Stripe::StripeObject
                def city: () -> String?

                def country: () -> String?

                def line1: () -> String?

                def line2: () -> String?

                def postal_code: () -> String?

                def state: () -> String?

                def town: () -> String?
              end

              class Kanji < ::Stripe::StripeObject
                def city: () -> String?

                def country: () -> String?

                def line1: () -> String?

                def line2: () -> String?

                def postal_code: () -> String?

                def state: () -> String?

                def town: () -> String?
              end

              def kana: () -> Kana?

              def kanji: () -> Kanji?
            end

            class ScriptNames < ::Stripe::StripeObject
              class Kana < ::Stripe::StripeObject
                def registered_name: () -> String?
              end

              class Kanji < ::Stripe::StripeObject
                def registered_name: () -> String?
              end

              def kana: () -> Kana?

              def kanji: () -> Kanji?
            end

            def additional_addresses: () -> ::Array[AdditionalAddress]?

            def address: () -> Address?

            def annual_revenue: () -> AnnualRevenue?

            def documents: () -> Documents?

            def estimated_worker_count: () -> Integer?

            def id_numbers: () -> ::Array[IdNumber]?

            def monthly_estimated_revenue: () -> MonthlyEstimatedRevenue?

            def phone: () -> String?

            def registered_name: () -> String?

            def registration_date: () -> RegistrationDate?

            def script_addresses: () -> ScriptAddresses?

            def script_names: () -> ScriptNames?

            def structure: () -> String?
          end

          class Individual < ::Stripe::StripeObject
            class AdditionalAddress < ::Stripe::StripeObject
              def city: () -> String?

              def country: () -> String?

              def line1: () -> String?

              def line2: () -> String?

              def postal_code: () -> String?

              def purpose: () -> String

              def state: () -> String?

              def town: () -> String?
            end

            class AdditionalName < ::Stripe::StripeObject
              def full_name: () -> String?

              def given_name: () -> String?

              def purpose: () -> String

              def surname: () -> String?
            end

            class AdditionalTermsOfService < ::Stripe::StripeObject
              class Account < ::Stripe::StripeObject
                def date: () -> String?

                def ip: () -> String?

                def user_agent: () -> String?
              end

              def account: () -> Account?
            end

            class Address < ::Stripe::StripeObject
              def city: () -> String?

              def country: () -> String?

              def line1: () -> String?

              def line2: () -> String?

              def postal_code: () -> String?

              def state: () -> String?

              def town: () -> String?
            end

            class DateOfBirth < ::Stripe::StripeObject
              def day: () -> Integer

              def month: () -> Integer

              def year: () -> Integer
            end

            class Documents < ::Stripe::StripeObject
              class CompanyAuthorization < ::Stripe::StripeObject
                def files: () -> ::Array[String]

                def type: () -> String
              end

              class Passport < ::Stripe::StripeObject
                def files: () -> ::Array[String]

                def type: () -> String
              end

              class PrimaryVerification < ::Stripe::StripeObject
                class FrontBack < ::Stripe::StripeObject
                  def back: () -> String?

                  def front: () -> String
                end

                def front_back: () -> FrontBack

                def type: () -> String
              end

              class SecondaryVerification < ::Stripe::StripeObject
                class FrontBack < ::Stripe::StripeObject
                  def back: () -> String?

                  def front: () -> String
                end

                def front_back: () -> FrontBack

                def type: () -> String
              end

              class Visa < ::Stripe::StripeObject
                def files: () -> ::Array[String]

                def type: () -> String
              end

              def company_authorization: () -> CompanyAuthorization?

              def passport: () -> Passport?

              def primary_verification: () -> PrimaryVerification?

              def secondary_verification: () -> SecondaryVerification?

              def visa: () -> Visa?
            end

            class IdNumber < ::Stripe::StripeObject
              def type: () -> String
            end

            class Relationship < ::Stripe::StripeObject
              def authorizer: () -> bool?

              def director: () -> bool?

              def executive: () -> bool?

              def legal_guardian: () -> bool?

              def owner: () -> bool?

              def percent_ownership: () -> BigDecimal?

              def representative: () -> bool?

              def title: () -> String?
            end

            class ScriptAddresses < ::Stripe::StripeObject
              class Kana < ::Stripe::StripeObject
                def city: () -> String?

                def country: () -> String?

                def line1: () -> String?

                def line2: () -> String?

                def postal_code: () -> String?

                def state: () -> String?

                def town: () -> String?
              end

              class Kanji < ::Stripe::StripeObject
                def city: () -> String?

                def country: () -> String?

                def line1: () -> String?

                def line2: () -> String?

                def postal_code: () -> String?

                def state: () -> String?

                def town: () -> String?
              end

              def kana: () -> Kana?

              def kanji: () -> Kanji?
            end

            class ScriptNames < ::Stripe::StripeObject
              class Kana < ::Stripe::StripeObject
                def given_name: () -> String?

                def surname: () -> String?
              end

              class Kanji < ::Stripe::StripeObject
                def given_name: () -> String?

                def surname: () -> String?
              end

              def kana: () -> Kana?

              def kanji: () -> Kanji?
            end

            def account: () -> String

            def additional_addresses: () -> ::Array[AdditionalAddress]?

            def additional_names: () -> ::Array[AdditionalName]?

            def additional_terms_of_service: () -> AdditionalTermsOfService?

            def address: () -> Address?

            def created: () -> String

            def date_of_birth: () -> DateOfBirth?

            def documents: () -> Documents?

            def email: () -> String?

            def given_name: () -> String?

            def id: () -> String

            def id_numbers: () -> ::Array[IdNumber]?

            def legal_gender: () -> String?

            def metadata: () -> ::Stripe::StripeObject?

            def nationalities: () -> ::Array[String]?

            def object: () -> String

            def phone: () -> String?

            def political_exposure: () -> String?

            def relationship: () -> Relationship?

            def script_addresses: () -> ScriptAddresses?

            def script_names: () -> ScriptNames?

            def surname: () -> String?

            def updated: () -> String
          end

          def attestations: () -> Attestations?

          def business_details: () -> BusinessDetails?

          def country: () -> String?

          def entity_type: () -> String?

          def individual: () -> Individual?
        end

        class Requirements < ::Stripe::StripeObject
          class Entry < ::Stripe::StripeObject
            class Error < ::Stripe::StripeObject
              def code: () -> String

              def description: () -> String
            end

            class Impact < ::Stripe::StripeObject
              class RestrictsCapability < ::Stripe::StripeObject
                class Deadline < ::Stripe::StripeObject
                  def status: () -> String
                end

                def capability: () -> String

                def configuration: () -> String

                def deadline: () -> Deadline
              end

              def restricts_capabilities: () -> ::Array[RestrictsCapability]?
            end

            class MinimumDeadline < ::Stripe::StripeObject
              def status: () -> String
            end

            class Reference < ::Stripe::StripeObject
              def inquiry: () -> String?

              def resource: () -> String?

              def type: () -> String
            end

            class RequestedReason < ::Stripe::StripeObject
              def code: () -> String
            end

            def awaiting_action_from: () -> String

            def description: () -> String

            def errors: () -> ::Array[Error]

            def impact: () -> Impact

            def minimum_deadline: () -> MinimumDeadline

            def reference: () -> Reference?

            def requested_reasons: () -> ::Array[RequestedReason]
          end

          class Summary < ::Stripe::StripeObject
            class MinimumDeadline < ::Stripe::StripeObject
              def status: () -> String

              def time: () -> String?
            end

            def minimum_deadline: () -> MinimumDeadline?
          end

          def entries: () -> ::Array[Entry]?

          def summary: () -> Summary?
        end

        def applied_configurations: () -> ::Array[String]

        def closed: () -> bool?

        def configuration: () -> Configuration?

        def contact_email: () -> String?

        def contact_phone: () -> String?

        def created: () -> String

        def dashboard: () -> String?

        def defaults: () -> Defaults?

        def display_name: () -> String?

        def future_requirements: () -> FutureRequirements?

        def id: () -> String

        def identity: () -> Identity?

        def livemode: () -> bool

        def metadata: () -> ::Stripe::StripeObject?

        def object: () -> String

        def requirements: () -> Requirements?
      end
    end
  end
end
