module Stripe
  module V2
    module Core
      class EventReasonRequest
        def id: () -> String

        def idempotency_key: () -> String

        def initialize: (?::Hash[untyped, untyped] event_reason_request_payload) -> void
      end

      class EventReason
        def type: () -> String

        def request: () -> ::Stripe::V2::Core::EventReasonRequest

        def initialize: (?::Hash[untyped, untyped] event_reason_payload) -> void
      end

      class EventNotification
        def id: () -> String

        def object: () -> String

        def type: () -> String

        def created: () -> String

        def context: () -> String?

        def livemode: () -> bool

        def reason: () -> ::Stripe::V2::Core::EventReason?
      end
    end
  end
end
