module Stripe
  module V2
    module Core
      class Event < APIResource
        class Reason < ::Stripe::StripeObject
          class Request < ::Stripe::StripeObject
            def id: () -> String

            def idempotency_key: () -> String
          end

          def request: () -> Request?

          def type: () -> String
        end

        def changes: () -> ::Stripe::StripeObject?

        def context: () -> String?

        def created: () -> String

        def id: () -> String

        def livemode: () -> bool

        def object: () -> String

        def reason: () -> Reason?

        def snapshot_event: () -> String?

        def type: () -> String
      end
    end
  end
end
