inherit_from: ../../.rubocop.yml

# Please specify only supported versions.
RBS/Layout:
  Enabled: true
  Include:
    - "gems/activerecord/7.2/**/*.rbs"
    - "gems/activerecord/8.0/**/*.rbs"
RBS/Lint:
  Enabled: true
  Include:
    - "gems/activerecord/7.2/**/*.rbs"
    - "gems/activerecord/8.0/**/*.rbs"
RBS/Style:
  Enabled: true
  Include:
    - "gems/activerecord/7.2/**/*.rbs"
    - "gems/activerecord/8.0/**/*.rbs"
