class Shrine
  class Attacher
    module ClassMethods
    end

    module InstanceMethods
      attr_reader file: Shrine::UploadedFile?

      def initialize: (?file: untyped, ?cache: Symbol, ?store: Symbol) -> void
      def assign: (untyped value, **untyped options) -> void
    end

    extend ClassMethods
    include InstanceMethods
  end
end
