class Shrine
  module Storage
    type t = FileSystem | Linter | Memory | S3

    class FileSystem
      def initialize: (String directory, ?prefix: String, ?clean: bool, ?permissions: Integer, ?directory_permissions: Integer) -> void
    end

    class Linter
    end

    class Memory
    end

    class S3
    end
  end
end
