class Shrine
  module Storage
    type t = FileSystem | Linter | Memory | S3

    class FileSystem
      def initialize: (String directory, ?prefix: String, ?clean: bool, ?permissions: Integer, ?directory_permissions: Integer) -> void
      def delete: (untyped id) -> void
      def delete_prefixed: (String delete_prefix) -> void
    end

    class Linter
    end

    class Memory
      def delete: (untyped id) -> void
      def delete_prefixed: (String delete_prefix) -> void
    end

    class S3
      def delete: (untyped id) -> void
      def delete_prefixed: (String delete_prefix) -> void
    end
  end
end
