# Classes
module Chronic
  def self.parse: (String text, ?context: (:future | :past), ?now: untyped, ?hours24: boolish, ?week_start: (:sunday | :monday), ?guess: (bool | :begin | :middle | :end), ?ambiguous_time_range: (Integer | :none), ?endian_precedence: (:middle | :little | Array[:middle | :little]), ?ambiguous_year_future_bias: Integer ) -> untyped
end
