class Venue < ActiveRecord::Base
  # Note: Geocoder::Store::ActiveRecord is automatically loaded by `.geocoded_by` call on Ruby.
  #       But there is no special way to do it on RBS side.  Therefore, developers should include it manually in their types.
  include Geocoder::Store::ActiveRecord
end
