module ActiveModel
  class Serializer[T]
    def self.attributes: (*Symbol attrs) -> void
    def self.attribute: (Symbol attr, ?Hash[Symbol, untyped] options) ?{ () -> untyped } -> void
    def self.type: (_ToS type) -> void

    attr_accessor object: T
    attr_accessor root: untyped
    attr_accessor scope: untyped

    def initialize: (T object, ?Hash[Symbol, untyped] options) -> void
  end
end
