module ActiveModel
  class Serializer
    def self.attributes: (*Symbol attrs) -> void
    def self.attribute: (Symbol attr, Hash[Symbol, untyped] options) ?{ () -> untyped } -> void

    attr_accessor object: untyped
    attr_accessor root: untyped
    attr_accessor scope: untyped

    def initialize: (untyped object, Hash[Symbol, untyped] options) -> void
  end
end
