module ActiveModelSerializers
  class Model
    def self.attributes: (*Symbol) -> void
  end

  class SerializableResource
    def initialize: (untyped resource, Hash[Symbol, untyped] options) -> void
    def to_json: -> String
    def as_json: -> Hash[Symbol, untyped]
  end
end
