class YARD::Parser::Ruby::Legacy::RubyParser < ::YARD::Parser::Base
  def initialize: (untyped source, untyped _filename) -> void
  def parse: () -> untyped
  def tokenize: () -> untyped
  def enumerator: () -> untyped
  def encoding_line: () -> untyped
  def shebang_line: () -> untyped
end
