D = Steep::Diagnostic

target :test do
  check "."
  signature "."

  repo_path "../../../"
  library "pathname"
  library "logger"
  library "mutex_m"
  library "cgi"
  library "date"
  library "erb"
  library "monitor"
  library "singleton"
  library "tsort"
  library 'rack'
  library 'thor'
  library 'time'
  library 'tempfile'
  library "activestorage:6.0"
  library "activerecord:6.0"
  library "activesupport:6.0"
  library "activemodel:6.0"
  library "actionpack:6.0"
  library "activejob:6.0"
  library "actionview:6.0"
  library "railties:6.0"

  configure_code_diagnostics(D::Ruby.all_error)
end
