module Stripe
  module TestHelpers
    module Issuing
      class AuthorizationService < StripeService
        def capture: (String authorization, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Issuing::Authorization

        def create: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Issuing::Authorization

        def expire: (String authorization, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Issuing::Authorization

        def finalize_amount: (String authorization, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Issuing::Authorization

        def increment: (String authorization, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Issuing::Authorization

        def respond: (String authorization, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Issuing::Authorization

        def reverse: (String authorization, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Issuing::Authorization
      end
    end
  end
end
