module Stripe
  module TestHelpers
    module Issuing
      class CardService < StripeService
        def deliver_card: (String card, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Issuing::Card

        def fail_card: (String card, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Issuing::Card

        def return_card: (String card, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Issuing::Card

        def ship_card: (String card, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Issuing::Card

        def submit_card: (String card, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Issuing::Card
      end
    end
  end
end
