module Stripe
  module TestHelpers
    module Issuing
      class PersonalizationDesignService < StripeService
        def activate: (String personalization_design, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Issuing::PersonalizationDesign

        def deactivate: (String personalization_design, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Issuing::PersonalizationDesign

        def reject: (String personalization_design, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Issuing::PersonalizationDesign
      end
    end
  end
end
