module Stripe
  module TestHelpers
    module Issuing
      class TransactionService < StripeService
        def create_force_capture: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Issuing::Transaction

        def create_unlinked_refund: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Issuing::Transaction

        def refund: (String transaction, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Issuing::Transaction
      end
    end
  end
end
