module LaunchDarkly
  #
  # This class exposes advanced configuration options for the LaunchDarkly
  # client library. Most users will not need to use a custom configuration--
  # the default configuration sets sane defaults for most use cases.
  #
  #
  class Config
    #
    # Constructor for creating custom LaunchDarkly configurations.
    #
    # @param opts [Hash] the configuration options
    # @option opts [Logger] :logger See {#logger}.
    # @option opts [String] :base_uri ("https://sdk.launchdarkly.com") See {#base_uri}.
    # @option opts [String] :stream_uri ("https://stream.launchdarkly.com") See {#stream_uri}.
    # @option opts [String] :events_uri ("https://events.launchdarkly.com") See {#events_uri}.
    # @option opts [Integer] :capacity (10000) See {#capacity}.
    # @option opts [Float] :flush_interval (30) See {#flush_interval}.
    # @option opts [Float] :read_timeout (10) See {#read_timeout}.
    # @option opts [Float] :initial_reconnect_delay (1) See {#initial_reconnect_delay}.
    # @option opts [Float] :connect_timeout (2) See {#connect_timeout}.
    # @option opts [Object] :cache_store See {#cache_store}.
    # @option opts [Object] :feature_store See {#feature_store}.
    # @option opts [Boolean] :use_ldd (false) See {#use_ldd?}.
    # @option opts [Boolean] :offline (false) See {#offline?}.
    # @option opts [Float] :poll_interval (30) See {#poll_interval}.
    # @option opts [Boolean] :stream (true) See {#stream?}.
    # @option opts [Boolean] all_attributes_private (false) See {#all_attributes_private}.
    # @option opts [Array] :private_attribute_names See {#private_attribute_names}.
    # @option opts [Boolean] :send_events (true) See {#send_events}.
    # @option opts [Integer] :user_keys_capacity (1000) See {#user_keys_capacity}.
    # @option opts [Float] :user_keys_flush_interval (300) See {#user_keys_flush_interval}.
    # @option opts [Boolean] :inline_users_in_events (false) See {#inline_users_in_events}.
    # @option opts [Object] :data_source See {#data_source}.
    # @option opts [Object] :update_processor Obsolete synonym for `data_source`.
    # @option opts [Object] :update_processor_factory Obsolete synonym for `data_source`.
    # @option opts [Boolean] :diagnostic_opt_out (false) See {#diagnostic_opt_out?}.
    # @option opts [Float] :diagnostic_recording_interval (900) See {#diagnostic_recording_interval}.
    # @option opts [String] :wrapper_name See {#wrapper_name}.
    # @option opts [String] :wrapper_version See {#wrapper_version}.
    # @option opts [#open] :socket_factory See {#socket_factory}.
    # @option opts [BigSegmentsConfig] :big_segments See {#big_segments}.
    # @option opts [Hash] :application See {#application}
    #
    def initialize: (?::Hash[untyped, untyped] opts) -> void

    #
    # The base URL for the LaunchDarkly server. This is configurable mainly for testing
    # purposes; most users should use the default value.
    # @return [String]
    #
    attr_reader base_uri: untyped

    #
    # The base URL for the LaunchDarkly streaming server. This is configurable mainly for testing
    # purposes; most users should use the default value.
    # @return [String]
    #
    attr_reader stream_uri: untyped

    #
    # The base URL for the LaunchDarkly events server. This is configurable mainly for testing
    # purposes; most users should use the default value.
    # @return [String]
    #
    attr_reader events_uri: untyped

    #
    # Whether streaming mode should be enabled. Streaming mode asynchronously updates
    # feature flags in real-time using server-sent events. Streaming is enabled by default, and
    # should only be disabled on the advice of LaunchDarkly support.
    # @return [Boolean]
    #
    def stream?: () -> untyped

    #
    # Whether to use the LaunchDarkly relay proxy in daemon mode. In this mode, the client does not
    # use polling or streaming to get feature flag updates from the server, but instead reads them
    # from the {#feature_store feature store}, which is assumed to be a database that is populated by
    # a LaunchDarkly relay proxy. For more information, see ["The relay proxy"](https://docs.launchdarkly.com/home/relay-proxy)
    # and ["Using a persistent data stores"](https://docs.launchdarkly.com/sdk/concepts/data-stores).
    #
    # All other properties related to streaming or polling are ignored if this option is set to true.
    #
    # @return [Boolean]
    #
    def use_ldd?: () -> untyped

    #
    # Whether the client should be initialized in offline mode. In offline mode, default values are
    # returned for all flags and no remote network requests are made.
    # @return [Boolean]
    #
    def offline?: () -> untyped

    #
    # The number of seconds between flushes of the event buffer. Decreasing the flush interval means
    # that the event buffer is less likely to reach capacity.
    # @return [Float]
    #
    attr_reader flush_interval: untyped

    #
    # The number of seconds to wait before polling for feature flag updates. This option has no
    # effect unless streaming is disabled.
    # @return [Float]
    #
    attr_reader poll_interval: untyped

    #
    # The configured logger for the LaunchDarkly client. The client library uses the log to
    # print warning and error messages. If not specified, this defaults to the Rails logger
    # in a Rails environment, or stdout otherwise.
    # @return [Logger]
    #
    attr_reader logger: untyped

    #
    # The capacity of the events buffer. The client buffers up to this many
    # events in memory before flushing. If the capacity is exceeded before
    # the buffer is flushed, events will be discarded.
    # Increasing the capacity means that events are less likely to be discarded,
    # at the cost of consuming more memory.
    # @return [Integer]
    #
    attr_reader capacity: untyped

    #
    # A store for HTTP caching (used only in polling mode). This must support the semantics used by
    # the [`faraday-http-cache`](https://github.com/plataformatec/faraday-http-cache) gem, although
    # the SDK no longer uses Faraday. Defaults to the Rails cache in a Rails environment, or a
    # thread-safe in-memory store otherwise.
    # @return [Object]
    #
    attr_reader cache_store: untyped

    #
    # The read timeout for network connections in seconds. This does not apply to the streaming
    # connection, which uses a longer timeout since the server does not send data constantly.
    # @return [Float]
    #
    attr_reader read_timeout: untyped

    #
    # The initial delay before reconnecting after an error in the SSE client.
    # This only applies to the streaming connection.
    # @return [Float]
    #
    attr_reader initial_reconnect_delay: untyped

    #
    # The connect timeout for network connections in seconds.
    # @return [Float]
    #
    attr_reader connect_timeout: untyped

    #
    # A store for feature flags and related data. The client uses it to store all data received
    # from LaunchDarkly, and uses the last stored data when evaluating flags. Defaults to
    # {InMemoryFeatureStore}; for other implementations, see {LaunchDarkly::Integrations}.
    #
    # For more information, see ["Persistent data stores"](https://docs.launchdarkly.com/sdk/concepts/data-stores).
    #
    # @return [LaunchDarkly::Interfaces::FeatureStore]
    #
    attr_reader feature_store: untyped

    #
    # True if all user attributes (other than the key) should be considered private. This means
    # that the attribute values will not be sent to LaunchDarkly in analytics events and will not
    # appear on the LaunchDarkly dashboard.
    # @return [Boolean]
    # @see #private_attribute_names
    #
    attr_reader all_attributes_private: untyped

    #
    # A list of user attribute names that should always be considered private. This means that the
    # attribute values will not be sent to LaunchDarkly in analytics events and will not appear on
    # the LaunchDarkly dashboard.
    #
    # You can also specify the same behavior for an individual flag evaluation by storing an array
    # of attribute names in the `:privateAttributeNames` property (note camelcase name) of the
    # user object.
    #
    # @return [Array<String>]
    # @see #all_attributes_private
    #
    attr_reader private_attribute_names: untyped

    #
    # Whether to send events back to LaunchDarkly. This differs from {#offline?} in that it affects
    # only the sending of client-side events, not streaming or polling for events from the server.
    # @return [Boolean]
    #
    attr_reader send_events: untyped

    #
    # The number of user keys that the event processor can remember at any one time. This reduces the
    # amount of duplicate user details sent in analytics events.
    # @return [Integer]
    # @see #user_keys_flush_interval
    #
    attr_reader user_keys_capacity: untyped

    #
    # The interval in seconds at which the event processor will reset its set of known user keys.
    # @return [Float]
    # @see #user_keys_capacity
    #
    attr_reader user_keys_flush_interval: untyped

    #
    # Whether to include full user details in every analytics event. By default, events will only
    # include the user key, except for one "index" event that provides the full details for the user.
    # The only reason to change this is if you are using the Analytics Data Stream.
    # @return [Boolean]
    #
    attr_reader inline_users_in_events: untyped

    #
    # An object that is responsible for receiving feature flag data from LaunchDarkly. By default,
    # the client uses its standard polling or streaming implementation; this is customizable for
    # testing purposes.
    #
    # This may be set to either an object that conforms to {LaunchDarkly::Interfaces::DataSource},
    # or a lambda (or Proc) that takes two parameters-- SDK key and {Config}-- and returns such an
    # object.
    #
    # @return [LaunchDarkly::Interfaces::DataSource|lambda]
    # @see LaunchDarkly::Integrations::FileData
    # @see LaunchDarkly::Integrations::TestData
    #
    attr_reader data_source: Interfaces::DataSource | ^(String, Config) -> Interfaces::DataSource

    #
    # Configuration options related to Big Segments.
    #
    # Big Segments are a specific type of user segments. For more information, read the LaunchDarkly
    # documentation: https://docs.launchdarkly.com/home/users/big-segments
    #
    # @return [BigSegmentsConfig]
    #
    attr_reader big_segments: untyped

    #
    # An object that allows configuration of application metadata.
    #
    # Application metadata may be used in LaunchDarkly analytics or other product features, but does not affect feature flag evaluations.
    #
    # If you want to set non-default values for any of these fields, provide the appropriately configured hash to the {Config} object.
    #
    # @example Configuring application information
    #   opts[:application] = {
    #     id: "MY APPLICATION ID",
    #     version: "MY APPLICATION VERSION"
    #   }
    #   config = LDConfig.new(opts)
    #
    # @return [Hash]
    #
    attr_reader application: untyped

    # @deprecated This is replaced by {#data_source}.
    attr_reader update_processor: untyped

    # @deprecated This is replaced by {#data_source}.
    attr_reader update_processor_factory: untyped

    #
    # Set to true to opt out of sending diagnostics data.
    #
    # Unless `diagnostic_opt_out` is set to true, the client will send some diagnostics data to the LaunchDarkly servers
    # in order to assist in the development of future SDK improvements. These diagnostics consist of an initial payload
    # containing some details of the SDK in use, the SDK's configuration, and the platform the SDK is being run on, as
    # well as periodic information on irregular occurrences such as dropped events.
    # @return [Boolean]
    #
    def diagnostic_opt_out?: () -> untyped

    #
    # The interval at which periodic diagnostic data is sent, in seconds.
    #
    # The default is 900 (every 15 minutes) and the minimum value is 60 (every minute).
    # @return [Float]
    #
    attr_reader diagnostic_recording_interval: untyped

    #
    # For use by wrapper libraries to set an identifying name for the wrapper being used.
    #
    # This will be sent in User-Agent headers during requests to the LaunchDarkly servers to allow recording
    # metrics on the usage of these wrapper libraries.
    # @return [String]
    #
    attr_reader wrapper_name: untyped

    #
    # For use by wrapper libraries to report the version of the library in use.
    #
    # If `wrapper_name` is not set, this field will be ignored. Otherwise the version string will be included in
    # the User-Agent headers along with the `wrapper_name` during requests to the LaunchDarkly servers.
    # @return [String]
    #
    attr_reader wrapper_version: untyped

    #
    # The factory used to construct sockets for HTTP operations. The factory must
    # provide the method `open(uri, timeout)`. The `open` method must return a
    # connected stream that implements the `IO` class, such as a `TCPSocket`.
    #
    # Defaults to nil.
    # @return [#open]
    #
    attr_reader socket_factory: untyped

    #
    # The default LaunchDarkly client configuration. This configuration sets
    # reasonable defaults for most users.
    # @return [Config] The default LaunchDarkly configuration.
    #
    def self.default: () -> untyped

    #
    # The default value for {#capacity}.
    # @return [Integer] 10000
    #
    def self.default_capacity: () -> 10000

    #
    # The default value for {#base_uri}.
    # @return [String] "https://sdk.launchdarkly.com"
    #
    def self.default_base_uri: () -> "https://sdk.launchdarkly.com"

    #
    # The default value for {#stream_uri}.
    # @return [String] "https://stream.launchdarkly.com"
    #
    def self.default_stream_uri: () -> "https://stream.launchdarkly.com"

    #
    # The default value for {#events_uri}.
    # @return [String] "https://events.launchdarkly.com"
    #
    def self.default_events_uri: () -> "https://events.launchdarkly.com"

    #
    # The default value for {#cache_store}.
    # @return [Object] the Rails cache if in Rails, or a simple in-memory implementation otherwise
    #
    def self.default_cache_store: () -> untyped

    #
    # The default value for {#flush_interval}.
    # @return [Float] 10
    #
    def self.default_flush_interval: () -> 10

    #
    # The default value for {#read_timeout}.
    # @return [Float] 10
    #
    def self.default_read_timeout: () -> 10

    #
    # The default value for {#initial_reconnect_delay}.
    # @return [Float] 1
    #
    def self.default_initial_reconnect_delay: () -> 1

    #
    # The default value for {#connect_timeout}.
    # @return [Float] 10
    #
    def self.default_connect_timeout: () -> 2

    #
    # The default value for {#logger}.
    # @return [Logger] the Rails logger if in Rails, or a default Logger at WARN level otherwise
    #
    def self.default_logger: () -> untyped

    #
    # The default value for {#stream?}.
    # @return [Boolean] true
    #
    def self.default_stream: () -> true

    #
    # The default value for {#use_ldd?}.
    # @return [Boolean] false
    #
    def self.default_use_ldd: () -> false

    #
    # The default value for {#feature_store}.
    # @return [LaunchDarkly::Interfaces::FeatureStore] an {InMemoryFeatureStore}
    #
    def self.default_feature_store: () -> untyped

    #
    # The default value for {#offline?}.
    # @return [Boolean] false
    #
    def self.default_offline: () -> false

    #
    # The default value for {#poll_interval}.
    # @return [Float] 30
    #
    def self.default_poll_interval: () -> 30

    #
    # The default value for {#send_events}.
    # @return [Boolean] true
    #
    def self.default_send_events: () -> true

    #
    # The default value for {#user_keys_capacity}.
    # @return [Integer] 1000
    #
    def self.default_user_keys_capacity: () -> 1000

    #
    # The default value for {#user_keys_flush_interval}.
    # @return [Float] 300
    #
    def self.default_user_keys_flush_interval: () -> 300

    #
    # The default value for {#diagnostic_recording_interval}.
    # @return [Float] 900
    #
    def self.default_diagnostic_recording_interval: () -> 900

    #
    # The minimum value for {#diagnostic_recording_interval}.
    # @return [Float] 60
    #
    def self.minimum_diagnostic_recording_interval: () -> 60
  end

  #
  # Configuration options related to Big Segments.
  #
  # Big Segments are a specific type of user segments. For more information, read the LaunchDarkly
  # documentation: https://docs.launchdarkly.com/home/users/big-segments
  #
  # If your application uses Big Segments, you will need to create a `BigSegmentsConfig` that at a
  # minimum specifies what database integration to use, and then pass the `BigSegmentsConfig`
  # object as the `big_segments` parameter when creating a {Config}.
  #
  # @example Configuring Big Segments with Redis
  #     store = LaunchDarkly::Integrations::Redis::new_big_segments_store(redis_url: "redis://my-server")
  #     config = LaunchDarkly::Config.new(big_segments:
  #       LaunchDarkly::BigSegmentsConfig.new(store: store))
  #     client = LaunchDarkly::LDClient.new(my_sdk_key, config)
  #
  class BigSegmentsConfig
    DEFAULT_USER_CACHE_SIZE: 1000

    DEFAULT_USER_CACHE_TIME: 5

    DEFAULT_STATUS_POLL_INTERVAL: 5

    DEFAULT_STALE_AFTER: untyped

    #
    # Constructor for setting Big Segments options.
    #
    # @param store [LaunchDarkly::Interfaces::BigSegmentStore] the data store implementation
    # @param user_cache_size [Integer] See {#user_cache_size}.
    # @param user_cache_time [Float] See {#user_cache_time}.
    # @param status_poll_interval [Float] See {#status_poll_interval}.
    # @param stale_after [Float] See {#stale_after}.
    #
    def initialize: (store: untyped, ?user_cache_size: untyped?, ?user_cache_time: untyped?, ?status_poll_interval: untyped?, ?stale_after: untyped?) -> void

    # The implementation of {LaunchDarkly::Interfaces::BigSegmentStore} that will be used to
    # query the Big Segments database.
    # @return [LaunchDarkly::Interfaces::BigSegmentStore]
    attr_reader store: untyped

    # The maximum number of users whose Big Segment state will be cached by the SDK at any given time.
    # @return [Integer]
    attr_reader user_cache_size: untyped

    # The maximum length of time (in seconds) that the Big Segment state for a user will be cached
    # by the SDK.
    # @return [Float]
    attr_reader user_cache_time: untyped

    # The interval (in seconds) at which the SDK will poll the Big Segment store to make sure it is
    # available and to determine how long ago it was updated.
    # @return [Float]
    attr_reader status_poll_interval: untyped

    # The maximum length of time between updates of the Big Segments data before the data is
    # considered out of date.
    # @return [Float]
    attr_reader stale_after: untyped
  end
end
