module LaunchDarkly
  # Simple implementation of a thread-safe memoized value whose generator function will never be
  # run more than once, and whose value can be overridden by explicit assignment.
  # Note that we no longer use this class and it will be removed in a future version.
  # @private
  class MemoizedValue
    def initialize: () { () -> untyped } -> void

    def get: () -> untyped

    def set: (untyped value) -> untyped
  end
end
