module LaunchDarkly
  # Simple wrapper for a FixedThreadPool that rejects new jobs if all the threads are busy, rather
  # than blocking. Also provides a way to wait for all jobs to finish without shutting down.
  # @private
  class NonBlockingThreadPool
    def initialize: (untyped capacity) -> void

    # Attempts to submit a job, but only if a worker is available. Unlike the regular post method,
    # this returns a value: true if the job was submitted, false if all workers are busy.
    def post: () { () -> untyped } -> (nil | untyped)

    # Waits until no jobs are executing, without shutting down the pool.
    def wait_all: () -> untyped

    def shutdown: () -> untyped

    def wait_for_termination: () -> untyped
  end
end
