module LaunchDarkly
  # @private
  class UserFilter
    def initialize: (untyped config) -> void

    def transform_user_props: (untyped user_props) -> (nil | untyped)

    private

    ALLOWED_TOP_LEVEL_KEYS: untyped

    IGNORED_TOP_LEVEL_KEYS: untyped

    def filter_values: (untyped props, untyped user_private_attrs, ?untyped allowed_keys, ?untyped keys_to_leave_as_is) -> ::Array[untyped]

    def private_attr?: (untyped name, untyped user_private_attrs) -> untyped
  end
end
