module LaunchDarkly
  # @private
  module Util
    def self.stringify_attrs: (untyped hash, untyped attrs) -> untyped

    def self.new_http_client: (untyped uri_s, untyped config) -> untyped

    def self.log_exception: (untyped logger, untyped message, untyped exc) -> untyped

    def self.http_error_recoverable?: (untyped status) -> (untyped | true)

    def self.http_error_message: (untyped status, untyped context, untyped recoverable_message) -> ::String
  end
end
