class User < ActiveRecord::Base
  extend ::ActiveRecord::Base::ClassMethods[User, ActiveRecord_Relation, Integer]

  class ActiveRecord_Relation < ::ActiveRecord::Relation
    include ::ActiveRecord::Relation::Methods[User, Integer]
  end
end
