# Classes
module HolidayJp
  class Holiday
    attr_reader date: Date
    attr_reader name: String

    def initialize: (Date, String) -> void
  end

  class Holidays
    attr_accessor holidays: Array[Holiday]

    def initialize: () -> void
    def between: (Date, Date) -> Array[Holiday]
  end

  def self.between: (Date, Date) -> (Array[Holiday] | Array[untyped])
  def self.holiday?: (Date) -> bool
end
