module ActiveHash
  module Associations
    module ActiveRecordExtensions
      def belongs_to: (Symbol name, ?untyped scope, **untyped options) -> void
      def belongs_to_active_hash: (Symbol association_id, **untyped options) -> void
    end

    module Methods
      def has_many: (Symbol association_id, **untyped options) -> void
      def has_one: (Symbol association_id, **untyped options) -> void
      def belongs_to: (Symbol association_id, **untyped options) -> void
    end
  end
end
