# Simple class for turning a flipper_id into an actor that can be based
# to Flipper::Feature#enabled?.
module Flipper
  class Actor
    attr_reader flipper_id: untyped

    def initialize: (untyped flipper_id) -> void

    def eql?: (untyped other) -> untyped

    alias == eql?

    def hash: () -> untyped
  end
end
