D = Steep::Diagnostic

target :test do
  check "."
  signature "."

  repo_path "../../../"
  library "json-jwt"

  library "activesupport"
  library "date"
  library "erb"
  library "logger"
  library "monitor"
  library "mutex_m"
  library "openssl"
  library "singleton"
  library "time"

  configure_code_diagnostics(D::Ruby.all_error)
end
