module Zip
  WINDOWS: bool

  CENTRAL_DIRECTORY_ENTRY_SIGNATURE: Integer
  CDIR_ENTRY_STATIC_HEADER_LENGTH: Integer
  LOCAL_ENTRY_SIGNATURE: Integer
  LOCAL_ENTRY_STATIC_HEADER_LENGTH: Integer
  LOCAL_ENTRY_TRAILING_DESCRIPTOR_SIZE: Integer
  SPLIT_FILE_SIGNATURE: Integer

  VERSION_MADE_BY: Integer
  VERSION_NEEDED_TO_EXTRACT: Integer
  VERSION_NEEDED_TO_EXTRACT_ZIP64: Integer

  FILE_TYPE_FILE: Integer
  FILE_TYPE_DIR: Integer
  FILE_TYPE_SYMLINK: Integer

  FSTYPE_FAT: Integer
  FSTYPE_AMIGA: Integer
  FSTYPE_VMS: Integer
  FSTYPE_UNIX: Integer
  FSTYPE_VM_CMS: Integer
  FSTYPE_ATARI: Integer
  FSTYPE_HPFS: Integer
  FSTYPE_MAC: Integer
  FSTYPE_Z_SYSTEM: Integer
  FSTYPE_CPM: Integer
  FSTYPE_TOPS20: Integer
  FSTYPE_NTFS: Integer
  FSTYPE_QDOS: Integer
  FSTYPE_ACORN: Integer
  FSTYPE_VFAT: Integer
  FSTYPE_MVS: Integer
  FSTYPE_BEOS: Integer
  FSTYPE_TANDEM: Integer
  FSTYPE_THEOS: Integer
  FSTYPE_MAC_OSX: Integer
  FSTYPE_ATHEOS: Integer

  FSTYPES: Hash[Integer, String]

  COMPRESSION_METHOD_STORE: Integer
  COMPRESSION_METHOD_DEFLATE: Integer

  COMPRESSION_METHODS: Hash[Integer, String]
end
