module Zip
  class Deflater < Compressor
    attr_reader size: Integer
    attr_reader crc: Integer

    def initialize: (IO output_stream, ?Integer level, ?encrypter: Encrypter?) -> void

    def <<: (String data) -> self

    def finish: -> void
  end
end
