module Zip
  module Dirtyable
    module ClassMethods
      def mark_dirty: (*Symbol method_names) -> void
    end

    def initialize: (?dirty_on_create: bool) -> void

    def dirty?: () -> bool
  end
end
