module Zip
  class DOSTime < Time
    def self.parse_binary_dos_format: (Integer dos_time, Integer dos_date) -> DOSTime

    def self.from_time: (Time time) -> DOSTime

    def to_binary_dos_time: -> Integer

    def to_binary_dos_date: -> Integer

    def <=>: (Time other) -> Integer?
  end
end
