module Zip
  class Entry
    include Dirtyable

    STORED: Integer
    DEFLATED: Integer
    EFS: Integer
    COMPRESSION_LEVEL_SUPERFAST_GPFLAG: Integer
    COMPRESSION_LEVEL_FAST_GPFLAG: Integer
    COMPRESSION_LEVEL_MAX_GPFLAG: Integer

    attr_accessor comment: String
    attr_accessor compressed_size: Integer
    attr_accessor crc: Integer
    attr_accessor external_file_attributes: Integer
    attr_accessor follow_symlinks: bool
    attr_accessor fstype: Integer
    attr_accessor gp_flags: Integer
    attr_accessor internal_file_attributes: Integer
    attr_accessor local_header_offset: Integer
    attr_accessor name: String
    attr_accessor restore_ownership: bool
    attr_accessor restore_permissions: bool
    attr_accessor restore_times: bool
    attr_accessor unix_gid: Integer?
    attr_accessor unix_perms: Integer?
    attr_accessor unix_uid: Integer?

    attr_reader compression_level: Integer
    attr_reader extra: ExtraField
    attr_reader filepath: String?

    attr_writer size: Integer

    def self.read_c_dir_entry: (IO io) -> Entry?
    def self.read_local_entry: (IO io) -> Entry?

    def initialize: (
      ?String zipfile,
      ?String name,
      ?comment: String,
      ?size: Integer?,
      ?compressed_size: Integer,
      ?crc: Integer,
      ?compression_method: Integer,
      ?compression_level: Integer,
      ?time: DOSTime,
      ?extra: ExtraField
    ) -> void

    def size: () -> Integer

    def time: (?component: Symbol) -> (Time | DOSTime)
    def mtime: (?component: Symbol) -> (Time | DOSTime)
    def atime: () -> Time?
    def ctime: () -> Time?

    def time=: (Time | DOSTime value, ?component: Symbol) -> (Time | DOSTime)
    def mtime=: (Time | DOSTime value, ?component: Symbol) -> (Time | DOSTime)
    def atime=: (Time | DOSTime value) -> (Time | DOSTime)
    def ctime=: (Time | DOSTime value) -> (Time | DOSTime)

    def absolute_time?: () -> bool

    def compression_method: () -> Integer
    def compression_method=: (Integer method) -> Integer

    def encrypted?: () -> bool

    def zip64?: () -> bool
    def aes?: () -> bool

    def directory?: () -> bool
    def file?: () -> bool
    def symlink?: () -> bool

    def name_safe?: () -> bool

    def extract: (?String entry_path, ?destination_directory: String) ?{ (Entry, String) -> boolish } -> self

    def get_input_stream: [TContent] () { (IO) -> TContent } -> TContent
                        | () -> IO

    def write_to_zip_output_stream: (OutputStream zip_output_stream) -> void

    def parent_as_string: () -> String?

    def get_extra_attributes_from_path: (String src_path) -> void

    def ==: (untyped other) -> bool
    def <=>: (Entry other) -> Integer?

    def to_s: () -> String
  end
end
