module Zip
  class Entry
    include Enumerable[Entry]

    def name: -> String

    def extract: (String, ?destination_directory: String?) -> void

    def each: ?{ (Entry) -> void } -> (Enumerator[Entry, void])
  end
end
