module Zip
  class ExtraField < Hash[untyped, untyped]
    ID_MAP: Hash[String, singleton(ExtraField::Generic)]

    def initialize: (?String binstr) -> void

    def merge: (String binstr, ?local: bool) -> self

    def create: (String name) -> ExtraField::Generic

    def suppress_fields!: () -> void

    def local_size: () -> Integer

    def c_dir_size: () -> Integer

    def to_local_bin: () -> String

    def to_c_dir_bin: () -> String
  end
end
