module Zip
  module FileSplit
    MAX_SEGMENT_SIZE: Integer
    MIN_SEGMENT_SIZE: Integer
    DATA_BUFFER_SIZE: Integer

    def split: (
      String zip_file_name,
      ?segment_size: Integer,
      ?delete_original: bool,
      ?partial_zip_file_name: String?
    ) -> Integer?
  end
end
