module Zip
  class PassThruCompressor < Compressor
    attr_reader size: Integer
    attr_reader crc: Integer

    def initialize: (IO output_stream) -> void

    def <<: (String data) -> self
  end
end
