# frozen_string_literal: true

source "https://rubygems.org"

ruby "~> 3.1"

gem 'mustache'
gem 'json'
gem 'rake'
gem 'rbs'
gem 'activesupport'

# aws-sdk-code-generator's dependency
gem 'kramdown'
gem 'jmespath'
