# frozen_string_literal: true

source "https://rubygems.org"

gem 'mustache'
gem 'json'
gem 'rake'

# steep does not support 1.8 or later.
gem 'rbs', '< 1.8'
# steep does not support 7 or later.
gem 'activesupport', '< 7'

# aws-sdk-code-generator's dependency
gem 'kramdown'
gem 'jmespath'
