# frozen_string_literal: true

SUPPORTED_SERVICES = %w[
  EC2
  Firehose
  KMS
  S3
  SNS
  SQS
  SSM
]

# see also aws-sdk-ruby/Rakefile
REPO_ROOT = "#{File.dirname(__FILE__)}/_src"
GEMS_DIR = "#{REPO_ROOT}/gems"
CORE_LIB = "#{REPO_ROOT}/gems/aws-sdk-core/lib"
$:.unshift("#{REPO_ROOT}/build_tools")
$:.unshift("#{REPO_ROOT}/build_tools/aws-sdk-code-generator/lib")
Dir["#{GEMS_DIR}/*"].each do |dir|
  $:.unshift("#{dir}/lib")
end

task :load_lib do
  require_relative 'lib/aws-sdk-rbs-generator'
end

namespace :write do
  SUPPORTED_SERVICES.each do |service_name|
    desc "write for #{service_name}"
    task service_name.downcase => :load_lib do
      target_path = "../../gems"
      dir = File.expand_path(target_path, __dir__)
      AwsSdkRbsGenerator::Services.new[service_name].write_files(dir:)
    end
  end
end

desc "initialize"
task :initialize do
  sh "git clone https://github.com/aws/aws-sdk-ruby.git _src"
end

desc "Update source code"
task :update_src do
  cd "_src" do
    sh "git pull origin version-3"
  end
end

desc "Generate all signatures"
task generate_all: SUPPORTED_SERVICES.map { |s| "write:#{s.downcase}" }

task :default => [:generate_all]
