# frozen_string_literal: true

# see also aws-sdk-ruby/Rakefile
REPO_ROOT = "#{File.dirname(__FILE__)}/_src"
GEMS_DIR = "#{REPO_ROOT}/gems"
CORE_LIB = "#{REPO_ROOT}/gems/aws-sdk-core/lib"
$:.unshift("#{REPO_ROOT}/build_tools")
$:.unshift("#{REPO_ROOT}/build_tools/aws-sdk-code-generator/lib")
Dir["#{GEMS_DIR}/*"].each do |dir|
  $:.unshift("#{dir}/lib")
end

task :load_lib do
  require_relative 'lib/aws-sdk-rbs-generator'
end

task write: :load_lib do |task, args|
  service_args = args.to_a
  services = AwsSdkRbsGenerator::Services.new
  target_path = "../../gems"
  dir = File.expand_path(target_path, __dir__)
  puts "Generate signatures to #{dir}"
  service_args.each { |name| services[name].write_files(dir:) }
end

desc "initialize"
task :initialize do
  sh "git clone https://github.com/aws/aws-sdk-ruby.git _src"
end

desc "Update source code"
task :update_src do
  cd "_src" do
    sh "git pull origin version-3"
  end
end

desc "Generate all signatures"
task generate_all: :load_lib do
  Rake::Task['write'].invoke("S3", "SQS", "KMS", "EC2", "SSM", "Firehose")
end

task :default => [:generate_all]
