module Stripe
  module Climate
    class OrderService < StripeService
      def cancel: (String order, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Climate::Order

      def create: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Climate::Order

      def list: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::Climate::Order]

      def retrieve: (String order, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Climate::Order

      def update: (String order, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Climate::Order
    end
  end
end
