module Stripe
  module Climate
    class ProductService < StripeService
      def list: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::Climate::Product]

      def retrieve: (String product, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Climate::Product
    end
  end
end
