module Stripe
  module Climate
    class SupplierService < StripeService
      def list: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::Climate::Supplier]

      def retrieve: (String supplier, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Climate::Supplier
    end
  end
end
