# Classes
module Woothee
  type attribute_name = (:name | :category | :os | :os_version | :vendor | :version)
 
  def self.parse: (String useragent) -> Hash[Woothee::attribute_name, (String | Symbol)]
  def self.is_crawler: (String useragent) -> bool
end
