# Classes
module Woothee
  def self.parse: (String useragent) -> { name: String, category: Symbol, os: String, os_version: String, version: String, vendor: String }
  def self.is_crawler: (String useragent) -> bool
end
