D = Steep::Diagnostic

target :test do
  check "."
  signature "."

  repo_path "../../../"
  library "rubocop-ast"
  library 'parser'
  library 'ast'

  configure_code_diagnostics(D::Ruby.all_error)
end
