class Person
  include ActiveModel::Attributes
  extend ActiveModel::Attributes::ClassMethods
  include ActiveModel::AttributeRegistration
  extend ActiveModel::AttributeRegistration::ClassMethods
  include ActiveModel::Validations
  extend ActiveModel::Validations::ClassMethods

  attr_accessor name: String?
end
