module Concurrent
  class AtomicReference[T]
    def initialize: (?T value) -> void
    def get: -> T
    def value: -> T
    def set: (T new_value) -> T
    def value=: (T new_value) -> T
    def get_and_set: (T new_value) -> T
    def swap: (T new_value) -> T
    def compare_and_set: (T old_value, T new_value) -> bool
    def compare_and_swap: (T old_value, T new_value) -> bool
    def update: () { (T) -> T } -> T
    def try_update: () { (T) -> T } -> T?
    def try_update!: () { (T) -> T } -> T
  end
end
