module Stripe
  module TestHelpers
    class CustomerService < StripeService
      def fund_cash_balance: (String customer, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::CustomerCashBalanceTransaction
    end
  end
end
