module Stripe
  module TestHelpers
    class IssuingService < StripeService
      attr_reader authorizations: ::Stripe::TestHelpers::Issuing::AuthorizationService

      attr_reader cards: ::Stripe::TestHelpers::Issuing::CardService

      attr_reader personalization_designs: ::Stripe::TestHelpers::Issuing::PersonalizationDesignService

      attr_reader transactions: ::Stripe::TestHelpers::Issuing::TransactionService
    end
  end
end
