module Stripe
  module TestHelpers
    class RefundService < StripeService
      def expire: (String refund, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Refund
    end
  end
end
