module Stripe
  module TestHelpers
    class TestClockService < StripeService
      def advance: (String test_clock, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::TestHelpers::TestClock

      def create: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::TestHelpers::TestClock

      def delete: (String test_clock, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::TestHelpers::TestClock

      def list: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::TestHelpers::TestClock]

      def retrieve: (String test_clock, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::TestHelpers::TestClock
    end
  end
end
