module Stripe
  module TestHelpers
    class TreasuryService < StripeService
      attr_reader inbound_transfers: ::Stripe::TestHelpers::Treasury::InboundTransferService

      attr_reader outbound_payments: ::Stripe::TestHelpers::Treasury::OutboundPaymentService

      attr_reader outbound_transfers: ::Stripe::TestHelpers::Treasury::OutboundTransferService

      attr_reader received_credits: ::Stripe::TestHelpers::Treasury::ReceivedCreditService

      attr_reader received_debits: ::Stripe::TestHelpers::Treasury::ReceivedDebitService
    end
  end
end
