module Stripe
  module V2
    module Billing
      class MeterEventSessionService < StripeService
        def create: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::V2::Billing::MeterEventSession
      end
    end
  end
end
