module Stripe
  module V2
    module Billing
      class MeterEventStreamService < StripeService
        def create: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> void
      end
    end
  end
end
