module Roo
  class Excelx
    class Cell
      class Date < Roo::Excelx::Cell::DateTime
        @format: untyped

        @value: untyped

        attr_reader value: untyped

        attr_reader formula: untyped

        attr_reader format: untyped

        attr_reader cell_type: untyped

        attr_reader cell_value: untyped

        attr_reader coordinate: untyped

        def initialize: (untyped value, untyped formula, untyped excelx_type, untyped style, untyped link, untyped base_date, untyped coordinate) -> void

        private

        def create_datetime: (untyped _, untyped _) -> nil

        def create_date: (untyped base_date, untyped value) -> untyped
      end
    end
  end
end
