module Roo
  class Excelx
    class Cell
      class Empty < Cell::Base
        @coordinate: ::Roo::Excelx::Coordinate

        @default_type: nil

        @style: nil

        attr_reader value: nil

        attr_reader formula: nil

        attr_reader format: nil

        attr_reader cell_type: nil

        attr_reader cell_value: nil

        attr_reader coordinate: ::Roo::Excelx::Coordinate

        def initialize: (::Roo::Excelx::Coordinate coordinate) -> void

        def empty?: () -> true

        def defatult_type: () -> nil

        def style: () -> nil

        def type: () -> nil
      end
    end
  end
end
