module Roo
  class Excelx
    class Cell
      class Empty < Cell::Base
        @coordinate: untyped

        attr_reader value: untyped

        attr_reader formula: untyped

        attr_reader format: untyped

        attr_reader cell_type: untyped

        attr_reader cell_value: untyped

        attr_reader coordinate: untyped

        def initialize: (untyped coordinate) -> void

        def empty?: () -> true
      end
    end
  end
end
