module Roo
  class Excelx
    class Cell
      class Number < Cell::Base
        # FIXME: Excelx_type is an array, but the first value isn't used.
        @format: untyped

        @value: untyped

        attr_reader value: untyped

        attr_reader formula: untyped

        attr_reader format: untyped

        attr_reader cell_value: untyped

        attr_reader coordinate: untyped

        def initialize: (untyped value, untyped formula, untyped excelx_type, untyped style, untyped link, untyped coordinate) -> void

        def create_numeric: (untyped number) -> untyped

        def formatted_value: () -> untyped

        def generate_formatter: (untyped format) -> untyped

        private

        def number_format: (untyped formatter, ?untyped? negative_formatter) -> untyped
      end
    end
  end
end
