module Roo
  class Excelx
    class Cell
      class Time < Roo::Excelx::Cell::DateTime
        @format: untyped

        @datetime: untyped

        @value: untyped

        attr_reader value: untyped

        attr_reader formula: untyped

        attr_reader format: untyped

        attr_reader cell_value: untyped

        attr_reader coordinate: untyped

        def initialize: (untyped value, untyped formula, untyped excelx_type, untyped style, untyped link, untyped base_date, untyped coordinate) -> void

        def formatted_value: () -> untyped

        alias to_s formatted_value
      end
    end
  end
end
