module Roo
  class Excelx
    class Cell
      class Time < Roo::Excelx::Cell::DateTime
        @format: string | nil

        @datetime: ::DateTime

        @value: Link | int

        attr_reader value: Link | int

        attr_reader formula: string | nil

        attr_reader format: string | nil

        attr_reader cell_value: string

        attr_reader coordinate: ::Roo::Excelx::Coordinate

        def initialize: (string value, string | nil formula, [:numeric_or_formula, string] excelx_type, string | nil style, string | nil link, ::Date base_date, ::Roo::Excelx::Coordinate coordinate) -> void

        def formatted_value: () -> string

        alias to_s formatted_value

        def type: () -> (:formula | :link | :time)
      end
    end
  end
end
