D = Steep::Diagnostic

target :test do
  check "."
  signature "."

  repo_path "../../../"
  library "actionpack:6.0"

  library "monitor"
  library "date"
  library "erb"
  library "singleton"
  library "logger"
  library "mutex_m"
  library "time"
  library "activesupport"
  library "actionview"
  library "rack"
  library "cgi"
  library "uri"
 
  configure_code_diagnostics(D::Ruby.all_error)
end
