class ApplicationController < ActionController::Base
  module After
    def self.after: (ActionController::Base) -> untyped
  end

  def controller_instance_method: () -> untyped
  def authenticate: () -> untyped
  def fetch: () -> void
end
