D = Steep::Diagnostic

target :test do
  check "."
  signature "."

  repo_path "../../../"
  library "sidekiq:7.0"
  library "logger"
  library "forwardable"
  library "monitor"
  library "timeout"
  library "connection_pool"
  signature "."

  configure_code_diagnostics(D::Ruby.all_error)
end
