class LessRetryableWorker
  include Sidekiq::Job
  extend Sidekiq::Job::ClassMethods
  def perform: () -> void
end

class LessRetryableJob
  include Sidekiq::Job
  extend Sidekiq::Job::ClassMethods
  def perform: () -> void
end

class NonRetryableWorker
  include Sidekiq::Job
  extend Sidekiq::Job::ClassMethods
  def perform: () -> void
end

class NonRetryableJob
  include Sidekiq::Job
  extend Sidekiq::Job::ClassMethods
  def perform: () -> void
end

class NoDeathWorker
  include Sidekiq::Job
  extend Sidekiq::Job::ClassMethods
  def perform: () -> void
end

class NoDeathJob
  include Sidekiq::Job
  extend Sidekiq::Job::ClassMethods
  def perform: () -> void
end

class WorkerWithCustomRetry
  include Sidekiq::Job
  extend Sidekiq::Job::ClassMethods
  extend Sidekiq::Job::Options::ClassMethods
  def perform: () -> void
end

class JobWithCustomRetry
  include Sidekiq::Job
  extend Sidekiq::Job::ClassMethods
  extend Sidekiq::Job::Options::ClassMethods
  def perform: () -> void
end

class FailingWorker
  include Sidekiq::Job
  extend Sidekiq::Job::ClassMethods
  extend Sidekiq::Job::Options::ClassMethods
  def perform: () -> void
end

class FailingJob
  include Sidekiq::Job
  extend Sidekiq::Job::ClassMethods
  extend Sidekiq::Job::Options::ClassMethods
  def perform: () -> void
end

class ImportantWorker
  include Sidekiq::Job
  extend Sidekiq::Job::ClassMethods
  def perform: () -> void
end

class ImportantJob
  include Sidekiq::Job
  extend Sidekiq::Job::ClassMethods
  def perform: () -> void
end

class YourWorker
  include Sidekiq::Job
  extend Sidekiq::Job::ClassMethods
  def perform: () -> void
end

class YourJob
  include Sidekiq::Job
  extend Sidekiq::Job::ClassMethods
  def perform: () -> void
end
