task :generate do
  load 'generate.rb'
end

task :validate do
  sh "bundle exec rbs --repo ../../ -r ripper -I out validate --silent"
end

task :replace do
  target = "../0.9"
  rm_rf target
  mv 'out', target
end

task default: [:generate, :validate, :replace]
