module Stripe
  module Issuing
    class PersonalizationDesignService < StripeService
      def create: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Issuing::PersonalizationDesign

      def list: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::Issuing::PersonalizationDesign]

      def retrieve: (String personalization_design, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Issuing::PersonalizationDesign

      def update: (String personalization_design, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Issuing::PersonalizationDesign
    end
  end
end
