module Stripe
  module Issuing
    class PhysicalBundleService < StripeService
      def list: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::Issuing::PhysicalBundle]

      def retrieve: (String physical_bundle, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::Issuing::PhysicalBundle
    end
  end
end
