module Axlsx
  class Package
    def to_stream: (?bool) -> (StringIO | false)
    def workbook: () ?{ (Workbook) -> void } -> Workbook
  end

  class Workbook
    def add_worksheet: (*untyped options) ?{ (Worksheet) -> void } -> Worksheet
  end

  class Worksheet
  end
end
