module Axlsx
  # XML Encoding
  ENCODING: ::String

  # spreadsheetML namespace
  XML_NS: ::String

  # content-types namespace
  XML_NS_T: ::String

  # extended-properties namespace
  APP_NS: ::String

  # doc props namespace
  APP_NS_VT: ::String

  # core properties namespace
  CORE_NS: ::String

  # dc elements (core) namespace
  CORE_NS_DC: ::String

  # dcmit (core) namespcace
  CORE_NS_DCMIT: ::String

  # dc terms namespace
  CORE_NS_DCT: ::String

  # xml schema namespace
  CORE_NS_XSI: ::String

  # Digital signature namespace
  DIGITAL_SIGNATURE_NS: ::String

  # spreadsheet drawing namespace
  XML_NS_XDR: ::String

  # drawing namespace
  XML_NS_A: ::String

  # chart namespace
  XML_NS_C: ::String

  # relationships namespace
  XML_NS_R: ::String

  # relationships name space
  RELS_R: ::String

  # table rels namespace
  TABLE_R: ::String

  # pivot table rels namespace
  PIVOT_TABLE_R: ::String

  # pivot table cache definition namespace
  PIVOT_TABLE_CACHE_DEFINITION_R: ::String

  # workbook rels namespace
  WORKBOOK_R: ::String

  # worksheet rels namespace
  WORKSHEET_R: ::String

  # app rels namespace
  APP_R: ::String

  # core rels namespace
  CORE_R: ::String

  # digital signature rels namespace
  DIGITAL_SIGNATURE_R: ::String

  # styles rels namespace
  STYLES_R: ::String

  # shared strings namespace
  SHARED_STRINGS_R: ::String

  # drawing rels namespace
  DRAWING_R: ::String

  # chart rels namespace
  CHART_R: ::String

  # image rels namespace
  IMAGE_R: ::String

  # hyperlink rels namespace
  HYPERLINK_R: ::String

  # comment rels namespace
  COMMENT_R: ::String

  # comment relation for nil target
  COMMENT_R_NULL: ::String

  # vml drawing relation namespace
  VML_DRAWING_R: ::String

  # VML Drawing content type
  VML_DRAWING_CT: ::String

  # table content type
  TABLE_CT: ::String

  # pivot table content type
  PIVOT_TABLE_CT: ::String

  # pivot table cache definition content type
  PIVOT_TABLE_CACHE_DEFINITION_CT: ::String

  # workbook content type
  WORKBOOK_CT: ::String

  # app content type
  APP_CT: ::String

  # rels content type
  RELS_CT: ::String

  # styles content type
  STYLES_CT: ::String

  # xml content type
  XML_CT: ::String

  # worksheet content type
  WORKSHEET_CT: ::String

  # shared strings content type
  SHARED_STRINGS_CT: ::String

  # core content type
  CORE_CT: ::String

  # digital signature xml content type
  DIGITAL_SIGNATURE_XML_CT: ::String

  # digital signature origin content type
  DIGITAL_SIGNATURE_ORIGIN_CT: ::String

  # digital signature certificate content type
  DIGITAL_SIGNATURE_CERTIFICATE_CT: ::String

  # chart content type
  CHART_CT: ::String

  # comments content type
  COMMENT_CT: ::String

  # jpeg content type
  JPEG_CT: ::String

  # gif content type
  GIF_CT: ::String

  # png content type
  PNG_CT: ::String

  # drawing content type
  DRAWING_CT: ::String

  # xml content type extensions
  XML_EX: ::String

  # jpeg extensions
  JPEG_EXS: Array[::String]

  # gif extension
  GIF_EX: ::String

  # png extension
  PNG_EX: ::String

  # rels content type extension
  RELS_EX: ::String

  # workbook part
  WORKBOOK_PN: ::String

  # styles part
  STYLES_PN: ::String

  # shared_strings  part
  SHARED_STRINGS_PN: ::String

  # app part
  APP_PN: ::String

  # core part
  CORE_PN: ::String

  # content types part
  CONTENT_TYPES_PN: ::String

  # rels part
  RELS_PN: ::String

  # workbook rels part
  WORKBOOK_RELS_PN: ::String

  # worksheet part
  WORKSHEET_PN: ::String

  # worksheet rels part
  WORKSHEET_RELS_PN: ::String

  # drawing part
  DRAWING_PN: ::String

  # drawing rels part
  DRAWING_RELS_PN: ::String

  # vml drawing part
  VML_DRAWING_PN: ::String

  # drawing part
  TABLE_PN: ::String

  # pivot table parts
  PIVOT_TABLE_PN: ::String

  # pivot table cache definition part name
  PIVOT_TABLE_CACHE_DEFINITION_PN: ::String

  # pivot table rels parts
  PIVOT_TABLE_RELS_PN: ::String

  # chart part
  CHART_PN: ::String

  # chart part
  IMAGE_PN: ::String

  # comment part
  COMMENT_PN: ::String

  # location of schema files for validation
  SCHEMA_BASE: ::String

  # App validation schema
  APP_XSD: ::String

  # core validation schema
  CORE_XSD: ::String

  # content types validation schema
  CONTENT_TYPES_XSD: ::String

  # rels validation schema
  RELS_XSD: ::String

  # spreadsheetML validation schema
  SML_XSD: ::String

  # drawing validation schema
  DRAWING_XSD: ::String

  # number format id for percentage formatting using the default formatting id.
  NUM_FMT_PERCENT: ::Integer

  # number format id for date format like 2011/11/13
  NUM_FMT_YYYYMMDD: ::Integer

  # number format id for time format the creates 2011/11/13 12:23:10
  NUM_FMT_YYYYMMDDHHMMSS: ::Integer

  # cellXfs id for thin borders around the cell
  STYLE_THIN_BORDER: ::Integer

  # cellXfs id for default date styling
  STYLE_DATE: ::Integer

  # worksheet maximum name length
  WORKSHEET_MAX_NAME_LENGTH: ::Integer

  # worksheet name forbidden characters
  WORKSHEET_NAME_FORBIDDEN_CHARS: Array[::String]

  # error messages RestrictionValidor
  ERR_RESTRICTION: ::String

  # error message DataTypeValidator
  ERR_TYPE: ::String

  # error message for RegexValidator
  ERR_REGEX: ::String

  # error message for RangeValidator
  ERR_RANGE: ::String

  # error message for sheets that use explicit empty string name
  ERR_SHEET_NAME_EMPTY: ::String

  # error message for sheets that use a name which is longer than 31 bytes
  ERR_SHEET_NAME_TOO_LONG: ::String

  # error message for sheets that use a name which include invalid characters
  ERR_SHEET_NAME_CHARACTER_FORBIDDEN: ::String

  # error message for duplicate sheet names
  ERR_DUPLICATE_SHEET_NAME: ::String

  # error message when user does not provide color and or style options for border in Style#add_sytle
  ERR_INVALID_BORDER_OPTIONS: ::String

  # error message for invalid border id reference
  ERR_INVALID_BORDER_ID: ::String

  # error message for invalid angles
  ERR_ANGLE: ::String

  # error message for non 'integerish' value
  ERR_INTEGERISH: ::String

  # error message for invalid cell reference
  ERR_CELL_REFERENCE_INVALID: ::String

  # error message for cell reference with last cell missing
  ERR_CELL_REFERENCE_MISSING_CELL: ::String

  # The regular expression used to remove control characters from worksheets
  CONTROL_CHARS: ::String

  # ISO 8601 date recognition
  ISO_8601_REGEX: ::Regexp

  # FLOAT recognition
  SAFE_FLOAT_REGEX: ::Regexp

  MAYBE_FLOAT_REGEX: ::Regexp

  # Numeric recognition
  NUMERIC_REGEX: ::Regexp

  # Leading characters that indicate a formula.
  # See: https://owasp.org/www-community/attacks/CSV_Injection
  FORMULA_PREFIX: ::String

  # Leading characters that indicate an array formula.
  ARRAY_FORMULA_PREFIX: ::String

  # Trailing character that indicates an array formula.
  ARRAY_FORMULA_SUFFIX: ::String

  BOOLEAN_VALUES: Array[bool]
end
