module ActiveSupport
  module Callbacks
    module ClassMethods
      # Manual definition to make block optional
      def set_callback: (untyped name, *untyped filter_list) ?{ () -> untyped } -> untyped

      # Manual definition to make block optional
      def skip_callback: (untyped name, *untyped filter_list) ?{ () -> untyped } -> untyped
    end
  end

  module Configurable
    module ClassMethods
      # Manual definition to make block optional
      def config_accessor: (*untyped names, ?instance_accessor: bool instance_accessor, ?instance_writer: bool instance_writer, ?instance_reader: bool instance_reader) ?{ () -> untyped } -> untyped
    end
  end

  class Deprecation
    class DeprecatedConstantProxy
      # Manual definition to make block optional
      def self.new: (*untyped args, **untyped kwargs) ?{ () -> untyped } -> untyped
    end
  end

  class HashWithIndifferentAccess[T, U] < Hash[T, U]
    # Manual definition to make block optional
    def fetch_values: (*untyped indices) ?{ () -> untyped } -> untyped

    # Manual definition to make block optional
    def merge: (untyped hash) ?{ () -> untyped } -> untyped

    # Manual definition to make block optional
    def select: (*untyped args) ?{ () -> untyped } -> untyped

    # Manual definition to make block optional
    def reject: (*untyped args) ?{ () -> untyped } -> untyped

    # Manual definition to make block optional
    def transform_values: (*untyped args) ?{ () -> untyped } -> untyped

    # Manual definition to make block optional
    def transform_keys: (*untyped args) ?{ () -> untyped } -> untyped

    # Manual definition to make block optional
    def transform_keys!: () ?{ (untyped) -> untyped } -> untyped
  end

  module Testing
    module TimeHelpers
      # Manual definition to make block optional
      def travel: (untyped duration) ?{ () -> untyped } -> untyped

      # Manual definition to make block optional
      def travel_to: (untyped date_or_time) ?{ () -> untyped } -> untyped

      # Manual definition to make block optional
      def freeze_time: () ?{ () -> untyped } -> untyped
    end
  end

end

class Hash[unchecked out K, unchecked out V]
  # Manual definition to make block optional
  def deep_merge: (untyped other_hash) ?{ () -> untyped } -> untyped

  # Manual definition to make block optional
  def deep_merge!: (untyped other_hash) ?{ () -> untyped } -> untyped
end

class Module
  # Manual definition to make block optional
  def mattr_reader: (*untyped syms, ?default: untyped? default, ?instance_accessor: bool instance_accessor, ?instance_reader: bool instance_reader) ?{ () -> untyped } -> untyped

  # Manual definition to make block optional
  def mattr_writer: (*untyped syms, ?default: untyped? default, ?instance_accessor: bool instance_accessor, ?instance_writer: bool instance_writer) ?{ () -> untyped } -> untyped

  # Manual definition to make block optional
  def mattr_accessor: (*untyped syms, ?default: untyped? default, ?instance_accessor: bool instance_accessor, ?instance_writer: bool instance_writer, ?instance_reader: bool instance_reader) ?{ () -> untyped } -> untyped
end
