name: RuboCop

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  rubocop:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v5
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ruby
        bundler-cache: true
    - name: 'Install dependencies'
      run: 'bundle install'
    - name: 'Run RuboCop'
      run: 'bundle exec rubocop --format github'
