name: 'Test PR comment'

on:
  pull_request_target:
    types:
      - opened
      - ready_for_review

jobs:
  create_comment:
    if: github.event.pull_request.draft == false
    runs-on: 'ubuntu-latest'
    permissions:
      pull-requests: write
      contents: read
    env:
      BASE_SHA: ${{ github.event.pull_request.base.sha }}
      HEAD_SHA: ${{ github.event.pull_request.head.sha }}
      PR_AUTHOR: ${{ github.event.pull_request.user.login }}
      PR_NUMBER: ${{ github.event.pull_request.number }}
      GH_REPO: ${{ github.repository }}
    steps:
      - uses: actions/checkout@v5
        with:
          filter: 'blob:none'
          fetch-depth: 0
          ref: main
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby
          bundler-cache: false
      - name: Changed gems and non gem files
        id: changes
        run: |
          ruby .github/workflows/pr_bot/changed_files.rb
      - name: Prepare comment body
        id: comment-body
        env:
          CHANGED_GEMS: ${{ steps.changes.outputs.gems }}
          CHANGED_NON_GEMS: ${{ steps.changes.outputs.non_gems }}
        run: |
          ruby .github/workflows/pr_bot/welcome_comment_body.rb "$CHANGED_GEMS" "$CHANGED_NON_GEMS"
      - name: Send a comment
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMENT_BODY: ${{ steps.comment-body.outputs.welcome_comment_body }}
        run:
          gh pr comment "$PR_NUMBER" --body "$COMMENT_BODY" --repo "$GH_REPO"
