module Stripe
  module ThreeDSecure
    class AuthenticationService < StripeService
      def cancel: (String authentication, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ThreeDSecure::Authentication

      def create: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ThreeDSecure::Authentication

      def list: (?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ListObject[::Stripe::ThreeDSecure::Authentication]

      def retrieve: (String authentication, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ThreeDSecure::Authentication

      def submit: (String authentication, ?::Hash[untyped, untyped] params, ?::Stripe::request_opts opts) -> ::Stripe::ThreeDSecure::Authentication
    end
  end
end
