module Holidays
  WEEKS: [Symbol, Integer]

  MONTH_LENGTHS: ::Array[Integer]

  DAY_SYMBOLS: ::Array[Symbol]

  def self.on: (untyped date, *untyped options) -> Array[{ date: untyped, name: String, regions: Array[Symbol] }]

  def self.between: (untyped start_date, untyped end_date, *untyped options) -> Array[{ date: untyped, name: String, regions: ::Array[Symbol] }]
end
