module Holidays
  WEEKS: [Symbol, Integer]

  MONTH_LENGTHS: ::Array[Integer]

  DAY_SYMBOLS: ::Array[Symbol]

  def self.on: (Date date, *untyped options) -> Array[{ date: Date, name: String, regions: Array[Symbol] }]

  def self.between: (Date start_date, Date end_date, *untyped options) -> Array[{ date: Date, name: String, regions: ::Array[Symbol] }]
end
