module Kernel
  def String!: (String) -> void
  def Symbol!: (Symbol) -> void
  def Array!: (Array[untyped]) -> void
  def Node!: (AST::Node) -> void
  def Bool!: (bool) -> void
end

class X
  extend AST::Sexp
end
